#!/usr/bin/env python3
"""Replace the "1,650+ chemicals" claim with the number of chemicals that have data.

The source spreadsheet has 1,651 rows, but 661 of them are synonyms that point
at another row and carry no ratings. 990 rows have data, for 835 distinct
chemicals. Pages generated by build_*.py state their own counts; this covers
the remaining hand-maintained pages. Idempotent.

    python3 fix_chemical_count.py [--check]
"""
import os
import re
import sys

import resistance_data as rd

ROOT = os.path.dirname(os.path.abspath(__file__))
SKIP_DIRS = {'.git', '.venv', '__pycache__', 'node_modules', 'data'}
CLAIM = re.compile(r'\b1[,.   ]?6(?:5[01]|00)(\+?)(?![\d.,]*\d)')


def main():
    check = '--check' in sys.argv
    chems, _ = rd.load()
    n = len(chems) // 10 * 10          # 835 -> "830+"
    changed = hits = 0
    for base, dirs, files in os.walk(ROOT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for name in files:
            if not (name.endswith('.html') or name == 'llms.txt'):
                continue
            path = os.path.join(base, name)
            with open(path, encoding='utf-8', errors='replace') as f:
                page = f.read()
            new, k = CLAIM.subn(lambda m: '%d+' % n if m.group(1) else str(n), page)
            if k:
                hits += k
                changed += 1
                if not check:
                    with open(path, 'w', encoding='utf-8') as f:
                        f.write(new)
    print('%s %d files, %d claims -> %d+' % ('would change' if check else 'changed', changed, hits, n))


if __name__ == '__main__':
    main()
