#!/usr/bin/env python3
"""
Translate all German chemical names to Spanish for chemicalresistance.org
"""
import json
import re

# Comprehensive German → Spanish chemical term translations
# Order matters - more specific terms first

TERM_TRANSLATIONS = {
    # Specific compounds first (most specific match wins)
    'acetanhydrid': 'anhídrido acético',
    'acetylchlorid': 'cloruro de acetilo',
    'benzoylchlorid': 'cloruro de benzoilo',
    'benzylchlorid': 'cloruro de bencilo',
    'amylchlorid': 'cloruro de amilo',
    'carbonylchlorid': 'fosgeno',
    'thionylchlorid': 'cloruro de tionilo',
    'sulfurylchlorid': 'cloruro de sulfurilo',
    'acetylentetrachlorid': 'tetracloroetano',
    'acetylentetrabromid': 'tetrabromoetano',
    'antimonpentachlorid': 'pentacloruro de antimonio',
    'antimontrichlorid': 'tricloruro de antimonio',
    'antimon-(iii)-chlorid': 'cloruro de antimonio(III)',
    'antimon-(v)-chlorid': 'cloruro de antimonio(V)',
    'anilinhydrochlorid': 'clorhidrato de anilina',
    'aniliniumchlorid': 'cloruro de anilinio',
    'arsenanhydrid': 'anhídrido arsenioso',
    'arsensäureanhydrid': 'anhídrido arsénico',
    'benzolhexachlorid': 'hexaclorociclohexano',
    'bismutchlorid': 'cloruro de bismuto',
    'buttersäureethylester': 'butirato de etilo',
    'buttersäuremethylester': 'butirato de metilo',
    'bernsteinsäurediethylester': 'succinato de dietilo',
    'phthalsäurediethylester': 'ftalato de dietilo',
    'phthalsäuredibutylester': 'ftalato de dibutilo',
    'phthalsäuredioctylester': 'ftalato de dioctilo',
    'sebacinsäure': 'ácido sebácico',
    
    # Esters - specific compounds
    'acrylsäurebutylester': 'acrilato de butilo',
    'acrylsäureethylester': 'acrilato de etilo',
    'acrylsäuremethylester': 'acrilato de metilo',
    'acrylsäurenitril': 'acrilonitrilo',
    'ameisensäureamid': 'formamida',
    'ameisensäureethylester': 'formiato de etilo',
    'ameisensäuremethylester': 'formiato de metilo',
    'essigsäureanhydrid': 'anhídrido acético',
    'essigsäureamid': 'acetamida',
    'essigsäurebutylester': 'acetato de butilo',
    'essigsäureethylester': 'acetato de etilo',
    'essigsäuremethylester': 'acetato de metilo',
    'essigsäureamylester': 'acetato de amilo',
    'essigsäurepropylester': 'acetato de propilo',
    'essigsäurevinylester': 'acetato de vinilo',
    'essigsäureallylester': 'acetato de alilo',
    'essigsäurebenzylester': 'acetato de bencilo',
    'essigsäure-n-amylester': 'acetato de n-amilo',
    'essigsäure silbersalz': 'acetato de plata',
    'chloressigsäureethylester': 'cloroacetato de etilo',
    'chloressigsäuremethylester': 'cloroacetato de metilo',
    'dichloressigsäuremethylester': 'dicloroacetato de metilo',
    'cyanessigsäureethylester': 'cianoacetato de etilo',
    'benzoesäurealdehyd': 'benzaldehído',
    'benzoesäurechlorid': 'cloruro de benzoilo',
    'benzoesäureethylester': 'benzoato de etilo',
    'benzoesäuremethylester': 'benzoato de metilo',
    'benzoesäurebenzylester': 'benzoato de bencilo',
    'benzoesäure natriumsalz': 'benzoato de sodio',
    'adipinsäuredioctylester': 'adipato de dioctilo',
    
    # Acids (Säuren → Ácidos)
    'schwefelsäure': 'ácido sulfúrico',
    'salzsäure': 'ácido clorhídrico',
    'salpetersäure': 'ácido nítrico',
    'phosphorsäure': 'ácido fosfórico',
    'essigsäure': 'ácido acético',
    'ameisensäure': 'ácido fórmico',
    'zitronensäure': 'ácido cítrico',
    'milchsäure': 'ácido láctico',
    'oxalsäure': 'ácido oxálico',
    'chromsäure': 'ácido crómico',
    'flusssäure': 'ácido fluorhídrico',
    'fluorwasserstoffsäure': 'ácido fluorhídrico',
    'kohlensäure': 'ácido carbónico',
    'borsäure': 'ácido bórico',
    'benzoesäure': 'ácido benzoico',
    'weinsäure': 'ácido tartárico',
    'bernsteinsäure': 'ácido succínico',
    'maleinsäure': 'ácido maleico',
    'fumarsäure': 'ácido fumárico',
    'adipinsäure': 'ácido adípico',
    'stearinsäure': 'ácido esteárico',
    'ölsäure': 'ácido oleico',
    'palmitinsäure': 'ácido palmítico',
    'laurinsäure': 'ácido láurico',
    'caprylsäure': 'ácido caprílico',
    'capronsäure': 'ácido caproico',
    'buttersäure': 'ácido butírico',
    'propionsäure': 'ácido propiónico',
    'acrylsäure': 'ácido acrílico',
    'methacrylsäure': 'ácido metacrílico',
    'glykolsäure': 'ácido glicólico',
    'glycolsäure': 'ácido glicólico',
    'brenztraubensäure': 'ácido pirúvico',
    'glutaminsäure': 'ácido glutámico',
    'asparaginsäure': 'ácido aspártico',
    'phthalsäure': 'ácido ftálico',
    'isophthalsäure': 'ácido isoftálico',
    'terephthalsäure': 'ácido tereftálico',
    'toluolsulfonsäure': 'ácido toluensulfónico',
    'benzolsulfonsäure': 'ácido bencenosulfónico',
    'sulfanilsäure': 'ácido sulfanílico',
    'pikrinsäure': 'ácido pícrico',
    'gallussäure': 'ácido gálico',
    'gerbsäure': 'ácido tánico',
    'harnsäure': 'ácido úrico',
    'hippursäure': 'ácido hipúrico',
    'ascorbinsäure': 'ácido ascórbico',
    'nikotinsäure': 'ácido nicotínico',
    'folsäure': 'ácido fólico',
    'fettsäure': 'ácido graso',
    'fettsäuren': 'ácidos grasos',
    'aminoessigsäure': 'glicina',
    'aminoethansäure': 'glicina',
    'aminopropionsäure': 'alanina',
    'aminosäure': 'aminoácido',
    'aminosäuren': 'aminoácidos',
    'carbonsäure': 'ácido carboxílico',
    'dicarbonsäure': 'ácido dicarboxílico',
    'tricarbonsäure': 'ácido tricarboxílico',
    'monocarbonsäure': 'ácido monocarboxílico',
    'hydroxycarbonsäure': 'ácido hidroxicarboxílico',
    'sulfonsäure': 'ácido sulfónico',
    'phosphonsäure': 'ácido fosfónico',
    'arsensäure': 'ácido arsénico',
    'arsenigsäure': 'ácido arsenioso',
    'antimonsäure': 'ácido antimónico',
    'kieselsäure': 'ácido silícico',
    'kieselflusssäure': 'ácido fluorosilícico',
    'hexafluorokieselsäure': 'ácido hexafluorosilícico',
    'perchlorsäure': 'ácido perclórico',
    'chlorsäure': 'ácido clórico',
    'hypochlorigsäure': 'ácido hipocloroso',
    'chlorigsäure': 'ácido cloroso',
    'bromsäure': 'ácido brómico',
    'bromwasserstoffsäure': 'ácido bromhídrico',
    'jodwasserstoffsäure': 'ácido yodhídrico',
    'jodsäure': 'ácido yódico',
    'periodsäure': 'ácido peryódico',
    'blausäure': 'ácido cianhídrico',
    'cyanwasserstoffsäure': 'ácido cianhídrico',
    'rhodanwasserstoffsäure': 'ácido tiociánico',
    'thiocyansäure': 'ácido tiociánico',
    'schwefelwasserstoffsäure': 'ácido sulfhídrico',
    'schwefligesäure': 'ácido sulfuroso',
    'unterschwefligesäure': 'ácido tiosulfúrico',
    'thioschwefelsäure': 'ácido tiosulfúrico',
    'selensäure': 'ácido selénico',
    'tellursäure': 'ácido telúrico',
    'molybdänsäure': 'ácido molíbdico',
    'wolframsäure': 'ácido túngstico',
    'vanadinsäure': 'ácido vanádico',
    'permangansäure': 'ácido permangánico',
    'übermangansäure': 'ácido permangánico',
    'mangansäure': 'ácido mangánico',
    'salicylsäure': 'ácido salicílico',
    'acetylsalicylsäure': 'ácido acetilsalicílico',
    'zimtsäure': 'ácido cinámico',
    'sorbinsäure': 'ácido sórbico',
    'peressigsäure': 'ácido peracético',
    'crotonsäure': 'ácido crotónico',
    'linolsäure': 'ácido linoleico',
    'linolensäure': 'ácido linolénico',
    'chloressigsäure': 'ácido cloroacético',
    'dichloressigsäure': 'ácido dicloroacético',
    'trichloressigsäure': 'ácido tricloroacético',
    'akkusäure': 'ácido de batería',
    'säure': 'ácido',
    
    # Bases/Hydroxides
    'natronlauge': 'sosa cáustica',
    'kalilauge': 'potasa cáustica',
    'natriumhydroxid': 'hidróxido de sodio',
    'kaliumhydroxid': 'hidróxido de potasio',
    'calciumhydroxid': 'hidróxido de calcio',
    'magnesiumhydroxid': 'hidróxido de magnesio',
    'bariumhydroxid': 'hidróxido de bario',
    'strontiumhydroxid': 'hidróxido de estroncio',
    'lithiumhydroxid': 'hidróxido de litio',
    'ammoniumhydroxid': 'hidróxido de amonio',
    'aluminiumhydroxid': 'hidróxido de aluminio',
    'eisenhydroxid': 'hidróxido de hierro',
    'kupferhydroxid': 'hidróxido de cobre',
    'zinkhydroxid': 'hidróxido de zinc',
    'hydroxid': 'hidróxido',
    'lauge': 'lejía',
    
    # Salts - Chlorides
    'natriumchlorid': 'cloruro de sodio',
    'kaliumchlorid': 'cloruro de potasio',
    'calciumchlorid': 'cloruro de calcio',
    'magnesiumchlorid': 'cloruro de magnesio',
    'bariumchlorid': 'cloruro de bario',
    'strontiumchlorid': 'cloruro de estroncio',
    'lithiumchlorid': 'cloruro de litio',
    'ammoniumchlorid': 'cloruro de amonio',
    'aluminiumchlorid': 'cloruro de aluminio',
    'eisenchlorid': 'cloruro de hierro',
    'eisen(iii)chlorid': 'cloruro de hierro(III)',
    'eisen(ii)chlorid': 'cloruro de hierro(II)',
    'kupferchlorid': 'cloruro de cobre',
    'zinkchlorid': 'cloruro de zinc',
    'zinnchlorid': 'cloruro de estaño',
    'bleichlorid': 'cloruro de plomo',
    'quecksilberchlorid': 'cloruro de mercurio',
    'silberchlorid': 'cloruro de plata',
    'goldchlorid': 'cloruro de oro',
    'platinchlorid': 'cloruro de platino',
    'nickelchlorid': 'cloruro de níquel',
    'cobaltchlorid': 'cloruro de cobalto',
    'manganchlorid': 'cloruro de manganeso',
    'chromchlorid': 'cloruro de cromo',
    'titantetrachlorid': 'tetracloruro de titanio',
    'siliciumtetrachlorid': 'tetracloruro de silicio',
    'kohlenstofftetrachlorid': 'tetracloruro de carbono',
    'tetrachlorkohlenstoff': 'tetracloruro de carbono',
    'chlorid': 'cloruro',
    
    # Salts - Sulfates
    'natriumsulfat': 'sulfato de sodio',
    'kaliumsulfat': 'sulfato de potasio',
    'calciumsulfat': 'sulfato de calcio',
    'magnesiumsulfat': 'sulfato de magnesio',
    'bariumsulfat': 'sulfato de bario',
    'ammoniumsulfat': 'sulfato de amonio',
    'aluminiumsulfat': 'sulfato de aluminio',
    'eisensulfat': 'sulfato de hierro',
    'kupfersulfat': 'sulfato de cobre',
    'zinksulfat': 'sulfato de zinc',
    'nickelsulfat': 'sulfato de níquel',
    'cobaltsulfat': 'sulfato de cobalto',
    'mangansulfat': 'sulfato de manganeso',
    'chromsulfat': 'sulfato de cromo',
    'sulfat': 'sulfato',
    
    # Salts - Nitrates
    'natriumnitrat': 'nitrato de sodio',
    'kaliumnitrat': 'nitrato de potasio',
    'calciumnitrat': 'nitrato de calcio',
    'magnesiumnitrat': 'nitrato de magnesio',
    'bariumnitrat': 'nitrato de bario',
    'ammoniumnitrat': 'nitrato de amonio',
    'aluminiumnitrat': 'nitrato de aluminio',
    'eisennitrat': 'nitrato de hierro',
    'kupfernitrat': 'nitrato de cobre',
    'zinknitrat': 'nitrato de zinc',
    'silbernitrat': 'nitrato de plata',
    'bleinitrat': 'nitrato de plomo',
    'nitrat': 'nitrato',
    
    # Salts - Carbonates
    'natriumcarbonat': 'carbonato de sodio',
    'kaliumcarbonat': 'carbonato de potasio',
    'calciumcarbonat': 'carbonato de calcio',
    'magnesiumcarbonat': 'carbonato de magnesio',
    'bariumcarbonat': 'carbonato de bario',
    'ammoniumcarbonat': 'carbonato de amonio',
    'lithiumcarbonat': 'carbonato de litio',
    'natriumhydrogencarbonat': 'hidrogenocarbonato de sodio',
    'kaliumhydrogencarbonat': 'hidrogenocarbonato de potasio',
    'ammoniumhydrogencarbonat': 'hidrogenocarbonato de amonio',
    'natriumbicarbonat': 'bicarbonato de sodio',
    'kaliumbicarbonat': 'bicarbonato de potasio',
    'ammoniumbicarbonat': 'bicarbonato de amonio',
    'carbonat': 'carbonato',
    'bicarbonat': 'bicarbonato',
    'hydrogencarbonat': 'hidrogenocarbonato',
    
    # Salts - Phosphates
    'natriumphosphat': 'fosfato de sodio',
    'kaliumphosphat': 'fosfato de potasio',
    'calciumphosphat': 'fosfato de calcio',
    'ammoniumphosphat': 'fosfato de amonio',
    'phosphat': 'fosfato',
    'hydrogenphosphat': 'hidrogenofosfato',
    'dihydrogenphosphat': 'dihidrogenofosfato',
    'polyphosphat': 'polifosfato',
    'metaphosphat': 'metafosfato',
    'pyrophosphat': 'pirofosfato',
    
    # Salts - Others
    'natriumsulfit': 'sulfito de sodio',
    'natriumthiosulfat': 'tiosulfato de sodio',
    'natriumhypochlorit': 'hipoclorito de sodio',
    'calciumhypochlorit': 'hipoclorito de calcio',
    'natriumchlorat': 'clorato de sodio',
    'kaliumchlorat': 'clorato de potasio',
    'natriumperchlorat': 'perclorato de sodio',
    'kaliumperchlorat': 'perclorato de potasio',
    'natriumfluorid': 'fluoruro de sodio',
    'kaliumfluorid': 'fluoruro de potasio',
    'calciumfluorid': 'fluoruro de calcio',
    'ammoniumfluorid': 'fluoruro de amonio',
    'ammoniumbifluorid': 'bifluoruro de amonio',
    'natriumcyanid': 'cianuro de sodio',
    'kaliumcyanid': 'cianuro de potasio',
    'natriumsulfid': 'sulfuro de sodio',
    'kaliumsulfid': 'sulfuro de potasio',
    'ammoniumsulfid': 'sulfuro de amonio',
    'natriumacetat': 'acetato de sodio',
    'kaliumacetat': 'acetato de potasio',
    'calciumacetat': 'acetato de calcio',
    'ammoniumacetat': 'acetato de amonio',
    'bleiacetat': 'acetato de plomo',
    'kupferacetat': 'acetato de cobre',
    'zinkacetat': 'acetato de zinc',
    'natriumformiat': 'formiato de sodio',
    'kaliumformiat': 'formiato de potasio',
    'natriumoxalat': 'oxalato de sodio',
    'kaliumoxalat': 'oxalato de potasio',
    'ammoniumoxalat': 'oxalato de amonio',
    'calciumoxalat': 'oxalato de calcio',
    'natriumcitrat': 'citrato de sodio',
    'kaliumcitrat': 'citrato de potasio',
    'natriumtartrat': 'tartrato de sodio',
    'kaliumtartrat': 'tartrato de potasio',
    'natriumbenzoat': 'benzoato de sodio',
    'kaliumbenzoat': 'benzoato de potasio',
    'natriumsalicylat': 'salicilato de sodio',
    'natriumlactat': 'lactato de sodio',
    'calciumlactat': 'lactato de calcio',
    'natriumgluconat': 'gluconato de sodio',
    'calciumgluconat': 'gluconato de calcio',
    'natriumstearat': 'estearato de sodio',
    'calciumstearat': 'estearato de calcio',
    'zinkstearat': 'estearato de zinc',
    'magnesiumstearat': 'estearato de magnesio',
    'sulfit': 'sulfito',
    'thiosulfat': 'tiosulfato',
    'hypochlorit': 'hipoclorito',
    'chlorat': 'clorato',
    'perchlorat': 'perclorato',
    'bromat': 'bromato',
    'bromid': 'bromuro',
    'jodat': 'yodato',
    'jodid': 'yoduro',
    'fluorid': 'fluoruro',
    'bifluorid': 'bifluoruro',
    'cyanid': 'cianuro',
    'sulfid': 'sulfuro',
    'hydrosulfid': 'hidrosulfuro',
    'acetat': 'acetato',
    'formiat': 'formiato',
    'oxalat': 'oxalato',
    'citrat': 'citrato',
    'tartrat': 'tartrato',
    'benzoat': 'benzoato',
    'salicylat': 'salicilato',
    'lactat': 'lactato',
    'gluconat': 'gluconato',
    'stearat': 'estearato',
    'oleat': 'oleato',
    'laurat': 'laurato',
    'palmitat': 'palmitato',
    'silikat': 'silicato',
    'borat': 'borato',
    'chromat': 'cromato',
    'dichromat': 'dicromato',
    'permanganat': 'permanganato',
    'molybdat': 'molibdato',
    'wolframat': 'tungstato',
    'vanadat': 'vanadato',
    'arsenat': 'arseniato',
    'arsenit': 'arsenito',
    'rhodanid': 'tiocianato',
    'thiocyanat': 'tiocianato',
    'sulfocyanid': 'tiocianato',
    'ferrocyanid': 'ferrocianuro',
    'ferricyanid': 'ferricianuro',
    'nitrit': 'nitrito',
    'nitrid': 'nitruro',
    'hydrid': 'hidruro',
    'amid': 'amiduro',
    'azid': 'azida',
    'peroxid': 'peróxido',
    'superoxid': 'superóxido',
    'oxid': 'óxido',
    
    # Organic compounds - Alcohols
    'methanol': 'metanol',
    'ethanol': 'etanol',
    'äthanol': 'etanol',
    'propanol': 'propanol',
    'isopropanol': 'isopropanol',
    'butanol': 'butanol',
    'isobutanol': 'isobutanol',
    'pentanol': 'pentanol',
    'amylalkohol': 'alcohol amílico',
    'hexanol': 'hexanol',
    'heptanol': 'heptanol',
    'octanol': 'octanol',
    'decanol': 'decanol',
    'dodecanol': 'dodecanol',
    'benzylalkohol': 'alcohol bencílico',
    'cyclohexanol': 'ciclohexanol',
    'ethylenglykol': 'etilenglicol',
    'äthylenglykol': 'etilenglicol',
    'propylenglykol': 'propilenglicol',
    'diethylenglykol': 'dietilenglicol',
    'triethylenglykol': 'trietilenglicol',
    'polyethylenglykol': 'polietilenglicol',
    'glycerin': 'glicerina',
    'glyzerin': 'glicerina',
    'glycerol': 'glicerol',
    'allylalkohol': 'alcohol alílico',
    'alkohol': 'alcohol',
    
    # Organic compounds - Aldehydes & Ketones
    'formaldehyd': 'formaldehído',
    'acetaldehyd': 'acetaldehído',
    'propionaldehyd': 'propionaldehído',
    'butyraldehyd': 'butiraldehído',
    'benzaldehyd': 'benzaldehído',
    'furfural': 'furfural',
    'acrolein': 'acroleína',
    'crotonaldehyd': 'crotonaldehído',
    'glutaraldehyd': 'glutaraldehído',
    'aldehyd': 'aldehído',
    'aceton': 'acetona',
    'methylethylketon': 'metiletilcetona',
    'methylisobutylketon': 'metilisobutilcetona',
    'cyclohexanon': 'ciclohexanona',
    'acetophenon': 'acetofenona',
    'keton': 'cetona',
    
    # Organic compounds - Ethers
    'diethylether': 'éter dietílico',
    'diäthylether': 'éter dietílico',
    'äther': 'éter',
    'ether': 'éter',
    'tetrahydrofuran': 'tetrahidrofurano',
    'dioxan': 'dioxano',
    'anisol': 'anisol',
    
    # Organic compounds - Esters
    'methylacetat': 'acetato de metilo',
    'ethylacetat': 'acetato de etilo',
    'äthylacetat': 'acetato de etilo',
    'butylacetat': 'acetato de butilo',
    'amylacetat': 'acetato de amilo',
    'isoamylacetat': 'acetato de isoamilo',
    'benzylacetat': 'acetato de bencilo',
    'methylformiat': 'formiato de metilo',
    'ethylformiat': 'formiato de etilo',
    'methylbenzoat': 'benzoato de metilo',
    'ethylbenzoat': 'benzoato de etilo',
    'methylsalicylat': 'salicilato de metilo',
    'methylmethacrylat': 'metacrilato de metilo',
    'ethylacrylat': 'acrilato de etilo',
    'butylacrylat': 'acrilato de butilo',
    'dioctylphthalat': 'ftalato de dioctilo',
    'dibutylphthalat': 'ftalato de dibutilo',
    'ester': 'éster',
    
    # Organic compounds - Amines
    'methylamin': 'metilamina',
    'dimethylamin': 'dimetilamina',
    'trimethylamin': 'trimetilamina',
    'ethylamin': 'etilamina',
    'äthylamin': 'etilamina',
    'diethylamin': 'dietilamina',
    'triethylamin': 'trietilamina',
    'propylamin': 'propilamina',
    'isopropylamin': 'isopropilamina',
    'butylamin': 'butilamina',
    'cyclohexylamin': 'ciclohexilamina',
    'anilin': 'anilina',
    'toluidin': 'toluidina',
    'benzylamin': 'bencilamina',
    'ethanolamin': 'etanolamina',
    'äthanolamin': 'etanolamina',
    'diethanolamin': 'dietanolamina',
    'triethanolamin': 'trietanolamina',
    'ethylendiamin': 'etilendiamina',
    'äthylendiamin': 'etilendiamina',
    'morpholin': 'morfolina',
    'piperidin': 'piperidina',
    'pyrrolidin': 'pirrolidina',
    'pyridin': 'piridina',
    'hydrazin': 'hidrazina',
    'hydroxylamin': 'hidroxilamina',
    'amin': 'amina',
    
    # Organic compounds - Amides
    'formamid': 'formamida',
    'acetamid': 'acetamida',
    'dimethylformamid': 'dimetilformamida',
    'dimethylacetamid': 'dimetilacetamida',
    'harnstoff': 'urea',
    'thioharnstoff': 'tiourea',
    'caprolactam': 'caprolactama',
    
    # Organic compounds - Nitriles
    'acetonitril': 'acetonitrilo',
    'propionitril': 'propionitrilo',
    'benzonitril': 'benzonitrilo',
    'acrylnitril': 'acrilonitrilo',
    'nitril': 'nitrilo',
    
    # Aromatic compounds
    'benzol': 'benceno',
    'toluol': 'tolueno',
    'xylol': 'xileno',
    'ethylbenzol': 'etilbenceno',
    'äthylbenzol': 'etilbenceno',
    'cumol': 'cumeno',
    'styrol': 'estireno',
    'naphthalin': 'naftaleno',
    'anthracen': 'antraceno',
    'phenol': 'fenol',
    'kresol': 'cresol',
    'hydrochinon': 'hidroquinona',
    'resorcin': 'resorcinol',
    'chlorbenzol': 'clorobenceno',
    'dichlorbenzol': 'diclorobenceno',
    'trichlorbenzol': 'triclorobenceno',
    'brombenzol': 'bromobenceno',
    'nitrobenzol': 'nitrobenceno',
    'dinitrobenzol': 'dinitrobenceno',
    'trinitrobenzol': 'trinitrobenceno',
    'nitrotoluol': 'nitrotolueno',
    'dinitrotoluol': 'dinitrotolueno',
    'trinitrotoluol': 'trinitrotolueno',
    
    # Aliphatic hydrocarbons
    'methan': 'metano',
    'ethan': 'etano',
    'äthan': 'etano',
    'propan': 'propano',
    'butan': 'butano',
    'isobutan': 'isobutano',
    'pentan': 'pentano',
    'isopentan': 'isopentano',
    'hexan': 'hexano',
    'heptan': 'heptano',
    'octan': 'octano',
    'isooctan': 'isooctano',
    'nonan': 'nonano',
    'decan': 'decano',
    'dodecan': 'dodecano',
    'cyclohexan': 'ciclohexano',
    'cyclopentan': 'ciclopentano',
    'methylcyclohexan': 'metilciclohexano',
    'ethylen': 'etileno',
    'äthylen': 'etileno',
    'propylen': 'propileno',
    'butylen': 'butileno',
    'butadien': 'butadieno',
    'isopren': 'isopreno',
    'acetylen': 'acetileno',
    
    # Halogenated compounds
    'chlormethan': 'clorometano',
    'dichlormethan': 'diclorometano',
    'trichlormethan': 'triclorometano',
    'chloroform': 'cloroformo',
    'chlorethan': 'cloroetano',
    'dichlorethan': 'dicloroetano',
    'trichlorethan': 'tricloroetano',
    'tetrachlorethan': 'tetracloroetano',
    'trichlorethylen': 'tricloroetileno',
    'tetrachlorethylen': 'tetracloroetileno',
    'perchlorethylen': 'percloroetileno',
    'vinylchlorid': 'cloruro de vinilo',
    'vinylidenchlorid': 'cloruro de vinilideno',
    'allylchlorid': 'cloruro de alilo',
    'epichlorhydrin': 'epiclorhidrina',
    'brommethan': 'bromometano',
    'bromwasserstoff': 'bromuro de hidrógeno',
    'fluorwasserstoff': 'fluoruro de hidrógeno',
    'chlorwasserstoff': 'cloruro de hidrógeno',
    'fluor': 'flúor',
    'chlor': 'cloro',
    'brom': 'bromo',
    'jod': 'yodo',
    
    # Sulfur compounds
    'schwefelwasserstoff': 'sulfuro de hidrógeno',
    'schwefeldioxid': 'dióxido de azufre',
    'schwefeltrioxid': 'trióxido de azufre',
    'schwefelkohlenstoff': 'disulfuro de carbono',
    'kohlenstoffdisulfid': 'disulfuro de carbono',
    'dimethylsulfoxid': 'dimetilsulfóxido',
    'dimethylsulfon': 'dimetilsulfona',
    'thiophene': 'tiofeno',
    'mercaptan': 'mercaptano',
    'thiol': 'tiol',
    'schwefel': 'azufre',
    
    # Nitrogen compounds
    'stickstoff': 'nitrógeno',
    'stickstoffoxid': 'óxido de nitrógeno',
    'stickstoffdioxid': 'dióxido de nitrógeno',
    'distickstoffoxid': 'óxido nitroso',
    'distickstofftetroxid': 'tetróxido de dinitrógeno',
    'stickstoffmonoxid': 'monóxido de nitrógeno',
    'ammoniak': 'amoníaco',
    'ammoniakwasser': 'agua amoniacal',
    
    # Phosphorus compounds
    'phosphor': 'fósforo',
    'phosphortrichlorid': 'tricloruro de fósforo',
    'phosphorpentachlorid': 'pentacloruro de fósforo',
    'phosphoroxychlorid': 'oxicloruro de fósforo',
    
    # Metals
    'natrium': 'sodio',
    'kalium': 'potasio',
    'lithium': 'litio',
    'calcium': 'calcio',
    'magnesium': 'magnesio',
    'barium': 'bario',
    'strontium': 'estroncio',
    'aluminium': 'aluminio',
    'eisen': 'hierro',
    'kupfer': 'cobre',
    'zink': 'zinc',
    'zinn': 'estaño',
    'blei': 'plomo',
    'quecksilber': 'mercurio',
    'silber': 'plata',
    'gold': 'oro',
    'platin': 'platino',
    'palladium': 'paladio',
    'nickel': 'níquel',
    'cobalt': 'cobalto',
    'chrom': 'cromo',
    'mangan': 'manganeso',
    'titan': 'titanio',
    'vanadium': 'vanadio',
    'molybdän': 'molibdeno',
    'wolfram': 'tungsteno',
    'cadmium': 'cadmio',
    'antimon': 'antimonio',
    'arsen': 'arsénico',
    'wismut': 'bismuto',
    'selen': 'selenio',
    'tellur': 'teluro',
    
    # Common technical terms
    'wasserstoff': 'hidrógeno',
    'sauerstoff': 'oxígeno',
    'kohlenstoff': 'carbono',
    'kohlendioxid': 'dióxido de carbono',
    'kohlenmonoxid': 'monóxido de carbono',
    'wasser': 'agua',
    'meerwasser': 'agua de mar',
    'leitungswasser': 'agua del grifo',
    'destilliertes wasser': 'agua destilada',
    'salzwasser': 'agua salada',
    'sole': 'salmuera',
    'kochsalzlösung': 'solución salina',
    'luft': 'aire',
    'ozon': 'ozono',
    'wasserstoffperoxid': 'peróxido de hidrógeno',
    'wasserstoffperoxyd': 'peróxido de hidrógeno',
    
    # Petroleum products
    'benzin': 'gasolina',
    'diesel': 'diésel',
    'dieselkraftstoff': 'combustible diésel',
    'heizöl': 'fueloil',
    'kerosin': 'queroseno',
    'petroleum': 'petróleo',
    'erdöl': 'petróleo crudo',
    'rohöl': 'petróleo crudo',
    'mineralöl': 'aceite mineral',
    'motoröl': 'aceite de motor',
    'hydrauliköl': 'aceite hidráulico',
    'getriebeöl': 'aceite de transmisión',
    'schmieröl': 'aceite lubricante',
    'öl': 'aceite',
    'fett': 'grasa',
    'schmierfett': 'grasa lubricante',
    'paraffin': 'parafina',
    'paraffinöl': 'aceite de parafina',
    'vaseline': 'vaselina',
    'wachs': 'cera',
    'bitumen': 'betún',
    'asphalt': 'asfalto',
    'teer': 'alquitrán',
    
    # Food & beverages
    'bier': 'cerveza',
    'wein': 'vino',
    'rotwein': 'vino tinto',
    'weisswein': 'vino blanco',
    'weißwein': 'vino blanco',
    'essig': 'vinagre',
    'weinessig': 'vinagre de vino',
    'milch': 'leche',
    'vollmilch': 'leche entera',
    'sahne': 'nata',
    'butter': 'mantequilla',
    'käse': 'queso',
    'joghurt': 'yogur',
    'fruchtsaft': 'zumo de frutas',
    'orangensaft': 'zumo de naranja',
    'apfelsaft': 'zumo de manzana',
    'limonade': 'limonada',
    'kaffee': 'café',
    'tee': 'té',
    'kakao': 'cacao',
    'schokolade': 'chocolate',
    'zucker': 'azúcar',
    'glucose': 'glucosa',
    'fructose': 'fructosa',
    'maltose': 'maltosa',
    'lactose': 'lactosa',
    'saccharose': 'sacarosa',
    'stärke': 'almidón',
    'mehl': 'harina',
    'salz': 'sal',
    'kochsalz': 'sal de mesa',
    'honig': 'miel',
    'gelatine': 'gelatina',
    
    # Biological & medical
    'blut': 'sangre',
    'serum': 'suero',
    'plasma': 'plasma',
    'urin': 'orina',
    'kot': 'heces',
    'speichel': 'saliva',
    'galle': 'bilis',
    'insulin': 'insulina',
    'penicillin': 'penicilina',
    'aspirin': 'aspirina',
    'vitamin': 'vitamina',
    'hormon': 'hormona',
    'enzym': 'enzima',
    'protein': 'proteína',
    
    # Cleaning & household
    'seife': 'jabón',
    'waschmittel': 'detergente',
    'spülmittel': 'lavavajillas',
    'reinigungsmittel': 'limpiador',
    'desinfektionsmittel': 'desinfectante',
    'bleichmittel': 'lejía',
    'bleiche': 'lejía',
    
    # Industry
    'tinte': 'tinta',
    'lack': 'laca',
    'farbe': 'pintura',
    'kleber': 'pegamento',
    'klebstoff': 'adhesivo',
    'leim': 'cola',
    'harz': 'resina',
    'kunstharz': 'resina sintética',
    'epoxidharz': 'resina epoxi',
    'polyesterharz': 'resina de poliéster',
    'gummi': 'goma',
    'kautschuk': 'caucho',
    'latex': 'látex',
    'silikon': 'silicona',
    'kunststoff': 'plástico',
    'polymer': 'polímero',
    'zellulose': 'celulosa',
    'glas': 'vidrio',
    'keramik': 'cerámica',
    'beton': 'hormigón',
    'zement': 'cemento',
    'gips': 'yeso',
    'kalk': 'cal',
    'branntkalk': 'cal viva',
    'löschkalk': 'cal apagada',
    'kalkmilch': 'lechada de cal',
    'kreide': 'tiza',
    'kohle': 'carbón',
    'koks': 'coque',
    'graphit': 'grafito',
    
    # Concentration terms
    'konzentriert': 'concentrado',
    'rein': 'puro',
    'technisch': 'técnico',
    'unverdünnt': 'sin diluir',
    'verdünnt': 'diluido',
    'gesättigt': 'saturado',
    'wässrig': 'acuoso',
    'wasserfrei': 'anhidro',
    'flüssig': 'líquido',
    'fest': 'sólido',
    'gasförmig': 'gaseoso',
    
    # Exhaust gases
    'abgase': 'gases de escape',
    'rauchgase': 'gases de combustión',
    'abgas': 'gas de escape',
    
    # Descriptors
    'alkalisch': 'alcalino',
    'sauer': 'ácido',
    'neutral': 'neutro',
    'basisch': 'básico',
    'ätzend': 'corrosivo',
    'giftig': 'tóxico',
    'brennbar': 'inflamable',
    'explosiv': 'explosivo',
    'fluorwasserstoffhaltig': 'que contiene ácido fluorhídrico',
    'kohlendioxidhaltig': 'que contiene dióxido de carbono',
    'nitrosehaltig': 'que contiene óxidos de nitrógeno',
    'salzsäurehaltig': 'que contiene ácido clorhídrico',
    'schwefeldioxidhaltig': 'que contiene dióxido de azufre',
    'schwefelsäurehaltig': 'que contiene ácido sulfúrico',
    'schwefeltrioxidhaltig': 'que contiene trióxido de azufre',
    
    # Common word parts
    'lösung': 'solución',
    'lösungsmittel': 'disolvente',
    'gemisch': 'mezcla',
    'verbindung': 'compuesto',
    'pulver': 'polvo',
    'paste': 'pasta',
    'emulsion': 'emulsión',
    'suspension': 'suspensión',
    'dispersion': 'dispersión',
}

# Additional specific translations
ADDITIONAL_TRANSLATIONS = {
    # A
    'acetyl-5-methyl-2,3-dihydropyran-2,4-dion, 2-': '2-acetil-5-metil-2,3-dihidropirano-2,4-diona',
    'alanin': 'alanina',
    'alaune': 'alumbres',
    'ammoniumalaun': 'alumbre de amonio',
    'ammoniumglycolat': 'glicolato de amonio',
    'ammonsalpeter': 'nitrato de amonio',
    'amylmercaptan': 'amilmercaptano',
    'ananassaft': 'zumo de piña',
    'anis': 'anís',
    'anon': 'ciclohexanona',
    'apfelsinensaft': 'zumo de naranja',
    
    # B
    'baldriantropfen': 'gotas de valeriana',
    'benzen': 'benceno',
    'benzylcarbinol': 'alcohol feniletílico',
    'bis(2-ethylhexyl)-adipat': 'adipato de bis(2-etilhexilo)',
    'bis(2-ethylhexyl)-phthalat': 'ftalato de bis(2-etilhexilo)',
    'borax': 'bórax',
    'butanol': 'butanol',
    'buten': 'buteno',
    'butenal, trans-2-': 'trans-2-butenal',
    'butylcarbinol': 'alcohol amílico',
    'butylcellosolve': 'éter monobutílico del etilenglicol',
    'butylglycol': 'butilglicol',
    
    # C
    'calciumcarbid': 'carburo de calcio',
    'calciumhydrat': 'hidróxido de calcio',
    'campher': 'alcanfor',
    'camphogen': 'canfógeno',
    'carbazol': 'carbazol',
    'carbinol': 'metanol',
    'carbolineum': 'carbolineum',
    'cellosolve': 'cellosolve',
    'chinin': 'quinina',
    'clophen a60': 'Clophen A60',
    'cumen': 'cumeno',
    'curry': 'curry',
    'cyankali': 'cianuro de potasio',
    'cyclanon': 'ciclanona',
    'cyclohexanol': 'ciclohexanol',
    'cymol, p-': 'p-cimeno',
    
    # D
    'dampf': 'vapor',
    'densodrin w': 'Densodrin W',
    'desmodur 44': 'Desmodur 44',
    'dextrin': 'dextrina',
    'dextrose': 'dextrosa',
    'diazan': 'hidrazina',
    'dibenzylsebacat': 'sebacato de dibencilo',
    'dibutylsebacat': 'sebacato de dibutilo',
    'dicyclohexylphthalat': 'ftalato de diciclohexilo',
    'diethylmalonat': 'malonato de dietilo',
    'diethylsebacat': 'sebacato de dietilo',
    'diethylsuccinat': 'succinato de dietilo',
    'diglycol': 'dietilenglicol',
    'dihexylphthalat': 'ftalato de dihexilo',
    'diisooctylphthalat (dop)': 'ftalato de diisooctilo (DOP)',
    'dimethylcarbinol': 'isopropanol',
    'dimethylphthalat (dmp)': 'ftalato de dimetilo (DMP)',
    'dinonylphthalat (dnp)': 'ftalato de dinonilo (DNP)',
    'dioctyladipat': 'adipato de dioctilo',
    'dioctylsebacat': 'sebacato de dioctilo',
    'dipenten': 'dipenteno',
    'dipentylphthalat': 'ftalato de dipentilo',
    'diphenylenimin': 'carbazol',
    'diphyl': 'Diphyl',
    'dolcymen': 'Dolcymen',
    
    # E
    'eau de labarraque': 'agua de Labarraque',
    'elaol': 'aceite de oliva',
    'emulgatoren': 'emulsionantes',
    'ephetin': 'efedrina',
    'erdgas': 'gas natural',
    'ethen': 'etileno',
    'ethin': 'acetileno',
    'ethinylcarbiol': 'alcohol propargílico',
    'ethoxyacetanilid, 4-': '4-etoxiacetanilida',
    'ethyl-cellosolve': 'éter monoetílico del etilenglicol',
    'ethylbenzen': 'etilbenceno',
    'ethylbutyrat': 'butirato de etilo',
    'ethylcarbinol': 'propanol',
    'ethylglycol': 'etilglicol',
    'ethylmalonat': 'malonato de etilo',
    'ethylmercaptan': 'etanotiol',
    'ethylsilicat': 'silicato de etilo',
    
    # F
    'fischtran': 'aceite de pescado',
    'flugmotorenkraftstoffe (jp)': 'combustible de aviación (JP)',
    'fluid 101, 100°c': 'Fluid 101, 100°C',
    'fluor': 'flúor',
    'fluorammonium': 'fluoruro de amonio',
    'formalin': 'formalina',
    'formin': 'hexametilentetramina',
    'fotoentwickler': 'revelador fotográfico',
    'fotofixierbäder': 'baño fijador fotográfico',
    'freon 11': 'Freón 11',
    'freon 112': 'Freón 112',
    'freon 113': 'Freón 113',
    'freon 114': 'Freón 114',
    'freon 114 b2': 'Freón 114 B2',
    'freon 115': 'Freón 115',
    'freon 12': 'Freón 12',
    'freon 13': 'Freón 13',
    'freon 13 b1': 'Freón 13 B1',
    'freon 14': 'Freón 14',
    'freon 142b': 'Freón 142b',
    'freon 152a': 'Freón 152a',
    'freon 21': 'Freón 21',
    'freon 218': 'Freón 218',
    'freon 22': 'Freón 22',
    'freon 31': 'Freón 31',
    'freon 32': 'Freón 32',
    'freon c 318': 'Freón C 318',
    'freon c316': 'Freón C316',
    'frigen 12': 'Frigen 12',
    'frigen 21': 'Frigen 21',
    'frigen 22': 'Frigen 22',
    'frostschutzmittel (kfz)': 'anticongelante (automóvil)',
    'fruchtsäfte': 'zumos de frutas',
    'fructose': 'fructosa',
    'furan': 'furano',
    'furanal': 'furfural',
    'furancarbinol, 2-': 'alcohol furfurílico',
    'furfural': 'furfural',
    'furfuran': 'furano',
    'furfurol': 'furfural',
    
    # G
    'gallotannin': 'galotanino',
    'gasoline': 'gasolina',
    'genantin': 'Genantin',
    'gerbeextrakte, pflanzlich': 'extractos curtientes vegetales',
    'gerbextrakte': 'extractos curtientes',
    'glucose': 'glucosa',
    'glucosesirup': 'jarabe de glucosa',
    'glycin': 'glicina',
    'glycol': 'glicol',
    'glykokoll': 'glicina',
    'glysantin': 'Glysantin',
    'grubengas': 'grisú',
    'gärungsmaische': 'mosto de fermentación',
    
    # H
    'hefe': 'levadura',
    'helium': 'helio',
    'hexen, 1-': 'hex-1-eno',
    'hexylen': 'hexileno',
    'hydrargillit': 'hidrargilita',
    'hydroxymethylfuran, 2-': '2-hidroximetilfurano',
    'hydroxymethylfurfural, 5-': '5-hidroximetilfurfural',
    
    # I
    'ingwer': 'jengibre',
    'isobutanol': 'isobutanol',
    'isopropanol': 'isopropanol',
    'isopropylbenzen': 'cumeno',
    
    # K
    'kalialaune': 'alumbre de potasio',
    'kalisalpeter': 'nitrato de potasio',
    'kardamom': 'cardamomo',
    'kraftstoff, normal': 'gasolina normal',
    'kraftstoff, super': 'gasolina súper',
    'kreosot': 'creosota',
    'kümmel': 'comino',
    
    # L
    'lachgas': 'óxido nitroso',
    'lactame': 'lactamas',
    'lactobiose': 'lactosa',
    'lactose': 'lactosa',
    'lanolin': 'lanolina',
    'latex': 'látex',
    'lebertran': 'aceite de hígado de bacalao',
    'ligroin': 'ligroína',
    'limonen, dl-': 'DL-limoneno',
    'lindan': 'lindano',
    'lorbeer': 'laurel',
    'lysol': 'lisol',
    
    # M
    'magnesit': 'magnesita',
    'malonester': 'éster malónico',
    'margarine': 'margarina',
    'melasse': 'melaza',
    'melassewürze': 'mosto de melaza',
    'menthadien-1,8, p-': 'p-menta-1,8-dieno',
    'menthol': 'mentol',
    'methyl-2-methylpropionat': '2-metilpropionato de metilo',
    'methylcellosolve': 'éter monometílico del etilenglicol',
    'methylglycol': 'metilglicol',
    'methyloxiran': 'óxido de propileno',
    'methylpent-4-en-2-on, 5-': '5-metilhex-4-en-2-ona',
    'methylpropenoat': 'metacrilato de metilo',
    'monopentylphthalat': 'ftalato de monopentilo',
    'mowilith d': 'Mowilith D',
    'muskat': 'nuez moscada',
    
    # N
    'naphtha': 'nafta',
    'naphthen': 'nafteno',
    'natronsalpeter': 'nitrato de sodio',
    'nelken': 'clavo',
    'netzmittel': 'agentes humectantes',
    'niacin': 'niacina',
    'nicotin': 'nicotina',
    'nitroglycol': 'nitroglicol',
    'nitrose gase': 'gases nitrosos',
    'nitroverdünnung': 'diluyente nitro',
    
    # O
    'obstpulp': 'pulpa de frutas',
    'octal': 'Octal',
    'olein': 'oleína',
    'oleum': 'óleum',
    'oleumdämpfe': 'vapores de óleum',
    'oxiran': 'óxido de etileno',
    'oxolan': 'tetrahidrofurano',
    'oxymethylfurfurol, 5-': '5-hidroximetilfurfural',
    
    # P
    'paraform': 'paraformaldehído',
    'parfüms': 'perfumes',
    'pectin': 'pectina',
    'perhydrol': 'peróxido de hidrógeno',
    'petrolatum': 'vaselina',
    'phenacetin': 'fenacetina',
    'phenyl-2-propenal, trans-3-': 'trans-3-fenil-2-propenal',
    'phenylcarbinol': 'alcohol bencílico',
    'phenylsulfonat': 'fenilsulfonato',
    'phosgen': 'fosgeno',
    'phosphin': 'fosfina',
    'piment': 'pimiento',
    'polyglycol': 'poliglicol',
    'polyran m25 n': 'Polyran M25 N',
    'polyran m400': 'Polyran M400',
    'polysiloxan': 'polisiloxano',
    'polysolvan o': 'Polysolvan O',
    'prontosil': 'Prontosil',
    'propanol': 'propanol',
    'propen': 'propeno',
    'propen-1-ol, 2-': 'prop-2-en-1-ol',
    'propin-1-ol, 2-': 'prop-2-in-1-ol',
    'pydraul c (312, 540)': 'Pydraul C (312, 540)',
    'pydraul e (29, 30, 50, 65, 90, 11)': 'Pydraul E (29, 30, 50, 65, 90, 11)',
    'pyrogallol': 'pirogalol',
    'pyrrol': 'pirrol',
    
    # R
    'ramasit': 'Ramasit',
    'rindertalg': 'sebo de vaca',
    'röstgase': 'gases de tostación',
    
    # S
    'sagrotan': 'Sagrotan',
    'salmiak': 'sal amoníaco',
    'salmiakgeist': 'amoníaco',
    'sattdampfkondensat': 'condensado de vapor saturado',
    'skydrol 500 (b4)': 'Skydrol 500 (B4)',
    'skydrol 7000': 'Skydrol 7000',
    'soda': 'sosa',
    'spirituosen': 'licores',
    'spiritus': 'alcohol de quemar',
    'strychnin': 'estricnina',
    
    # T
    'talg': 'sebo',
    'tannin': 'tanino',
    'tenside': 'tensioactivos',
    'terpentinersatz': 'sustituto de trementina',
    'testkraftstoff a (iso-fluid a)': 'combustible de prueba A (ISO-Fluid A)',
    'testkraftstoff b (iso-fluid b)': 'combustible de prueba B (ISO-Fluid B)',
    'testkraftstoff c (iso-fluid c)': 'combustible de prueba C (ISO-Fluid C)',
    'testkraftstoff d (iso-fluid d)': 'combustible de prueba D (ISO-Fluid D)',
    'thiacyclopentadien': 'tiofeno',
    'thiofuran': 'tiofeno',
    'thiophen': 'tiofeno',
    'thymol': 'timol',
    'toluen': 'tolueno',
    'traganth': 'tragacanto',
    'triacetin': 'triacetina',
    'triglycol': 'trietilenglicol',
    'tripen': 'tripeno',
    
    # U
    'urotropin': 'hexametilentetramina',
    
    # V
    'vaseline': 'vaselina',
    'vinylcarbinol': 'alcohol alílico',
    
    # W
    'walrat': 'esperma de ballena',
    'weichmacher': 'plastificantes',
    'whiskey': 'whisky',
    'white spirit': 'aguarrás',
    
    # X
    'xenon': 'xenón',
    'xylen': 'xileno',
    
    # Z
    'zimt': 'canela',
    'zitronensaft': 'zumo de limón',
    
    # Ä
    'ätzbaryt': 'barita cáustica',
    'ätzkali': 'potasa cáustica',
    'ätznatron': 'sosa cáustica',
}

def translate_chemical_name(german_name):
    """Translate a German chemical name to Spanish."""
    result = german_name.lower()
    
    # Try exact match in additional translations first (manually curated)
    if result in ADDITIONAL_TRANSLATIONS:
        return ADDITIONAL_TRANSLATIONS[result].title()
    
    # Try exact match in term translations
    if result in TERM_TRANSLATIONS:
        return TERM_TRANSLATIONS[result].title()
    
    # Apply translations from longest to shortest (more specific first)
    sorted_terms = sorted(TERM_TRANSLATIONS.keys(), key=len, reverse=True)
    
    for de_term in sorted_terms:
        if de_term in result:
            result = result.replace(de_term, TERM_TRANSLATIONS[de_term])
    
    # Capitalize appropriately
    words = result.split()
    capitalized = []
    for i, word in enumerate(words):
        if i == 0:
            capitalized.append(word.capitalize())
        elif word in ['de', 'del', 'y', 'o', 'a', 'en', 'que']:
            capitalized.append(word)
        elif word.startswith(('di', 'tri', 'tetra', 'penta', 'hexa', 'mono', 'poli', 'iso', 'n-', 'o-', 'm-', 'p-')):
            capitalized.append(word)
        else:
            capitalized.append(word)
    
    return ' '.join(capitalized)


def main():
    # Load chemical data
    with open('data/chemicals_burkle_full.json', 'r', encoding='utf-8') as f:
        chemicals = json.load(f)
    
    # Get unique names and translate
    names = sorted(set(c['name'] for c in chemicals))
    
    translations = {}
    for name in names:
        translated = translate_chemical_name(name)
        # Include translation if it exists
        if translated:
            translations[name.lower()] = translated
    
    print(f"Translated {len(translations)} of {len(names)} chemical names")
    
    # Output as JavaScript object
    js_output = "// German → Spanish chemical name translations\n"
    js_output += "// Auto-generated - " + str(len(translations)) + " translations\n"
    js_output += "const chemicalTranslations = {\n"
    
    for de, es in sorted(translations.items()):
        # Escape quotes
        de_escaped = de.replace("'", "\\'")
        es_escaped = es.replace("'", "\\'")
        js_output += f"    '{de_escaped}': '{es_escaped}',\n"
    
    js_output += "};\n"
    
    # Save to file
    with open('js/chemical_translations_es.js', 'w', encoding='utf-8') as f:
        f.write(js_output)
    
    print(f"Saved translations to js/chemical_translations_es.js")
    
    # Print some samples
    print("\nSample translations:")
    samples = list(translations.items())[:20]
    for de, es in samples:
        print(f"  {de} → {es}")


if __name__ == '__main__':
    main()
