#!/usr/bin/env python3
"""
Translate all German chemical names to English for chemicalresistance.org
"""
import json
import re

# Comprehensive German → English chemical term translations

TERM_TRANSLATIONS = {
    # Specific compounds first
    'acetanhydrid': 'acetic anhydride',
    'acetylchlorid': 'acetyl chloride',
    'benzoylchlorid': 'benzoyl chloride',
    'benzylchlorid': 'benzyl chloride',
    'amylchlorid': 'amyl chloride',
    'carbonylchlorid': 'phosgene',
    'thionylchlorid': 'thionyl chloride',
    'sulfurylchlorid': 'sulfuryl chloride',
    'acetylentetrachlorid': 'tetrachloroethane',
    'acetylentetrabromid': 'tetrabromoethane',
    'antimonpentachlorid': 'antimony pentachloride',
    'antimontrichlorid': 'antimony trichloride',
    'antimon-(iii)-chlorid': 'antimony(III) chloride',
    'antimon-(v)-chlorid': 'antimony(V) chloride',
    'anilinhydrochlorid': 'aniline hydrochloride',
    'aniliniumchlorid': 'anilinium chloride',
    'arsenanhydrid': 'arsenic trioxide',
    'arsensäureanhydrid': 'arsenic pentoxide',
    'benzolhexachlorid': 'hexachlorocyclohexane',
    'bismutchlorid': 'bismuth chloride',
    'buttersäureethylester': 'ethyl butyrate',
    'buttersäuremethylester': 'methyl butyrate',
    'bernsteinsäurediethylester': 'diethyl succinate',
    'phthalsäurediethylester': 'diethyl phthalate',
    'phthalsäuredibutylester': 'dibutyl phthalate',
    'phthalsäuredioctylester': 'dioctyl phthalate',
    'sebacinsäure': 'sebacic acid',
    
    # Esters - specific compounds
    'acrylsäurebutylester': 'butyl acrylate',
    'acrylsäureethylester': 'ethyl acrylate',
    'acrylsäuremethylester': 'methyl acrylate',
    'acrylsäurenitril': 'acrylonitrile',
    'ameisensäureamid': 'formamide',
    'ameisensäureethylester': 'ethyl formate',
    'ameisensäuremethylester': 'methyl formate',
    'essigsäureanhydrid': 'acetic anhydride',
    'essigsäureamid': 'acetamide',
    'essigsäurebutylester': 'butyl acetate',
    'essigsäureethylester': 'ethyl acetate',
    'essigsäuremethylester': 'methyl acetate',
    'essigsäureamylester': 'amyl acetate',
    'essigsäurepropylester': 'propyl acetate',
    'essigsäurevinylester': 'vinyl acetate',
    'essigsäureallylester': 'allyl acetate',
    'essigsäurebenzylester': 'benzyl acetate',
    'essigsäure-n-amylester': 'n-amyl acetate',
    'essigsäure silbersalz': 'silver acetate',
    'chloressigsäureethylester': 'ethyl chloroacetate',
    'chloressigsäuremethylester': 'methyl chloroacetate',
    'dichloressigsäuremethylester': 'methyl dichloroacetate',
    'cyanessigsäureethylester': 'ethyl cyanoacetate',
    'benzoesäurealdehyd': 'benzaldehyde',
    'benzoesäurechlorid': 'benzoyl chloride',
    'benzoesäureethylester': 'ethyl benzoate',
    'benzoesäuremethylester': 'methyl benzoate',
    'benzoesäurebenzylester': 'benzyl benzoate',
    'benzoesäure natriumsalz': 'sodium benzoate',
    'adipinsäuredioctylester': 'dioctyl adipate',
    
    # Acids
    'schwefelsäure': 'sulfuric acid',
    'salzsäure': 'hydrochloric acid',
    'salpetersäure': 'nitric acid',
    'phosphorsäure': 'phosphoric acid',
    'essigsäure': 'acetic acid',
    'ameisensäure': 'formic acid',
    'zitronensäure': 'citric acid',
    'milchsäure': 'lactic acid',
    'oxalsäure': 'oxalic acid',
    'chromsäure': 'chromic acid',
    'flusssäure': 'hydrofluoric acid',
    'fluorwasserstoffsäure': 'hydrofluoric acid',
    'kohlensäure': 'carbonic acid',
    'borsäure': 'boric acid',
    'benzoesäure': 'benzoic acid',
    'weinsäure': 'tartaric acid',
    'bernsteinsäure': 'succinic acid',
    'maleinsäure': 'maleic acid',
    'fumarsäure': 'fumaric acid',
    'adipinsäure': 'adipic acid',
    'stearinsäure': 'stearic acid',
    'ölsäure': 'oleic acid',
    'palmitinsäure': 'palmitic acid',
    'laurinsäure': 'lauric acid',
    'caprylsäure': 'caprylic acid',
    'capronsäure': 'caproic acid',
    'buttersäure': 'butyric acid',
    'propionsäure': 'propionic acid',
    'acrylsäure': 'acrylic acid',
    'methacrylsäure': 'methacrylic acid',
    'glykolsäure': 'glycolic acid',
    'glycolsäure': 'glycolic acid',
    'brenztraubensäure': 'pyruvic acid',
    'glutaminsäure': 'glutamic acid',
    'asparaginsäure': 'aspartic acid',
    'phthalsäure': 'phthalic acid',
    'isophthalsäure': 'isophthalic acid',
    'terephthalsäure': 'terephthalic acid',
    'toluolsulfonsäure': 'toluenesulfonic acid',
    'benzolsulfonsäure': 'benzenesulfonic acid',
    'sulfanilsäure': 'sulfanilic acid',
    'pikrinsäure': 'picric acid',
    'gallussäure': 'gallic acid',
    'gerbsäure': 'tannic acid',
    'harnsäure': 'uric acid',
    'hippursäure': 'hippuric acid',
    'ascorbinsäure': 'ascorbic acid',
    'nikotinsäure': 'nicotinic acid',
    'folsäure': 'folic acid',
    'fettsäure': 'fatty acid',
    'fettsäuren': 'fatty acids',
    'aminoessigsäure': 'glycine',
    'aminoethansäure': 'glycine',
    'aminopropionsäure': 'alanine',
    'aminosäure': 'amino acid',
    'aminosäuren': 'amino acids',
    'carbonsäure': 'carboxylic acid',
    'dicarbonsäure': 'dicarboxylic acid',
    'tricarbonsäure': 'tricarboxylic acid',
    'sulfonsäure': 'sulfonic acid',
    'phosphonsäure': 'phosphonic acid',
    'arsensäure': 'arsenic acid',
    'arsenigsäure': 'arsenious acid',
    'antimonsäure': 'antimonic acid',
    'kieselsäure': 'silicic acid',
    'kieselflusssäure': 'fluorosilicic acid',
    'hexafluorokieselsäure': 'hexafluorosilicic acid',
    'perchlorsäure': 'perchloric acid',
    'chlorsäure': 'chloric acid',
    'hypochlorigsäure': 'hypochlorous acid',
    'chlorigsäure': 'chlorous acid',
    'bromsäure': 'bromic acid',
    'bromwasserstoffsäure': 'hydrobromic acid',
    'jodwasserstoffsäure': 'hydroiodic acid',
    'jodsäure': 'iodic acid',
    'periodsäure': 'periodic acid',
    'blausäure': 'hydrocyanic acid',
    'cyanwasserstoffsäure': 'hydrocyanic acid',
    'rhodanwasserstoffsäure': 'thiocyanic acid',
    'thiocyansäure': 'thiocyanic acid',
    'schwefelwasserstoffsäure': 'hydrosulfuric acid',
    'schwefligesäure': 'sulfurous acid',
    'unterschwefligesäure': 'thiosulfuric acid',
    'thioschwefelsäure': 'thiosulfuric acid',
    'selensäure': 'selenic acid',
    'tellursäure': 'telluric acid',
    'molybdänsäure': 'molybdic acid',
    'wolframsäure': 'tungstic acid',
    'vanadinsäure': 'vanadic acid',
    'permangansäure': 'permanganic acid',
    'übermangansäure': 'permanganic acid',
    'mangansäure': 'manganic acid',
    'salicylsäure': 'salicylic acid',
    'acetylsalicylsäure': 'acetylsalicylic acid',
    'zimtsäure': 'cinnamic acid',
    'sorbinsäure': 'sorbic acid',
    'peressigsäure': 'peracetic acid',
    'crotonsäure': 'crotonic acid',
    'linolsäure': 'linoleic acid',
    'linolensäure': 'linolenic acid',
    'chloressigsäure': 'chloroacetic acid',
    'dichloressigsäure': 'dichloroacetic acid',
    'trichloressigsäure': 'trichloroacetic acid',
    'akkusäure': 'battery acid',
    'säure': 'acid',
    
    # Bases/Hydroxides
    'natronlauge': 'caustic soda',
    'kalilauge': 'caustic potash',
    'natriumhydroxid': 'sodium hydroxide',
    'kaliumhydroxid': 'potassium hydroxide',
    'calciumhydroxid': 'calcium hydroxide',
    'magnesiumhydroxid': 'magnesium hydroxide',
    'bariumhydroxid': 'barium hydroxide',
    'strontiumhydroxid': 'strontium hydroxide',
    'lithiumhydroxid': 'lithium hydroxide',
    'ammoniumhydroxid': 'ammonium hydroxide',
    'aluminiumhydroxid': 'aluminum hydroxide',
    'eisenhydroxid': 'iron hydroxide',
    'kupferhydroxid': 'copper hydroxide',
    'zinkhydroxid': 'zinc hydroxide',
    'hydroxid': 'hydroxide',
    'lauge': 'lye',
    
    # Salts - Chlorides
    'natriumchlorid': 'sodium chloride',
    'kaliumchlorid': 'potassium chloride',
    'calciumchlorid': 'calcium chloride',
    'magnesiumchlorid': 'magnesium chloride',
    'bariumchlorid': 'barium chloride',
    'strontiumchlorid': 'strontium chloride',
    'lithiumchlorid': 'lithium chloride',
    'ammoniumchlorid': 'ammonium chloride',
    'aluminiumchlorid': 'aluminum chloride',
    'eisenchlorid': 'iron chloride',
    'eisen(iii)chlorid': 'iron(III) chloride',
    'eisen(ii)chlorid': 'iron(II) chloride',
    'kupferchlorid': 'copper chloride',
    'zinkchlorid': 'zinc chloride',
    'zinnchlorid': 'tin chloride',
    'bleichlorid': 'lead chloride',
    'quecksilberchlorid': 'mercury chloride',
    'silberchlorid': 'silver chloride',
    'goldchlorid': 'gold chloride',
    'platinchlorid': 'platinum chloride',
    'nickelchlorid': 'nickel chloride',
    'cobaltchlorid': 'cobalt chloride',
    'manganchlorid': 'manganese chloride',
    'chromchlorid': 'chromium chloride',
    'titantetrachlorid': 'titanium tetrachloride',
    'siliciumtetrachlorid': 'silicon tetrachloride',
    'kohlenstofftetrachlorid': 'carbon tetrachloride',
    'tetrachlorkohlenstoff': 'carbon tetrachloride',
    'chlorid': 'chloride',
    
    # Salts - Sulfates
    'natriumsulfat': 'sodium sulfate',
    'kaliumsulfat': 'potassium sulfate',
    'calciumsulfat': 'calcium sulfate',
    'magnesiumsulfat': 'magnesium sulfate',
    'bariumsulfat': 'barium sulfate',
    'ammoniumsulfat': 'ammonium sulfate',
    'aluminiumsulfat': 'aluminum sulfate',
    'eisensulfat': 'iron sulfate',
    'kupfersulfat': 'copper sulfate',
    'zinksulfat': 'zinc sulfate',
    'nickelsulfat': 'nickel sulfate',
    'cobaltsulfat': 'cobalt sulfate',
    'mangansulfat': 'manganese sulfate',
    'chromsulfat': 'chromium sulfate',
    'sulfat': 'sulfate',
    
    # Salts - Nitrates
    'natriumnitrat': 'sodium nitrate',
    'kaliumnitrat': 'potassium nitrate',
    'calciumnitrat': 'calcium nitrate',
    'magnesiumnitrat': 'magnesium nitrate',
    'bariumnitrat': 'barium nitrate',
    'ammoniumnitrat': 'ammonium nitrate',
    'aluminiumnitrat': 'aluminum nitrate',
    'eisennitrat': 'iron nitrate',
    'kupfernitrat': 'copper nitrate',
    'zinknitrat': 'zinc nitrate',
    'silbernitrat': 'silver nitrate',
    'bleinitrat': 'lead nitrate',
    'nitrat': 'nitrate',
    
    # Salts - Carbonates
    'natriumcarbonat': 'sodium carbonate',
    'kaliumcarbonat': 'potassium carbonate',
    'calciumcarbonat': 'calcium carbonate',
    'magnesiumcarbonat': 'magnesium carbonate',
    'bariumcarbonat': 'barium carbonate',
    'ammoniumcarbonat': 'ammonium carbonate',
    'lithiumcarbonat': 'lithium carbonate',
    'natriumhydrogencarbonat': 'sodium hydrogen carbonate',
    'kaliumhydrogencarbonat': 'potassium hydrogen carbonate',
    'ammoniumhydrogencarbonat': 'ammonium hydrogen carbonate',
    'natriumbicarbonat': 'sodium bicarbonate',
    'kaliumbicarbonat': 'potassium bicarbonate',
    'ammoniumbicarbonat': 'ammonium bicarbonate',
    'carbonat': 'carbonate',
    'bicarbonat': 'bicarbonate',
    'hydrogencarbonat': 'hydrogen carbonate',
    
    # Salts - Phosphates
    'natriumphosphat': 'sodium phosphate',
    'kaliumphosphat': 'potassium phosphate',
    'calciumphosphat': 'calcium phosphate',
    'ammoniumphosphat': 'ammonium phosphate',
    'phosphat': 'phosphate',
    'hydrogenphosphat': 'hydrogen phosphate',
    'dihydrogenphosphat': 'dihydrogen phosphate',
    'polyphosphat': 'polyphosphate',
    'metaphosphat': 'metaphosphate',
    'pyrophosphat': 'pyrophosphate',
    
    # Salts - Others
    'natriumsulfit': 'sodium sulfite',
    'natriumthiosulfat': 'sodium thiosulfate',
    'natriumhypochlorit': 'sodium hypochlorite',
    'calciumhypochlorit': 'calcium hypochlorite',
    'natriumchlorat': 'sodium chlorate',
    'kaliumchlorat': 'potassium chlorate',
    'natriumperchlorat': 'sodium perchlorate',
    'kaliumperchlorat': 'potassium perchlorate',
    'natriumfluorid': 'sodium fluoride',
    'kaliumfluorid': 'potassium fluoride',
    'calciumfluorid': 'calcium fluoride',
    'ammoniumfluorid': 'ammonium fluoride',
    'ammoniumbifluorid': 'ammonium bifluoride',
    'natriumcyanid': 'sodium cyanide',
    'kaliumcyanid': 'potassium cyanide',
    'natriumsulfid': 'sodium sulfide',
    'kaliumsulfid': 'potassium sulfide',
    'ammoniumsulfid': 'ammonium sulfide',
    'natriumacetat': 'sodium acetate',
    'kaliumacetat': 'potassium acetate',
    'calciumacetat': 'calcium acetate',
    'ammoniumacetat': 'ammonium acetate',
    'bleiacetat': 'lead acetate',
    'kupferacetat': 'copper acetate',
    'zinkacetat': 'zinc acetate',
    'natriumformiat': 'sodium formate',
    'kaliumformiat': 'potassium formate',
    'natriumoxalat': 'sodium oxalate',
    'kaliumoxalat': 'potassium oxalate',
    'ammoniumoxalat': 'ammonium oxalate',
    'calciumoxalat': 'calcium oxalate',
    'natriumcitrat': 'sodium citrate',
    'kaliumcitrat': 'potassium citrate',
    'natriumtartrat': 'sodium tartrate',
    'kaliumtartrat': 'potassium tartrate',
    'natriumbenzoat': 'sodium benzoate',
    'kaliumbenzoat': 'potassium benzoate',
    'natriumsalicylat': 'sodium salicylate',
    'natriumlactat': 'sodium lactate',
    'calciumlactat': 'calcium lactate',
    'natriumgluconat': 'sodium gluconate',
    'calciumgluconat': 'calcium gluconate',
    'natriumstearat': 'sodium stearate',
    'calciumstearat': 'calcium stearate',
    'zinkstearat': 'zinc stearate',
    'magnesiumstearat': 'magnesium stearate',
    'sulfit': 'sulfite',
    'thiosulfat': 'thiosulfate',
    'hypochlorit': 'hypochlorite',
    'chlorat': 'chlorate',
    'perchlorat': 'perchlorate',
    'bromat': 'bromate',
    'bromid': 'bromide',
    'jodat': 'iodate',
    'jodid': 'iodide',
    'fluorid': 'fluoride',
    'bifluorid': 'bifluoride',
    'cyanid': 'cyanide',
    'sulfid': 'sulfide',
    'hydrosulfid': 'hydrosulfide',
    'acetat': 'acetate',
    'formiat': 'formate',
    'oxalat': 'oxalate',
    'citrat': 'citrate',
    'tartrat': 'tartrate',
    'benzoat': 'benzoate',
    'salicylat': 'salicylate',
    'lactat': 'lactate',
    'gluconat': 'gluconate',
    'stearat': 'stearate',
    'oleat': 'oleate',
    'laurat': 'laurate',
    'palmitat': 'palmitate',
    'silikat': 'silicate',
    'borat': 'borate',
    'chromat': 'chromate',
    'dichromat': 'dichromate',
    'permanganat': 'permanganate',
    'molybdat': 'molybdate',
    'wolframat': 'tungstate',
    'vanadat': 'vanadate',
    'arsenat': 'arsenate',
    'arsenit': 'arsenite',
    'rhodanid': 'thiocyanate',
    'thiocyanat': 'thiocyanate',
    'sulfocyanid': 'thiocyanate',
    'ferrocyanid': 'ferrocyanide',
    'ferricyanid': 'ferricyanide',
    'nitrit': 'nitrite',
    'nitrid': 'nitride',
    'hydrid': 'hydride',
    'amid': 'amide',
    'azid': 'azide',
    'peroxid': 'peroxide',
    'superoxid': 'superoxide',
    'oxid': 'oxide',
    
    # Organic compounds - Alcohols
    'methanol': 'methanol',
    'ethanol': 'ethanol',
    'äthanol': 'ethanol',
    'propanol': 'propanol',
    'isopropanol': 'isopropanol',
    'butanol': 'butanol',
    'isobutanol': 'isobutanol',
    'pentanol': 'pentanol',
    'amylalkohol': 'amyl alcohol',
    'hexanol': 'hexanol',
    'heptanol': 'heptanol',
    'octanol': 'octanol',
    'decanol': 'decanol',
    'dodecanol': 'dodecanol',
    'benzylalkohol': 'benzyl alcohol',
    'cyclohexanol': 'cyclohexanol',
    'ethylenglykol': 'ethylene glycol',
    'äthylenglykol': 'ethylene glycol',
    'propylenglykol': 'propylene glycol',
    'diethylenglykol': 'diethylene glycol',
    'triethylenglykol': 'triethylene glycol',
    'polyethylenglykol': 'polyethylene glycol',
    'glycerin': 'glycerin',
    'glyzerin': 'glycerin',
    'glycerol': 'glycerol',
    'allylalkohol': 'allyl alcohol',
    'alkohol': 'alcohol',
    
    # Organic compounds - Aldehydes & Ketones
    'formaldehyd': 'formaldehyde',
    'acetaldehyd': 'acetaldehyde',
    'propionaldehyd': 'propionaldehyde',
    'butyraldehyd': 'butyraldehyde',
    'benzaldehyd': 'benzaldehyde',
    'furfural': 'furfural',
    'acrolein': 'acrolein',
    'crotonaldehyd': 'crotonaldehyde',
    'glutaraldehyd': 'glutaraldehyde',
    'aldehyd': 'aldehyde',
    'aceton': 'acetone',
    'methylethylketon': 'methyl ethyl ketone',
    'methylisobutylketon': 'methyl isobutyl ketone',
    'cyclohexanon': 'cyclohexanone',
    'acetophenon': 'acetophenone',
    'keton': 'ketone',
    
    # Organic compounds - Ethers
    'diethylether': 'diethyl ether',
    'diäthylether': 'diethyl ether',
    'äther': 'ether',
    'ether': 'ether',
    'tetrahydrofuran': 'tetrahydrofuran',
    'dioxan': 'dioxane',
    'anisol': 'anisole',
    
    # Organic compounds - Esters
    'methylacetat': 'methyl acetate',
    'ethylacetat': 'ethyl acetate',
    'äthylacetat': 'ethyl acetate',
    'butylacetat': 'butyl acetate',
    'amylacetat': 'amyl acetate',
    'isoamylacetat': 'isoamyl acetate',
    'benzylacetat': 'benzyl acetate',
    'methylformiat': 'methyl formate',
    'ethylformiat': 'ethyl formate',
    'methylbenzoat': 'methyl benzoate',
    'ethylbenzoat': 'ethyl benzoate',
    'methylsalicylat': 'methyl salicylate',
    'methylmethacrylat': 'methyl methacrylate',
    'ethylacrylat': 'ethyl acrylate',
    'butylacrylat': 'butyl acrylate',
    'dioctylphthalat': 'dioctyl phthalate',
    'dibutylphthalat': 'dibutyl phthalate',
    'ester': 'ester',
    
    # Organic compounds - Amines
    'methylamin': 'methylamine',
    'dimethylamin': 'dimethylamine',
    'trimethylamin': 'trimethylamine',
    'ethylamin': 'ethylamine',
    'äthylamin': 'ethylamine',
    'diethylamin': 'diethylamine',
    'triethylamin': 'triethylamine',
    'propylamin': 'propylamine',
    'isopropylamin': 'isopropylamine',
    'butylamin': 'butylamine',
    'cyclohexylamin': 'cyclohexylamine',
    'anilin': 'aniline',
    'toluidin': 'toluidine',
    'benzylamin': 'benzylamine',
    'ethanolamin': 'ethanolamine',
    'äthanolamin': 'ethanolamine',
    'diethanolamin': 'diethanolamine',
    'triethanolamin': 'triethanolamine',
    'ethylendiamin': 'ethylenediamine',
    'äthylendiamin': 'ethylenediamine',
    'morpholin': 'morpholine',
    'piperidin': 'piperidine',
    'pyrrolidin': 'pyrrolidine',
    'pyridin': 'pyridine',
    'hydrazin': 'hydrazine',
    'hydroxylamin': 'hydroxylamine',
    'amin': 'amine',
    
    # Organic compounds - Amides
    'formamid': 'formamide',
    'acetamid': 'acetamide',
    'dimethylformamid': 'dimethylformamide',
    'dimethylacetamid': 'dimethylacetamide',
    'harnstoff': 'urea',
    'thioharnstoff': 'thiourea',
    'caprolactam': 'caprolactam',
    
    # Organic compounds - Nitriles
    'acetonitril': 'acetonitrile',
    'propionitril': 'propionitrile',
    'benzonitril': 'benzonitrile',
    'acrylnitril': 'acrylonitrile',
    'nitril': 'nitrile',
    
    # Aromatic compounds
    'benzol': 'benzene',
    'toluol': 'toluene',
    'xylol': 'xylene',
    'ethylbenzol': 'ethylbenzene',
    'äthylbenzol': 'ethylbenzene',
    'cumol': 'cumene',
    'styrol': 'styrene',
    'naphthalin': 'naphthalene',
    'anthracen': 'anthracene',
    'phenol': 'phenol',
    'kresol': 'cresol',
    'hydrochinon': 'hydroquinone',
    'resorcin': 'resorcinol',
    'chlorbenzol': 'chlorobenzene',
    'dichlorbenzol': 'dichlorobenzene',
    'trichlorbenzol': 'trichlorobenzene',
    'brombenzol': 'bromobenzene',
    'nitrobenzol': 'nitrobenzene',
    'dinitrobenzol': 'dinitrobenzene',
    'trinitrobenzol': 'trinitrobenzene',
    'nitrotoluol': 'nitrotoluene',
    'dinitrotoluol': 'dinitrotoluene',
    'trinitrotoluol': 'trinitrotoluene',
    
    # Aliphatic hydrocarbons
    'methan': 'methane',
    'ethan': 'ethane',
    'äthan': 'ethane',
    'propan': 'propane',
    'butan': 'butane',
    'isobutan': 'isobutane',
    'pentan': 'pentane',
    'isopentan': 'isopentane',
    'hexan': 'hexane',
    'heptan': 'heptane',
    'octan': 'octane',
    'isooctan': 'isooctane',
    'nonan': 'nonane',
    'decan': 'decane',
    'dodecan': 'dodecane',
    'cyclohexan': 'cyclohexane',
    'cyclopentan': 'cyclopentane',
    'methylcyclohexan': 'methylcyclohexane',
    'ethylen': 'ethylene',
    'äthylen': 'ethylene',
    'propylen': 'propylene',
    'butylen': 'butylene',
    'butadien': 'butadiene',
    'isopren': 'isoprene',
    'acetylen': 'acetylene',
    
    # Halogenated compounds
    'chlormethan': 'chloromethane',
    'dichlormethan': 'dichloromethane',
    'trichlormethan': 'trichloromethane',
    'chloroform': 'chloroform',
    'chlorethan': 'chloroethane',
    'dichlorethan': 'dichloroethane',
    'trichlorethan': 'trichloroethane',
    'tetrachlorethan': 'tetrachloroethane',
    'trichlorethylen': 'trichloroethylene',
    'tetrachlorethylen': 'tetrachloroethylene',
    'perchlorethylen': 'perchloroethylene',
    'vinylchlorid': 'vinyl chloride',
    'vinylidenchlorid': 'vinylidene chloride',
    'allylchlorid': 'allyl chloride',
    'epichlorhydrin': 'epichlorohydrin',
    'brommethan': 'bromomethane',
    'bromwasserstoff': 'hydrogen bromide',
    'fluorwasserstoff': 'hydrogen fluoride',
    'chlorwasserstoff': 'hydrogen chloride',
    'fluor': 'fluorine',
    'chlor': 'chlorine',
    'brom': 'bromine',
    'jod': 'iodine',
    
    # Sulfur compounds
    'schwefelwasserstoff': 'hydrogen sulfide',
    'schwefeldioxid': 'sulfur dioxide',
    'schwefeltrioxid': 'sulfur trioxide',
    'schwefelkohlenstoff': 'carbon disulfide',
    'kohlenstoffdisulfid': 'carbon disulfide',
    'dimethylsulfoxid': 'dimethyl sulfoxide',
    'dimethylsulfon': 'dimethyl sulfone',
    'thiophene': 'thiophene',
    'mercaptan': 'mercaptan',
    'thiol': 'thiol',
    'schwefel': 'sulfur',
    
    # Nitrogen compounds
    'stickstoff': 'nitrogen',
    'stickstoffoxid': 'nitrogen oxide',
    'stickstoffdioxid': 'nitrogen dioxide',
    'distickstoffoxid': 'nitrous oxide',
    'distickstofftetroxid': 'dinitrogen tetroxide',
    'stickstoffmonoxid': 'nitrogen monoxide',
    'ammoniak': 'ammonia',
    'ammoniakwasser': 'ammonia water',
    
    # Phosphorus compounds
    'phosphor': 'phosphorus',
    'phosphortrichlorid': 'phosphorus trichloride',
    'phosphorpentachlorid': 'phosphorus pentachloride',
    'phosphoroxychlorid': 'phosphorus oxychloride',
    
    # Metals
    'natrium': 'sodium',
    'kalium': 'potassium',
    'lithium': 'lithium',
    'calcium': 'calcium',
    'magnesium': 'magnesium',
    'barium': 'barium',
    'strontium': 'strontium',
    'aluminium': 'aluminum',
    'eisen': 'iron',
    'kupfer': 'copper',
    'zink': 'zinc',
    'zinn': 'tin',
    'blei': 'lead',
    'quecksilber': 'mercury',
    'silber': 'silver',
    'gold': 'gold',
    'platin': 'platinum',
    'palladium': 'palladium',
    'nickel': 'nickel',
    'cobalt': 'cobalt',
    'chrom': 'chromium',
    'mangan': 'manganese',
    'titan': 'titanium',
    'vanadium': 'vanadium',
    'molybdän': 'molybdenum',
    'wolfram': 'tungsten',
    'cadmium': 'cadmium',
    'antimon': 'antimony',
    'arsen': 'arsenic',
    'wismut': 'bismuth',
    'selen': 'selenium',
    'tellur': 'tellurium',
    
    # Common technical terms
    'wasserstoff': 'hydrogen',
    'sauerstoff': 'oxygen',
    'kohlenstoff': 'carbon',
    'kohlendioxid': 'carbon dioxide',
    'kohlenmonoxid': 'carbon monoxide',
    'wasser': 'water',
    'meerwasser': 'seawater',
    'leitungswasser': 'tap water',
    'destilliertes wasser': 'distilled water',
    'salzwasser': 'salt water',
    'sole': 'brine',
    'kochsalzlösung': 'saline solution',
    'luft': 'air',
    'ozon': 'ozone',
    'wasserstoffperoxid': 'hydrogen peroxide',
    'wasserstoffperoxyd': 'hydrogen peroxide',
    
    # Petroleum products
    'benzin': 'gasoline',
    'diesel': 'diesel',
    'dieselkraftstoff': 'diesel fuel',
    'heizöl': 'fuel oil',
    'kerosin': 'kerosene',
    'petroleum': 'petroleum',
    'erdöl': 'crude oil',
    'rohöl': 'crude oil',
    'mineralöl': 'mineral oil',
    'motoröl': 'motor oil',
    'hydrauliköl': 'hydraulic oil',
    'getriebeöl': 'transmission oil',
    'schmieröl': 'lubricating oil',
    'öl': 'oil',
    'fett': 'grease',
    'schmierfett': 'lubricating grease',
    'paraffin': 'paraffin',
    'paraffinöl': 'paraffin oil',
    'vaseline': 'petroleum jelly',
    'wachs': 'wax',
    'bitumen': 'bitumen',
    'asphalt': 'asphalt',
    'teer': 'tar',
    
    # Food & beverages
    'bier': 'beer',
    'wein': 'wine',
    'rotwein': 'red wine',
    'weisswein': 'white wine',
    'weißwein': 'white wine',
    'essig': 'vinegar',
    'weinessig': 'wine vinegar',
    'milch': 'milk',
    'vollmilch': 'whole milk',
    'sahne': 'cream',
    'butter': 'butter',
    'käse': 'cheese',
    'joghurt': 'yogurt',
    'fruchtsaft': 'fruit juice',
    'orangensaft': 'orange juice',
    'apfelsaft': 'apple juice',
    'limonade': 'lemonade',
    'kaffee': 'coffee',
    'tee': 'tea',
    'kakao': 'cocoa',
    'schokolade': 'chocolate',
    'zucker': 'sugar',
    'glucose': 'glucose',
    'fructose': 'fructose',
    'maltose': 'maltose',
    'lactose': 'lactose',
    'saccharose': 'sucrose',
    'stärke': 'starch',
    'mehl': 'flour',
    'salz': 'salt',
    'kochsalz': 'table salt',
    'honig': 'honey',
    'gelatine': 'gelatin',
    
    # Biological & medical
    'blut': 'blood',
    'serum': 'serum',
    'plasma': 'plasma',
    'urin': 'urine',
    'kot': 'feces',
    'speichel': 'saliva',
    'galle': 'bile',
    'insulin': 'insulin',
    'penicillin': 'penicillin',
    'aspirin': 'aspirin',
    'vitamin': 'vitamin',
    'hormon': 'hormone',
    'enzym': 'enzyme',
    'protein': 'protein',
    
    # Cleaning & household
    'seife': 'soap',
    'waschmittel': 'detergent',
    'spülmittel': 'dish soap',
    'reinigungsmittel': 'cleaning agent',
    'desinfektionsmittel': 'disinfectant',
    'bleichmittel': 'bleach',
    'bleiche': 'bleach',
    
    # Industry
    'tinte': 'ink',
    'lack': 'lacquer',
    'farbe': 'paint',
    'kleber': 'glue',
    'klebstoff': 'adhesive',
    'leim': 'glue',
    'harz': 'resin',
    'kunstharz': 'synthetic resin',
    'epoxidharz': 'epoxy resin',
    'polyesterharz': 'polyester resin',
    'gummi': 'rubber',
    'kautschuk': 'rubber',
    'latex': 'latex',
    'silikon': 'silicone',
    'kunststoff': 'plastic',
    'polymer': 'polymer',
    'zellulose': 'cellulose',
    'glas': 'glass',
    'keramik': 'ceramic',
    'beton': 'concrete',
    'zement': 'cement',
    'gips': 'gypsum',
    'kite': 'lime',
    'branntkalk': 'quickite',
    'löschkalk': 'slaked lime',
    'kalkmilch': 'lime milk',
    'kreide': 'chalk',
    'kohle': 'coal',
    'koks': 'coke',
    'graphit': 'graphite',
    
    # Concentration terms
    'konzentriert': 'concentrated',
    'rein': 'pure',
    'technisch': 'technical',
    'unverdünnt': 'undiluted',
    'verdünnt': 'diluted',
    'gesättigt': 'saturated',
    'wässrig': 'aqueous',
    'wasserfrei': 'anhydrous',
    'flüssig': 'liquid',
    'fest': 'solid',
    'gasförmig': 'gaseous',
    
    # Exhaust gases
    'abgase': 'exhaust gases',
    'rauchgase': 'flue gases',
    'abgas': 'exhaust gas',
    
    # Descriptors
    'alkalisch': 'alkaline',
    'sauer': 'acidic',
    'neutral': 'neutral',
    'basisch': 'basic',
    'ätzend': 'corrosive',
    'giftig': 'toxic',
    'brennbar': 'flammable',
    'explosiv': 'explosive',
    'fluorwasserstoffhaltig': 'containing hydrofluoric acid',
    'kohlendioxidhaltig': 'containing carbon dioxide',
    'nitrosehaltig': 'containing nitrogen oxides',
    'salzsäurehaltig': 'containing hydrochloric acid',
    'schwefeldioxidhaltig': 'containing sulfur dioxide',
    'schwefelsäurehaltig': 'containing sulfuric acid',
    'schwefeltrioxidhaltig': 'containing sulfur trioxide',
    
    # Common word parts
    'lösung': 'solution',
    'lösungsmittel': 'solvent',
    'gemisch': 'mixture',
    'verbindung': 'compound',
    'pulver': 'powder',
    'paste': 'paste',
    'emulsion': 'emulsion',
    'suspension': 'suspension',
    'dispersion': 'dispersion',
}

# Additional specific translations
ADDITIONAL_TRANSLATIONS = {
    'acetyl-5-methyl-2,3-dihydropyran-2,4-dion, 2-': '2-acetyl-5-methyl-2,3-dihydropyran-2,4-dione',
    'alanin': 'alanine',
    'alaune': 'alums',
    'ammoniumalaun': 'ammonium alum',
    'ammoniumglycolat': 'ammonium glycolate',
    'ammonsalpeter': 'ammonium nitrate',
    'amylmercaptan': 'amyl mercaptan',
    'ananassaft': 'pineapple juice',
    'anis': 'anise',
    'anon': 'cyclohexanone',
    'apfelsinensaft': 'orange juice',
    'baldriantropfen': 'valerian drops',
    'benzen': 'benzene',
    'benzylcarbinol': 'phenylethyl alcohol',
    'bis(2-ethylhexyl)-adipat': 'bis(2-ethylhexyl) adipate',
    'bis(2-ethylhexyl)-phthalat': 'bis(2-ethylhexyl) phthalate',
    'borax': 'borax',
    'butanol': 'butanol',
    'buten': 'butene',
    'butenal, trans-2-': 'trans-2-butenal',
    'butylcarbinol': 'amyl alcohol',
    'butylcellosolve': 'ethylene glycol monobutyl ether',
    'butylglycol': 'butyl glycol',
    'calciumcarbid': 'calcium carbide',
    'calciumhydrat': 'calcium hydroxide',
    'campher': 'camphor',
    'camphogen': 'camphogen',
    'carbazol': 'carbazole',
    'carbinol': 'methanol',
    'carbolineum': 'carbolineum',
    'cellosolve': 'cellosolve',
    'chinin': 'quinine',
    'clophen a60': 'Clophen A60',
    'cumen': 'cumene',
    'curry': 'curry',
    'cyankali': 'potassium cyanide',
    'cyclanon': 'cyclanone',
    'cyclohexanol': 'cyclohexanol',
    'cymol, p-': 'p-cymene',
    'dampf': 'steam',
    'densodrin w': 'Densodrin W',
    'desmodur 44': 'Desmodur 44',
    'dextrin': 'dextrin',
    'dextrose': 'dextrose',
    'diazan': 'hydrazine',
    'dibenzylsebacat': 'dibenzyl sebacate',
    'dibutylsebacat': 'dibutyl sebacate',
    'dicyclohexylphthalat': 'dicyclohexyl phthalate',
    'diethylmalonat': 'diethyl malonate',
    'diethylsebacat': 'diethyl sebacate',
    'diethylsuccinat': 'diethyl succinate',
    'diglycol': 'diethylene glycol',
    'dihexylphthalat': 'dihexyl phthalate',
    'diisooctylphthalat (dop)': 'diisooctyl phthalate (DOP)',
    'dimethylcarbinol': 'isopropanol',
    'dimethylphthalat (dmp)': 'dimethyl phthalate (DMP)',
    'dinonylphthalat (dnp)': 'dinonyl phthalate (DNP)',
    'dioctyladipat': 'dioctyl adipate',
    'dioctylsebacat': 'dioctyl sebacate',
    'dipenten': 'dipentene',
    'dipentylphthalat': 'dipentyl phthalate',
    'diphenylenimin': 'carbazole',
    'diphyl': 'Diphyl',
    'dolcymen': 'Dolcymen',
    'eau de labarraque': 'Labarraque solution',
    'elaol': 'olive oil',
    'emulgatoren': 'emulsifiers',
    'ephetin': 'ephedrine',
    'erdgas': 'natural gas',
    'ethen': 'ethylene',
    'ethin': 'acetylene',
    'ethinylcarbiol': 'propargyl alcohol',
    'ethoxyacetanilid, 4-': '4-ethoxyacetanilide',
    'ethyl-cellosolve': 'ethylene glycol monoethyl ether',
    'ethylbenzen': 'ethylbenzene',
    'ethylbutyrat': 'ethyl butyrate',
    'ethylcarbinol': 'propanol',
    'ethylglycol': 'ethyl glycol',
    'ethylmalonat': 'ethyl malonate',
    'ethylmercaptan': 'ethanethiol',
    'ethylsilicat': 'ethyl silicate',
    'fischtran': 'fish oil',
    'flugmotorenkraftstoffe (jp)': 'aviation fuel (JP)',
    'fluid 101, 100°c': 'Fluid 101, 100°C',
    'fluor': 'fluorine',
    'fluorammonium': 'ammonium fluoride',
    'formalin': 'formalin',
    'formin': 'hexamethylenetetramine',
    'fotoentwickler': 'photographic developer',
    'fotofixierbäder': 'photographic fixer bath',
    'freon 11': 'Freon 11',
    'freon 112': 'Freon 112',
    'freon 113': 'Freon 113',
    'freon 114': 'Freon 114',
    'freon 114 b2': 'Freon 114 B2',
    'freon 115': 'Freon 115',
    'freon 12': 'Freon 12',
    'freon 13': 'Freon 13',
    'freon 13 b1': 'Freon 13 B1',
    'freon 14': 'Freon 14',
    'freon 142b': 'Freon 142b',
    'freon 152a': 'Freon 152a',
    'freon 21': 'Freon 21',
    'freon 218': 'Freon 218',
    'freon 22': 'Freon 22',
    'freon 31': 'Freon 31',
    'freon 32': 'Freon 32',
    'freon c 318': 'Freon C 318',
    'freon c316': 'Freon C316',
    'frigen 12': 'Frigen 12',
    'frigen 21': 'Frigen 21',
    'frigen 22': 'Frigen 22',
    'frostschutzmittel (kfz)': 'antifreeze (automotive)',
    'fruchtsäfte': 'fruit juices',
    'fructose': 'fructose',
    'furan': 'furan',
    'furanal': 'furfural',
    'furancarbinol, 2-': 'furfuryl alcohol',
    'furfural': 'furfural',
    'furfuran': 'furan',
    'furfurol': 'furfural',
    'gallotannin': 'gallotannin',
    'gasoline': 'gasoline',
    'genantin': 'Genantin',
    'gerbeextrakte, pflanzlich': 'vegetable tanning extracts',
    'gerbextrakte': 'tanning extracts',
    'glucose': 'glucose',
    'glucosesirup': 'glucose syrup',
    'glycin': 'glycine',
    'glycol': 'glycol',
    'glykokoll': 'glycine',
    'glysantin': 'Glysantin',
    'grubengas': 'mine gas',
    'gärungsmaische': 'fermentation mash',
    'hefe': 'yeast',
    'helium': 'helium',
    'hexen, 1-': 'hex-1-ene',
    'hexylen': 'hexylene',
    'hydrargillit': 'hydrargillite',
    'hydroxymethylfuran, 2-': '2-hydroxymethylfuran',
    'hydroxymethylfurfural, 5-': '5-hydroxymethylfurfural',
    'ingwer': 'ginger',
    'isobutanol': 'isobutanol',
    'isopropanol': 'isopropanol',
    'isopropylbenzen': 'cumene',
    'kalialaune': 'potassium alum',
    'kalisalpeter': 'potassium nitrate',
    'kardamom': 'cardamom',
    'kraftstoff, normal': 'regular gasoline',
    'kraftstoff, super': 'premium gasoline',
    'kreosot': 'creosote',
    'kümmel': 'caraway',
    'lachgas': 'laughing gas',
    'lactame': 'lactams',
    'lactobiose': 'lactose',
    'lactose': 'lactose',
    'lanolin': 'lanolin',
    'latex': 'latex',
    'lebertran': 'cod liver oil',
    'ligroin': 'ligroin',
    'limonen, dl-': 'DL-limonene',
    'lindan': 'lindane',
    'lorbeer': 'bay leaf',
    'lysol': 'lysol',
    'magnesit': 'magnesite',
    'malonester': 'malonic ester',
    'margarine': 'margarine',
    'melasse': 'molasses',
    'melassewürze': 'molasses wort',
    'menthadien-1,8, p-': 'p-mentha-1,8-diene',
    'menthol': 'menthol',
    'methyl-2-methylpropionat': 'methyl 2-methylpropionate',
    'methylcellosolve': 'ethylene glycol monomethyl ether',
    'methylglycol': 'methyl glycol',
    'methyloxiran': 'propylene oxide',
    'methylpent-4-en-2-on, 5-': '5-methylhex-4-en-2-one',
    'methylpropenoat': 'methyl methacrylate',
    'monopentylphthalat': 'monopentyl phthalate',
    'mowilith d': 'Mowilith D',
    'muskat': 'nutmeg',
    'naphtha': 'naphtha',
    'naphthen': 'naphthene',
    'natronsalpeter': 'sodium nitrate',
    'nelken': 'cloves',
    'netzmittel': 'wetting agents',
    'niacin': 'niacin',
    'nicotin': 'nicotine',
    'nitroglycol': 'nitroglycol',
    'nitrose gase': 'nitrous gases',
    'nitroverdünnung': 'nitro thinner',
    'obstpulp': 'fruit pulp',
    'octal': 'Octal',
    'olein': 'olein',
    'oleum': 'oleum',
    'oleumdämpfe': 'oleum vapors',
    'oxiran': 'ethylene oxide',
    'oxolan': 'tetrahydrofuran',
    'oxymethylfurfurol, 5-': '5-hydroxymethylfurfural',
    'paraform': 'paraformaldehyde',
    'parfüms': 'perfumes',
    'pectin': 'pectin',
    'perhydrol': 'hydrogen peroxide',
    'petrolatum': 'petrolatum',
    'phenacetin': 'phenacetin',
    'phenyl-2-propenal, trans-3-': 'trans-3-phenyl-2-propenal',
    'phenylcarbinol': 'benzyl alcohol',
    'phenylsulfonat': 'phenyl sulfonate',
    'phosgen': 'phosgene',
    'phosphin': 'phosphine',
    'piment': 'allspice',
    'polyglycol': 'polyglycol',
    'polyran m25 n': 'Polyran M25 N',
    'polyran m400': 'Polyran M400',
    'polysiloxan': 'polysiloxane',
    'polysolvan o': 'Polysolvan O',
    'prontosil': 'Prontosil',
    'propanol': 'propanol',
    'propen': 'propene',
    'propen-1-ol, 2-': 'prop-2-en-1-ol',
    'propin-1-ol, 2-': 'prop-2-yn-1-ol',
    'pydraul c (312, 540)': 'Pydraul C (312, 540)',
    'pydraul e (29, 30, 50, 65, 90, 11)': 'Pydraul E (29, 30, 50, 65, 90, 11)',
    'pyrogallol': 'pyrogallol',
    'pyrrol': 'pyrrole',
    'ramasit': 'Ramasit',
    'rindertalg': 'beef tallow',
    'röstgase': 'roasting gases',
    'sagrotan': 'Sagrotan',
    'salmiak': 'sal ammoniac',
    'salmiakgeist': 'ammonia solution',
    'sattdampfkondensat': 'saturated steam condensate',
    'skydrol 500 (b4)': 'Skydrol 500 (B4)',
    'skydrol 7000': 'Skydrol 7000',
    'soda': 'soda',
    'spirituosen': 'spirits',
    'spiritus': 'denatured alcohol',
    'strychnin': 'strychnine',
    'talg': 'tallow',
    'tannin': 'tannin',
    'tenside': 'surfactants',
    'terpentinersatz': 'turpentine substitute',
    'testkraftstoff a (iso-fluid a)': 'test fuel A (ISO-Fluid A)',
    'testkraftstoff b (iso-fluid b)': 'test fuel B (ISO-Fluid B)',
    'testkraftstoff c (iso-fluid c)': 'test fuel C (ISO-Fluid C)',
    'testkraftstoff d (iso-fluid d)': 'test fuel D (ISO-Fluid D)',
    'thiacyclopentadien': 'thiophene',
    'thiofuran': 'thiophene',
    'thiophen': 'thiophene',
    'thymol': 'thymol',
    'toluen': 'toluene',
    'traganth': 'tragacanth',
    'triacetin': 'triacetin',
    'triglycol': 'triethylene glycol',
    'tripen': 'tripene',
    'urotropin': 'hexamethylenetetramine',
    'vaseline': 'petroleum jelly',
    'vinylcarbinol': 'allyl alcohol',
    'walrat': 'spermaceti',
    'weichmacher': 'plasticizers',
    'whiskey': 'whiskey',
    'white spirit': 'white spirit',
    'xenon': 'xenon',
    'xylen': 'xylene',
    'zimt': 'cinnamon',
    'zitronensaft': 'lemon juice',
    'ätzbaryt': 'caustic baryta',
    'ätzkali': 'caustic potash',
    'ätznatron': 'caustic soda',
}

def translate_chemical_name(german_name):
    """Translate a German chemical name to English."""
    result = german_name.lower()
    
    # Try exact match in additional translations first
    if result in ADDITIONAL_TRANSLATIONS:
        return ADDITIONAL_TRANSLATIONS[result].title()
    
    # Try exact match in term translations
    if result in TERM_TRANSLATIONS:
        return TERM_TRANSLATIONS[result].title()
    
    # Apply translations from longest to shortest
    sorted_terms = sorted(TERM_TRANSLATIONS.keys(), key=len, reverse=True)
    
    for de_term in sorted_terms:
        if de_term in result:
            result = result.replace(de_term, TERM_TRANSLATIONS[de_term])
    
    # Capitalize appropriately
    words = result.split()
    capitalized = []
    for i, word in enumerate(words):
        if i == 0:
            capitalized.append(word.capitalize())
        elif word in ['of', 'and', 'or', 'the', 'a', 'an', 'in']:
            capitalized.append(word)
        elif word.startswith(('di', 'tri', 'tetra', 'penta', 'hexa', 'mono', 'poly', 'iso', 'n-', 'o-', 'm-', 'p-')):
            capitalized.append(word)
        else:
            capitalized.append(word)
    
    return ' '.join(capitalized)


def main():
    # Load chemical data
    with open('data/chemicals_burkle_full.json', 'r', encoding='utf-8') as f:
        chemicals = json.load(f)
    
    # Get unique names and translate
    names = sorted(set(c['name'] for c in chemicals))
    
    translations = {}
    for name in names:
        translated = translate_chemical_name(name)
        if translated:
            translations[name.lower()] = translated
    
    print(f"Translated {len(translations)} of {len(names)} chemical names")
    
    # Output as JavaScript object
    js_output = "// German → English chemical name translations\n"
    js_output += "// Auto-generated - " + str(len(translations)) + " translations\n"
    js_output += "const chemicalTranslations = {\n"
    
    for de, en in sorted(translations.items()):
        de_escaped = de.replace("'", "\\'")
        en_escaped = en.replace("'", "\\'")
        js_output += f"    '{de_escaped}': '{en_escaped}',\n"
    
    js_output += "};\n"
    
    # Save to file
    with open('js/chemical_translations_en.js', 'w', encoding='utf-8') as f:
        f.write(js_output)
    
    print(f"Saved translations to js/chemical_translations_en.js")
    
    # Print some samples
    print("\nSample translations:")
    samples = list(translations.items())[:20]
    for de, en in samples:
        print(f"  {de} → {en}")


if __name__ == '__main__':
    main()
