#!/usr/bin/env python3
"""
Translate all German chemical names to French for chemicalresistance.org
"""
import json
import re

# Comprehensive German → French chemical term translations
# Order matters - more specific terms first

TERM_TRANSLATIONS = {
    # Specific compounds first (most specific match wins)
    'acetanhydrid': 'anhydride acétique',
    'acetylchlorid': 'chlorure d\'acétyle',
    'benzoylchlorid': 'chlorure de benzoyle',
    'benzylchlorid': 'chlorure de benzyle',
    'amylchlorid': 'chlorure d\'amyle',
    'carbonylchlorid': 'phosgène',
    'thionylchlorid': 'chlorure de thionyle',
    'sulfurylchlorid': 'chlorure de sulfuryle',
    'acetylentetrachlorid': 'tétrachloroéthane',
    'acetylentetrabromid': 'tétrabromoéthane',
    'antimonpentachlorid': 'pentachlorure d\'antimoine',
    'antimontrichlorid': 'trichlorure d\'antimoine',
    'antimon-(iii)-chlorid': 'chlorure d\'antimoine(III)',
    'antimon-(v)-chlorid': 'chlorure d\'antimoine(V)',
    'anilinhydrochlorid': 'chlorhydrate d\'aniline',
    'aniliniumchlorid': 'chlorure d\'anilinium',
    'arsenanhydrid': 'anhydride arsénieux',
    'arsensäureanhydrid': 'anhydride arsénique',
    'benzolhexachlorid': 'hexachlorocyclohexane',
    'bismutchlorid': 'chlorure de bismuth',
    'buttersäureethylester': 'butyrate d\'éthyle',
    'buttersäuremethylester': 'butyrate de méthyle',
    'bernsteinsäurediethylester': 'succinate de diéthyle',
    'phthalsäurediethylester': 'phtalate de diéthyle',
    'phthalsäuredibutylester': 'phtalate de dibutyle',
    'phthalsäuredioctylester': 'phtalate de dioctyle',
    'sebacinsäure': 'acide sébacique',
    
    # Acids (Säuren → Acides)
    'schwefelsäure': 'acide sulfurique',
    'salzsäure': 'acide chlorhydrique',
    'salpetersäure': 'acide nitrique',
    'phosphorsäure': 'acide phosphorique',
    'essigsäureanhydrid': 'anhydride acétique',
    'essigsäureamid': 'acétamide',
    'essigsäurebutylester': 'acétate de butyle',
    'essigsäureethylester': 'acétate d\'éthyle',
    'essigsäuremethylester': 'acétate de méthyle',
    'essigsäureamylester': 'acétate d\'amyle',
    'essigsäurepropylester': 'acétate de propyle',
    'essigsäurevinylester': 'acétate de vinyle',
    'essigsäureallylester': 'acétate d\'allyle',
    'essigsäurebenzylester': 'acétate de benzyle',
    'essigsäure-n-amylester': 'acétate de n-amyle',
    'essigsäure silbersalz': 'acétate d\'argent',
    'chloressigsäureethylester': 'chloroacétate d\'éthyle',
    'chloressigsäuremethylester': 'chloroacétate de méthyle',
    'dichloressigsäuremethylester': 'dichloroacétate de méthyle',
    'cyanessigsäureethylester': 'cyanoacétate d\'éthyle',
    'essigsäure': 'acide acétique',
    'ameisensäureamid': 'formamide',
    'ameisensäureethylester': 'formiate d\'éthyle',
    'ameisensäuremethylester': 'formiate de méthyle',
    'ameisensäure': 'acide formique',
    'zitronensäure': 'acide citrique',
    'milchsäure': 'acide lactique',
    'oxalsäure': 'acide oxalique',
    'chromsäure': 'acide chromique',
    'flusssäure': 'acide fluorhydrique',
    'fluorwasserstoffsäure': 'acide fluorhydrique',
    'kohlensäure': 'acide carbonique',
    'borsäure': 'acide borique',
    'benzoesäurealdehyd': 'benzaldéhyde',
    'benzoesäurechlorid': 'chlorure de benzoyle',
    'benzoesäureethylester': 'benzoate d\'éthyle',
    'benzoesäuremethylester': 'benzoate de méthyle',
    'benzoesäurebenzylester': 'benzoate de benzyle',
    'benzoesäure natriumsalz': 'benzoate de sodium',
    'benzoesäure': 'acide benzoïque',
    'weinsäure': 'acide tartrique',
    'bernsteinsäure': 'acide succinique',
    'maleinsäure': 'acide maléique',
    'fumarsäure': 'acide fumarique',
    'adipinsäuredioctylester': 'adipate de dioctyle',
    'adipinsäure': 'acide adipique',
    'akkusäure': 'acide de batterie',
    'stearinsäure': 'acide stéarique',
    'ölsäure': 'acide oléique',
    'palmitinsäure': 'acide palmitique',
    'laurinsäure': 'acide laurique',
    'caprylsäure': 'acide caprylique',
    'capronsäure': 'acide caproïque',
    'buttersäure': 'acide butyrique',
    'propionsäure': 'acide propionique',
    'acrylsäurebutylester': 'acrylate de butyle',
    'acrylsäureethylester': 'acrylate d\'éthyle',
    'acrylsäuremethylester': 'acrylate de méthyle',
    'acrylsäurenitril': 'acrylonitrile',
    'acrylsäure': 'acide acrylique',
    'methacrylsäure': 'acide méthacrylique',
    'glykolsäure': 'acide glycolique',
    'glycolsäure': 'acide glycolique',
    'brenztraubensäure': 'acide pyruvique',
    'glutaminsäure': 'acide glutamique',
    'asparaginsäure': 'acide aspartique',
    'phthalsäure': 'acide phtalique',
    'isophthalsäure': 'acide isophtalique',
    'terephthalsäure': 'acide téréphtalique',
    'toluolsulfonsäure': 'acide toluènesulfonique',
    'benzolsulfonsäure': 'acide benzènesulfonique',
    'sulfanilsäure': 'acide sulfanilique',
    'pikrinsäure': 'acide picrique',
    'gallussäure': 'acide gallique',
    'gerbsäure': 'acide tannique',
    'harnsäure': 'acide urique',
    'hippursäure': 'acide hippurique',
    'ascorbinsäure': 'acide ascorbique',
    'nikotinsäure': 'acide nicotinique',
    'folsäure': 'acide folique',
    'fettsäure': 'acide gras',
    'fettsäuren': 'acides gras',
    'aminoessigsäure': 'glycine',
    'aminoethansäure': 'glycine',
    'aminopropionsäure': 'alanine',
    'aminosäure': 'acide aminé',
    'aminosäuren': 'acides aminés',
    'carbonsäure': 'acide carboxylique',
    'dicarbonsäure': 'acide dicarboxylique',
    'tricarbonsäure': 'acide tricarboxylique',
    'monocarbonsäure': 'acide monocarboxylique',
    'hydroxycarbonsäure': 'acide hydroxycarboxylique',
    'sulfonsäure': 'acide sulfonique',
    'phosphonsäure': 'acide phosphonique',
    'arsensäure': 'acide arsénique',
    'arsenigsäure': 'acide arsénieux',
    'antimonsäure': 'acide antimonique',
    'kieselsäure': 'acide silicique',
    'kieselflusssäure': 'acide fluorosilicique',
    'hexafluorokieselsäure': 'acide hexafluorosilicique',
    'perchlorsäure': 'acide perchlorique',
    'chlorsäure': 'acide chlorique',
    'hypochlorigsäure': 'acide hypochloreux',
    'chlorigsäure': 'acide chloreux',
    'bromsäure': 'acide bromique',
    'bromwasserstoffsäure': 'acide bromhydrique',
    'jodwasserstoffsäure': 'acide iodhydrique',
    'jodsäure': 'acide iodique',
    'periodsäure': 'acide periodique',
    'blausäure': 'acide cyanhydrique',
    'cyanwasserstoffsäure': 'acide cyanhydrique',
    'rhodanwasserstoffsäure': 'acide thiocyanique',
    'thiocyansäure': 'acide thiocyanique',
    'schwefelwasserstoffsäure': 'acide sulfhydrique',
    'schwefligesäure': 'acide sulfureux',
    'unterschwefligesäure': 'acide thiosulfurique',
    'thioschwefelsäure': 'acide thiosulfurique',
    'dithionige säure': 'acide dithioneux',
    'polythionsäure': 'acide polythionique',
    'selensäure': 'acide sélénique',
    'selenige säure': 'acide sélénieux',
    'tellursäure': 'acide tellurique',
    'molybdänsäure': 'acide molybdique',
    'wolframsäure': 'acide tungstique',
    'vanadinsäure': 'acide vanadique',
    'permangansäure': 'acide permanganique',
    'übermangansäure': 'acide permanganique',
    'mangansäure': 'acide manganique',
    'salicylsäure': 'acide salicylique',
    'acetylsalicylsäure': 'acide acétylsalicylique',
    'zimtsäure': 'acide cinnamique',
    'sorbinsäure': 'acide sorbique',
    'peressigsäure': 'acide peracétique',
    'perameisensäure': 'acide performique',
    'perbenzoesäure': 'acide perbenzoïque',
    'monopercarbonsäure': 'acide monopercarboxylique',
    'crotonsäure': 'acide crotonique',
    'undecylensäure': 'acide undécylénique',
    'linolsäure': 'acide linoléique',
    'linolensäure': 'acide linolénique',
    'elaidinsäure': 'acide élaïdique',
    'erucasäure': 'acide érucique',
    'ricinolsäure': 'acide ricinoléique',
    'säure': 'acide',  # Generic - must be last
    
    # Bases/Hydroxides (Laugen/Hydroxide → Bases/Hydroxydes)
    'natronlauge': 'soude caustique',
    'kalilauge': 'potasse caustique',
    'natriumhydroxid': 'hydroxyde de sodium',
    'kaliumhydroxid': 'hydroxyde de potassium',
    'calciumhydroxid': 'hydroxyde de calcium',
    'magnesiumhydroxid': 'hydroxyde de magnésium',
    'bariumhydroxid': 'hydroxyde de baryum',
    'strontiumhydroxid': 'hydroxyde de strontium',
    'lithiumhydroxid': 'hydroxyde de lithium',
    'ammoniumhydroxid': 'hydroxyde d\'ammonium',
    'aluminiumhydroxid': 'hydroxyde d\'aluminium',
    'eisenhydroxid': 'hydroxyde de fer',
    'kupferhydroxid': 'hydroxyde de cuivre',
    'zinkhydroxid': 'hydroxyde de zinc',
    'hydroxid': 'hydroxyde',
    'lauge': 'lessive',
    
    # Salts - Chlorides (Chloride → Chlorures)
    'natriumchlorid': 'chlorure de sodium',
    'kaliumchlorid': 'chlorure de potassium',
    'calciumchlorid': 'chlorure de calcium',
    'magnesiumchlorid': 'chlorure de magnésium',
    'bariumchlorid': 'chlorure de baryum',
    'strontiumchlorid': 'chlorure de strontium',
    'lithiumchlorid': 'chlorure de lithium',
    'ammoniumchlorid': 'chlorure d\'ammonium',
    'aluminiumchlorid': 'chlorure d\'aluminium',
    'eisenchlorid': 'chlorure de fer',
    'eisen(iii)chlorid': 'chlorure de fer(III)',
    'eisen(ii)chlorid': 'chlorure de fer(II)',
    'eisen-iii-chlorid': 'chlorure de fer(III)',
    'eisen-ii-chlorid': 'chlorure de fer(II)',
    'kupferchlorid': 'chlorure de cuivre',
    'zinkchlorid': 'chlorure de zinc',
    'zinnchlorid': 'chlorure d\'étain',
    'bleichlorid': 'chlorure de plomb',
    'quecksilberchlorid': 'chlorure de mercure',
    'silberchlorid': 'chlorure d\'argent',
    'goldchlorid': 'chlorure d\'or',
    'platinchlorid': 'chlorure de platine',
    'nickelchlorid': 'chlorure de nickel',
    'cobaltchlorid': 'chlorure de cobalt',
    'manganchlorid': 'chlorure de manganèse',
    'chromchlorid': 'chlorure de chrome',
    'titantetrachlorid': 'tétrachlorure de titane',
    'siliciumtetrachlorid': 'tétrachlorure de silicium',
    'kohlenstofftetrachlorid': 'tétrachlorure de carbone',
    'tetrachlorkohlenstoff': 'tétrachlorure de carbone',
    'chlorid': 'chlorure',
    
    # Salts - Sulfates (Sulfate → Sulfates)
    'natriumsulfat': 'sulfate de sodium',
    'kaliumsulfat': 'sulfate de potassium',
    'calciumsulfat': 'sulfate de calcium',
    'magnesiumsulfat': 'sulfate de magnésium',
    'bariumsulfat': 'sulfate de baryum',
    'ammoniumsulfat': 'sulfate d\'ammonium',
    'aluminiumsulfat': 'sulfate d\'aluminium',
    'eisensulfat': 'sulfate de fer',
    'kupfersulfat': 'sulfate de cuivre',
    'zinksulfat': 'sulfate de zinc',
    'nickelsulfat': 'sulfate de nickel',
    'cobaltsulfat': 'sulfate de cobalt',
    'mangansulfat': 'sulfate de manganèse',
    'chromsulfat': 'sulfate de chrome',
    'sulfat': 'sulfate',
    
    # Salts - Nitrates (Nitrate → Nitrates)
    'natriumnitrat': 'nitrate de sodium',
    'kaliumnitrat': 'nitrate de potassium',
    'calciumnitrat': 'nitrate de calcium',
    'magnesiumnitrat': 'nitrate de magnésium',
    'bariumnitrat': 'nitrate de baryum',
    'ammoniumnitrat': 'nitrate d\'ammonium',
    'aluminiumnitrat': 'nitrate d\'aluminium',
    'eisennitrat': 'nitrate de fer',
    'kupfernitrat': 'nitrate de cuivre',
    'zinknitrat': 'nitrate de zinc',
    'silbernitrat': 'nitrate d\'argent',
    'bleinitrat': 'nitrate de plomb',
    'nitrat': 'nitrate',
    
    # Salts - Carbonates (Carbonate → Carbonates)
    'natriumcarbonat': 'carbonate de sodium',
    'kaliumcarbonat': 'carbonate de potassium',
    'calciumcarbonat': 'carbonate de calcium',
    'magnesiumcarbonat': 'carbonate de magnésium',
    'bariumcarbonat': 'carbonate de baryum',
    'ammoniumcarbonat': 'carbonate d\'ammonium',
    'lithiumcarbonat': 'carbonate de lithium',
    'natriumhydrogencarbonat': 'hydrogénocarbonate de sodium',
    'kaliumhydrogencarbonat': 'hydrogénocarbonate de potassium',
    'ammoniumhydrogencarbonat': 'hydrogénocarbonate d\'ammonium',
    'natriumbicarbonat': 'bicarbonate de sodium',
    'kaliumbicarbonat': 'bicarbonate de potassium',
    'ammoniumbicarbonat': 'bicarbonate d\'ammonium',
    'carbonat': 'carbonate',
    'bicarbonat': 'bicarbonate',
    'hydrogencarbonat': 'hydrogénocarbonate',
    
    # Salts - Phosphates (Phosphate → Phosphates)
    'natriumphosphat': 'phosphate de sodium',
    'kaliumphosphat': 'phosphate de potassium',
    'calciumphosphat': 'phosphate de calcium',
    'ammoniumphosphat': 'phosphate d\'ammonium',
    'dinatriumhydrogenphosphat': 'hydrogénophosphate de disodium',
    'natriumdihydrogenphosphat': 'dihydrogénophosphate de sodium',
    'ammoniumdihydrogenphosphat': 'dihydrogénophosphate d\'ammonium',
    'phosphat': 'phosphate',
    'hydrogenphosphat': 'hydrogénophosphate',
    'dihydrogenphosphat': 'dihydrogénophosphate',
    'polyphosphat': 'polyphosphate',
    'metaphosphat': 'métaphosphate',
    'pyrophosphat': 'pyrophosphate',
    
    # Salts - Others
    'natriumsulfit': 'sulfite de sodium',
    'natriumthiosulfat': 'thiosulfate de sodium',
    'natriumhypochlorit': 'hypochlorite de sodium',
    'calciumhypochlorit': 'hypochlorite de calcium',
    'natriumchlorat': 'chlorate de sodium',
    'kaliumchlorat': 'chlorate de potassium',
    'natriumperchlorat': 'perchlorate de sodium',
    'kaliumperchlorat': 'perchlorate de potassium',
    'natriumbromat': 'bromate de sodium',
    'kaliumbromat': 'bromate de potassium',
    'natriumjodat': 'iodate de sodium',
    'kaliumjodat': 'iodate de potassium',
    'natriumfluorid': 'fluorure de sodium',
    'kaliumfluorid': 'fluorure de potassium',
    'calciumfluorid': 'fluorure de calcium',
    'ammoniumfluorid': 'fluorure d\'ammonium',
    'ammoniumbifluorid': 'bifluorure d\'ammonium',
    'ammoniumhydrogendifluorid': 'hydrogénodifluorure d\'ammonium',
    'natriumcyanid': 'cyanure de sodium',
    'kaliumcyanid': 'cyanure de potassium',
    'natriumsulfid': 'sulfure de sodium',
    'kaliumsulfid': 'sulfure de potassium',
    'ammoniumsulfid': 'sulfure d\'ammonium',
    'calciumsulfid': 'sulfure de calcium',
    'natriumhydrogensulfid': 'hydrogénosulfure de sodium',
    'ammoniumhydrogensulfid': 'hydrogénosulfure d\'ammonium',
    'ammoniumhydrosulfid': 'hydrosulfure d\'ammonium',
    'natriumacetat': 'acétate de sodium',
    'kaliumacetat': 'acétate de potassium',
    'calciumacetat': 'acétate de calcium',
    'ammoniumacetat': 'acétate d\'ammonium',
    'bleiacetat': 'acétate de plomb',
    'kupferacetat': 'acétate de cuivre',
    'zinkacetat': 'acétate de zinc',
    'natriumformiat': 'formiate de sodium',
    'kaliumformiat': 'formiate de potassium',
    'ammoniumformiat': 'formiate d\'ammonium',
    'natriumoxalat': 'oxalate de sodium',
    'kaliumoxalat': 'oxalate de potassium',
    'ammoniumoxalat': 'oxalate d\'ammonium',
    'calciumoxalat': 'oxalate de calcium',
    'natriumcitrat': 'citrate de sodium',
    'kaliumcitrat': 'citrate de potassium',
    'calciumcitrat': 'citrate de calcium',
    'natriumtartrat': 'tartrate de sodium',
    'kaliumtartrat': 'tartrate de potassium',
    'kaliumnatriumtartrat': 'tartrate de potassium et sodium',
    'natriumbenzoat': 'benzoate de sodium',
    'kaliumbenzoat': 'benzoate de potassium',
    'natriumsalicylat': 'salicylate de sodium',
    'natriumlactat': 'lactate de sodium',
    'calciumlactat': 'lactate de calcium',
    'natriumgluconat': 'gluconate de sodium',
    'calciumgluconat': 'gluconate de calcium',
    'natriumstearat': 'stéarate de sodium',
    'calciumstearat': 'stéarate de calcium',
    'zinkstearat': 'stéarate de zinc',
    'magnesiumstearat': 'stéarate de magnésium',
    'natriumoleat': 'oléate de sodium',
    'natriumlaurat': 'laurate de sodium',
    'natriumpalmitat': 'palmitate de sodium',
    'sulfit': 'sulfite',
    'thiosulfat': 'thiosulfate',
    'hypochlorit': 'hypochlorite',
    'chlorat': 'chlorate',
    'perchlorat': 'perchlorate',
    'bromat': 'bromate',
    'bromid': 'bromure',
    'jodat': 'iodate',
    'jodid': 'iodure',
    'fluorid': 'fluorure',
    'bifluorid': 'bifluorure',
    'cyanid': 'cyanure',
    'sulfid': 'sulfure',
    'hydrosulfid': 'hydrosulfure',
    'acetat': 'acétate',
    'formiat': 'formiate',
    'oxalat': 'oxalate',
    'citrat': 'citrate',
    'tartrat': 'tartrate',
    'benzoat': 'benzoate',
    'salicylat': 'salicylate',
    'lactat': 'lactate',
    'gluconat': 'gluconate',
    'stearat': 'stéarate',
    'oleat': 'oléate',
    'laurat': 'laurate',
    'palmitat': 'palmitate',
    'silikat': 'silicate',
    'borat': 'borate',
    'chromat': 'chromate',
    'dichromat': 'dichromate',
    'permanganat': 'permanganate',
    'molybdat': 'molybdate',
    'wolframat': 'tungstate',
    'vanadat': 'vanadate',
    'arsenat': 'arséniate',
    'arsenit': 'arsénite',
    'antimonat': 'antimoniate',
    'stannat': 'stannate',
    'plumbat': 'plombate',
    'zirkonat': 'zirconate',
    'titanat': 'titanate',
    'aluminat': 'aluminate',
    'ferrat': 'ferrate',
    'manganat': 'manganate',
    'rhodanid': 'thiocyanate',
    'thiocyanat': 'thiocyanate',
    'sulfocyanid': 'thiocyanate',
    'ferrocyanid': 'ferrocyanure',
    'ferricyanid': 'ferricyanure',
    'hexacyanoferrat': 'hexacyanoferrate',
    'nitrit': 'nitrite',
    'nitrid': 'nitrure',
    'hydrid': 'hydrure',
    'amid': 'amidure',
    'azid': 'azoture',
    'peroxid': 'peroxyde',
    'superoxid': 'superoxyde',
    'oxid': 'oxyde',
    
    # Organic compounds - Alcohols
    'methanol': 'méthanol',
    'ethanol': 'éthanol',
    'äthanol': 'éthanol',
    'propanol': 'propanol',
    'isopropanol': 'isopropanol',
    'butanol': 'butanol',
    'isobutanol': 'isobutanol',
    'pentanol': 'pentanol',
    'amylalkohol': 'alcool amylique',
    'hexanol': 'hexanol',
    'heptanol': 'heptanol',
    'octanol': 'octanol',
    'decanol': 'décanol',
    'dodecanol': 'dodécanol',
    'laurylalkohol': 'alcool laurylique',
    'cetylalkohol': 'alcool cétylique',
    'stearylalkohol': 'alcool stéarylique',
    'benzylalkohol': 'alcool benzylique',
    'phenylethanol': 'phényléthanol',
    'cyclohexanol': 'cyclohexanol',
    'ethylenglykol': 'éthylène glycol',
    'äthylenglykol': 'éthylène glycol',
    'propylenglykol': 'propylène glycol',
    'diethylenglykol': 'diéthylène glycol',
    'triethylenglykol': 'triéthylène glycol',
    'polyethylenglykol': 'polyéthylène glycol',
    'glycerin': 'glycérine',
    'glyzerin': 'glycérine',
    'glycerol': 'glycérol',
    'allylalkohol': 'alcool allylique',
    'furfurylalkohol': 'alcool furfurylique',
    'tetrahydrofurfurylalkohol': 'alcool tétrahydrofurfurylique',
    'alkohol': 'alcool',
    
    # Organic compounds - Aldehydes & Ketones
    'formaldehyd': 'formaldéhyde',
    'acetaldehyd': 'acétaldéhyde',
    'propionaldehyd': 'propionaldéhyde',
    'butyraldehyd': 'butyraldéhyde',
    'benzaldehyd': 'benzaldéhyde',
    'furfural': 'furfural',
    'acrolein': 'acroléine',
    'crotonaldehyd': 'crotonaldéhyde',
    'glutaraldehyd': 'glutaraldéhyde',
    'aldehyd': 'aldéhyde',
    'aceton': 'acétone',
    'methylethylketon': 'méthyléthylcétone',
    'methylisobutylketon': 'méthylisobutylcétone',
    'cyclohexanon': 'cyclohexanone',
    'acetophenon': 'acétophénone',
    'keton': 'cétone',
    
    # Organic compounds - Ethers
    'diethylether': 'éther diéthylique',
    'diäthylether': 'éther diéthylique',
    'äther': 'éther',
    'ether': 'éther',
    'methyltertiärbutylether': 'éther méthyl-tert-butylique',
    'tetrahydrofuran': 'tétrahydrofurane',
    'dioxan': 'dioxane',
    'dimethoxyethan': 'diméthoxyéthane',
    'diglyme': 'diglyme',
    'triglyme': 'triglyme',
    'anisol': 'anisole',
    'phenetol': 'phénétole',
    'kronenether': 'éther couronne',
    
    # Organic compounds - Esters
    'methylacetat': 'acétate de méthyle',
    'ethylacetat': 'acétate d\'éthyle',
    'äthylacetat': 'acétate d\'éthyle',
    'butylacetat': 'acétate de butyle',
    'amylacetat': 'acétate d\'amyle',
    'isoamylacetat': 'acétate d\'isoamyle',
    'benzylacetat': 'acétate de benzyle',
    'methylformiat': 'formiate de méthyle',
    'ethylformiat': 'formiate d\'éthyle',
    'methylbenzoat': 'benzoate de méthyle',
    'ethylbenzoat': 'benzoate d\'éthyle',
    'methylsalicylat': 'salicylate de méthyle',
    'methylmethacrylat': 'méthacrylate de méthyle',
    'ethylacrylat': 'acrylate d\'éthyle',
    'butylacrylat': 'acrylate de butyle',
    'dioctylphthalat': 'phtalate de dioctyle',
    'dibutylphthalat': 'phtalate de dibutyle',
    'ester': 'ester',
    
    # Organic compounds - Amines
    'methylamin': 'méthylamine',
    'dimethylamin': 'diméthylamine',
    'trimethylamin': 'triméthylamine',
    'ethylamin': 'éthylamine',
    'äthylamin': 'éthylamine',
    'diethylamin': 'diéthylamine',
    'triethylamin': 'triéthylamine',
    'propylamin': 'propylamine',
    'isopropylamin': 'isopropylamine',
    'butylamin': 'butylamine',
    'hexylamin': 'hexylamine',
    'octylamin': 'octylamine',
    'dodecylamin': 'dodécylamine',
    'cyclohexylamin': 'cyclohexylamine',
    'anilin': 'aniline',
    'toluidin': 'toluidine',
    'xylidin': 'xylidine',
    'benzylamin': 'benzylamine',
    'ethanolamin': 'éthanolamine',
    'äthanolamin': 'éthanolamine',
    'diethanolamin': 'diéthanolamine',
    'triethanolamin': 'triéthanolamine',
    'ethylendiamin': 'éthylènediamine',
    'äthylendiamin': 'éthylènediamine',
    'diethylentriamin': 'diéthylènetriamine',
    'triethylentetramin': 'triéthylènetétramine',
    'hexamethylendiamin': 'hexaméthylènediamine',
    'morpholin': 'morpholine',
    'piperidin': 'pipéridine',
    'pyrrolidin': 'pyrrolidine',
    'pyridin': 'pyridine',
    'chinolin': 'quinoléine',
    'isochinolin': 'isoquinoléine',
    'acridin': 'acridine',
    'hydrazin': 'hydrazine',
    'hydroxylamin': 'hydroxylamine',
    'amin': 'amine',
    
    # Organic compounds - Amides
    'formamid': 'formamide',
    'acetamid': 'acétamide',
    'dimethylformamid': 'diméthylformamide',
    'dimethylacetamid': 'diméthylacétamide',
    'n-methylpyrrolidon': 'N-méthylpyrrolidone',
    'methylpyrrolidon': 'méthylpyrrolidone',
    'harnstoff': 'urée',
    'thioharnstoff': 'thiourée',
    'caprolactam': 'caprolactame',
    
    # Organic compounds - Nitriles
    'acetonitril': 'acétonitrile',
    'propionitril': 'propionitrile',
    'butyronitril': 'butyronitrile',
    'benzonitril': 'benzonitrile',
    'acrylnitril': 'acrylonitrile',
    'adiponitril': 'adiponitrile',
    'nitril': 'nitrile',
    
    # Aromatic compounds
    'benzol': 'benzène',
    'toluol': 'toluène',
    'xylol': 'xylène',
    'ethylbenzol': 'éthylbenzène',
    'äthylbenzol': 'éthylbenzène',
    'cumol': 'cumène',
    'styrol': 'styrène',
    'naphthalin': 'naphtalène',
    'anthracen': 'anthracène',
    'phenanthren': 'phénanthrène',
    'fluoren': 'fluorène',
    'phenol': 'phénol',
    'kresol': 'crésol',
    'xylenol': 'xylénol',
    'hydrochinon': 'hydroquinone',
    'resorcin': 'résorcinol',
    'brenzkatechin': 'catéchol',
    'pyrogallol': 'pyrogallol',
    'chlorbenzol': 'chlorobenzène',
    'dichlorbenzol': 'dichlorobenzène',
    'trichlorbenzol': 'trichlorobenzène',
    'brombenzol': 'bromobenzène',
    'jodbenzol': 'iodobenzène',
    'nitrobenzol': 'nitrobenzène',
    'dinitrobenzol': 'dinitrobenzène',
    'trinitrobenzol': 'trinitrobenzène',
    'nitrotoluol': 'nitrotoluène',
    'dinitrotoluol': 'dinitrotoluène',
    'trinitrotoluol': 'trinitrotoluène',
    'chlortoluol': 'chlorotoluène',
    'anisol': 'anisole',
    'phenetol': 'phénétole',
    
    # Aliphatic hydrocarbons
    'methan': 'méthane',
    'ethan': 'éthane',
    'äthan': 'éthane',
    'propan': 'propane',
    'butan': 'butane',
    'isobutan': 'isobutane',
    'pentan': 'pentane',
    'isopentan': 'isopentane',
    'neopentan': 'néopentane',
    'hexan': 'hexane',
    'heptan': 'heptane',
    'octan': 'octane',
    'isooctan': 'isooctane',
    'nonan': 'nonane',
    'decan': 'décane',
    'undecan': 'undécane',
    'dodecan': 'dodécane',
    'tridecan': 'tridécane',
    'tetradecan': 'tétradécane',
    'pentadecan': 'pentadécane',
    'hexadecan': 'hexadécane',
    'heptadecan': 'heptadécane',
    'octadecan': 'octadécane',
    'cyclohexan': 'cyclohexane',
    'cyclopentan': 'cyclopentane',
    'cycloheptan': 'cycloheptane',
    'methylcyclohexan': 'méthylcyclohexane',
    'ethylen': 'éthylène',
    'äthylen': 'éthylène',
    'propylen': 'propylène',
    'butylen': 'butylène',
    'isobutylen': 'isobutylène',
    'butadien': 'butadiène',
    'isopren': 'isoprène',
    'acetylen': 'acétylène',
    
    # Halogenated compounds
    'chlormethan': 'chlorométhane',
    'dichlormethan': 'dichlorométhane',
    'trichlormethan': 'trichlorométhane',
    'chloroform': 'chloroforme',
    'tetrachlormethan': 'tétrachlorométhane',
    'chlorethan': 'chloroéthane',
    'dichlorethan': 'dichloroéthane',
    'trichlorethan': 'trichloroéthane',
    'tetrachlorethan': 'tétrachloroéthane',
    'chlorethylen': 'chloroéthylène',
    'dichlorethylen': 'dichloroéthylène',
    'trichlorethylen': 'trichloroéthylène',
    'tetrachlorethylen': 'tétrachloroéthylène',
    'perchlorethylen': 'perchloroéthylène',
    'vinylchlorid': 'chlorure de vinyle',
    'vinylidenchlorid': 'chlorure de vinylidène',
    'allylchlorid': 'chlorure d\'allyle',
    'epichlorhydrin': 'épichlorhydrine',
    'chloraceton': 'chloroacétone',
    'chloressigsäure': 'acide chloroacétique',
    'dichloressigsäure': 'acide dichloroacétique',
    'trichloressigsäure': 'acide trichloroacétique',
    'brommethan': 'bromométhane',
    'dibromethan': 'dibromoéthane',
    'bromwasserstoff': 'bromure d\'hydrogène',
    'jodmethan': 'iodométhane',
    'fluorwasserstoff': 'fluorure d\'hydrogène',
    'chlorwasserstoff': 'chlorure d\'hydrogène',
    'fluor': 'fluor',
    'chlor': 'chlore',
    'brom': 'brome',
    'jod': 'iode',
    
    # Sulfur compounds
    'schwefelwasserstoff': 'sulfure d\'hydrogène',
    'schwefeldioxid': 'dioxyde de soufre',
    'schwefeltrioxid': 'trioxyde de soufre',
    'schwefelkohlenstoff': 'disulfure de carbone',
    'kohlenstoffdisulfid': 'disulfure de carbone',
    'dimethylsulfoxid': 'diméthylsulfoxyde',
    'dimethylsulfon': 'diméthylsulfone',
    'thiophene': 'thiophène',
    'mercaptan': 'mercaptan',
    'thiol': 'thiol',
    'schwefel': 'soufre',
    
    # Nitrogen compounds
    'stickstoff': 'azote',
    'stickstoffoxid': 'oxyde d\'azote',
    'stickstoffdioxid': 'dioxyde d\'azote',
    'distickstoffoxid': 'protoxyde d\'azote',
    'distickstofftetroxid': 'tétroxyde de diazote',
    'stickstoffmonoxid': 'monoxyde d\'azote',
    'ammoniak': 'ammoniac',
    'ammoniakwasser': 'ammoniaque',
    
    # Phosphorus compounds
    'phosphor': 'phosphore',
    'phosphortrichlorid': 'trichlorure de phosphore',
    'phosphorpentachlorid': 'pentachlorure de phosphore',
    'phosphoroxychlorid': 'oxychlorure de phosphore',
    'phosphorsäuretributylester': 'phosphate de tributyle',
    'phosphorsäuretriphenylester': 'phosphate de triphényle',
    
    # Metals
    'natrium': 'sodium',
    'kalium': 'potassium',
    'lithium': 'lithium',
    'calcium': 'calcium',
    'magnesium': 'magnésium',
    'barium': 'baryum',
    'strontium': 'strontium',
    'aluminium': 'aluminium',
    'eisen': 'fer',
    'kupfer': 'cuivre',
    'zink': 'zinc',
    'zinn': 'étain',
    'blei': 'plomb',
    'quecksilber': 'mercure',
    'silber': 'argent',
    'gold': 'or',
    'platin': 'platine',
    'palladium': 'palladium',
    'nickel': 'nickel',
    'cobalt': 'cobalt',
    'chrom': 'chrome',
    'mangan': 'manganèse',
    'titan': 'titane',
    'vanadium': 'vanadium',
    'molybdän': 'molybdène',
    'wolfram': 'tungstène',
    'cadmium': 'cadmium',
    'antimon': 'antimoine',
    'arsen': 'arsenic',
    'wismut': 'bismuth',
    'selen': 'sélénium',
    'tellur': 'tellure',
    
    # Common technical terms
    'wasserstoff': 'hydrogène',
    'sauerstoff': 'oxygène',
    'kohlenstoff': 'carbone',
    'kohlendioxid': 'dioxyde de carbone',
    'kohlenmonoxid': 'monoxyde de carbone',
    'wasser': 'eau',
    'meerwasser': 'eau de mer',
    'leitungswasser': 'eau du robinet',
    'destilliertes wasser': 'eau distillée',
    'salzwasser': 'eau salée',
    'sole': 'saumure',
    'kochsalzlösung': 'solution saline',
    'luft': 'air',
    'ozon': 'ozone',
    'wasserstoffperoxid': 'peroxyde d\'hydrogène',
    'wasserstoffperoxyd': 'peroxyde d\'hydrogène',
    'peroxid': 'peroxyde',
    
    # Petroleum products
    'benzin': 'essence',
    'diesel': 'diesel',
    'dieselkraftstoff': 'carburant diesel',
    'heizöl': 'fioul',
    'kerosin': 'kérosène',
    'petroleum': 'pétrole',
    'erdöl': 'pétrole brut',
    'rohöl': 'pétrole brut',
    'mineralöl': 'huile minérale',
    'motoröl': 'huile moteur',
    'hydrauliköl': 'huile hydraulique',
    'getriebeöl': 'huile de transmission',
    'schmieröl': 'huile lubrifiante',
    'maschinenöl': 'huile de machine',
    'transformatoröl': 'huile de transformateur',
    'turbinenöl': 'huile de turbine',
    'schneidöl': 'huile de coupe',
    'bohröl': 'huile de forage',
    'öl': 'huile',
    'fett': 'graisse',
    'schmierfett': 'graisse lubrifiante',
    'paraffin': 'paraffine',
    'paraffinöl': 'huile de paraffine',
    'vaseline': 'vaseline',
    'wachs': 'cire',
    'bitumen': 'bitume',
    'asphalt': 'asphalte',
    'teer': 'goudron',
    'pech': 'poix',
    
    # Food & beverages
    'bier': 'bière',
    'wein': 'vin',
    'rotwein': 'vin rouge',
    'weisswein': 'vin blanc',
    'weißwein': 'vin blanc',
    'champagner': 'champagne',
    'sekt': 'vin mousseux',
    'schnaps': 'eau-de-vie',
    'whisky': 'whisky',
    'wodka': 'vodka',
    'rum': 'rhum',
    'cognac': 'cognac',
    'likör': 'liqueur',
    'essig': 'vinaigre',
    'weinessig': 'vinaigre de vin',
    'apfelessig': 'vinaigre de cidre',
    'milch': 'lait',
    'vollmilch': 'lait entier',
    'magermilch': 'lait écrémé',
    'buttermilch': 'babeurre',
    'sahne': 'crème',
    'rahm': 'crème',
    'butter': 'beurre',
    'käse': 'fromage',
    'joghurt': 'yaourt',
    'molke': 'lactosérum',
    'fruchtsaft': 'jus de fruits',
    'orangensaft': 'jus d\'orange',
    'apfelsaft': 'jus de pomme',
    'traubensaft': 'jus de raisin',
    'limonade': 'limonade',
    'cola': 'cola',
    'kaffee': 'café',
    'tee': 'thé',
    'kakao': 'cacao',
    'schokolade': 'chocolat',
    'zucker': 'sucre',
    'glucose': 'glucose',
    'fructose': 'fructose',
    'maltose': 'maltose',
    'lactose': 'lactose',
    'saccharose': 'saccharose',
    'stärke': 'amidon',
    'mehl': 'farine',
    'salz': 'sel',
    'kochsalz': 'sel de table',
    'speisesalz': 'sel de cuisine',
    'pfeffer': 'poivre',
    'senf': 'moutarde',
    'honig': 'miel',
    'marmelade': 'confiture',
    'gelatine': 'gélatine',
    
    # Biological & medical
    'blut': 'sang',
    'serum': 'sérum',
    'plasma': 'plasma',
    'urin': 'urine',
    'kot': 'matières fécales',
    'fäkalien': 'matières fécales',
    'speichel': 'salive',
    'schweiss': 'sueur',
    'schweiß': 'sueur',
    'tränen': 'larmes',
    'eiter': 'pus',
    'galle': 'bile',
    'magensäure': 'acide gastrique',
    'magensaft': 'suc gastrique',
    'insulin': 'insuline',
    'penicillin': 'pénicilline',
    'antibiotikum': 'antibiotique',
    'aspirin': 'aspirine',
    'vitamin': 'vitamine',
    'hormon': 'hormone',
    'enzym': 'enzyme',
    'protein': 'protéine',
    'eiweiss': 'protéine',
    'eiweiß': 'protéine',
    
    # Cleaning & household
    'seife': 'savon',
    'kernseife': 'savon de Marseille',
    'flüssigseife': 'savon liquide',
    'waschmittel': 'détergent',
    'spülmittel': 'liquide vaisselle',
    'reinigungsmittel': 'agent de nettoyage',
    'desinfektionsmittel': 'désinfectant',
    'bleichmittel': 'eau de Javel',
    'bleiche': 'eau de Javel',
    'entkalker': 'détartrant',
    'rostentferner': 'antirouille',
    'fleckenentferner': 'détachant',
    'politur': 'polish',
    'möbelpolitur': 'cire à meubles',
    
    # Industry
    'tinte': 'encre',
    'druckfarbe': 'encre d\'imprimerie',
    'lack': 'laque',
    'farbe': 'peinture',
    'anstrichfarbe': 'peinture',
    'grundierung': 'apprêt',
    'kleber': 'colle',
    'klebstoff': 'adhésif',
    'leim': 'colle',
    'harz': 'résine',
    'kunstharz': 'résine synthétique',
    'epoxidharz': 'résine époxy',
    'polyesterharz': 'résine polyester',
    'phenolharz': 'résine phénolique',
    'gummi': 'caoutchouc',
    'kautschuk': 'caoutchouc',
    'latex': 'latex',
    'silikon': 'silicone',
    'kunststoff': 'plastique',
    'polymer': 'polymère',
    'zellulose': 'cellulose',
    'zellstoff': 'pâte à papier',
    'papier': 'papier',
    'karton': 'carton',
    'holz': 'bois',
    'leder': 'cuir',
    'wolle': 'laine',
    'baumwolle': 'coton',
    'seide': 'soie',
    'nylon': 'nylon',
    'polyester': 'polyester',
    'acryl': 'acrylique',
    'glas': 'verre',
    'keramik': 'céramique',
    'porzellan': 'porcelaine',
    'beton': 'béton',
    'zement': 'ciment',
    'gips': 'plâtre',
    'kalk': 'chite',
    'branntkalk': 'chaux vive',
    'löschkalk': 'chaux éteinte',
    'kalkmilch': 'lait de chaux',
    'kreide': 'craie',
    'marmor': 'marbre',
    'granit': 'granite',
    'sand': 'sable',
    'kies': 'gravier',
    'ton': 'argile',
    'lehm': 'argile',
    'torf': 'tourbe',
    'kohle': 'charbon',
    'steinkohle': 'houille',
    'braunkohle': 'lignite',
    'koks': 'coke',
    'graphit': 'graphite',
    'diamant': 'diamant',
    'ruß': 'suie',
    'russ': 'suie',
    'asche': 'cendre',
    
    # Concentration terms
    'konzentriert': 'concentré',
    'rein': 'pur',
    'technisch': 'technique',
    'unverdünnt': 'non dilué',
    'verdünnt': 'dilué',
    'gesättigt': 'saturé',
    'wässrig': 'aqueux',
    'wasserfrei': 'anhydre',
    'flüssig': 'liquide',
    'fest': 'solide',
    'gasförmig': 'gazeux',
    'kristallin': 'cristallin',
    'pulverförmig': 'en poudre',
    
    # Prefixes
    'mono': 'mono',
    'di': 'di',
    'tri': 'tri',
    'tetra': 'tétra',
    'penta': 'penta',
    'hexa': 'hexa',
    'hepta': 'hepta',
    'octa': 'octa',
    'nona': 'nona',
    'deca': 'déca',
    'poly': 'poly',
    'iso': 'iso',
    'neo': 'néo',
    'ortho': 'ortho',
    'meta': 'méta',
    'para': 'para',
    'cis': 'cis',
    'trans': 'trans',
    'alpha': 'alpha',
    'beta': 'bêta',
    'gamma': 'gamma',
    'delta': 'delta',
    'n-': 'n-',
    
    # Exhaust gases
    'abgase': 'gaz d\'échappement',
    'rauchgase': 'fumées',
    'abgas': 'gaz d\'échappement',
    
    # Descriptors
    'alkalisch': 'alcalin',
    'sauer': 'acide',
    'neutral': 'neutre',
    'basisch': 'basique',
    'oxidierend': 'oxydant',
    'reduzierend': 'réducteur',
    'ätzend': 'corrosif',
    'giftig': 'toxique',
    'brennbar': 'inflammable',
    'explosiv': 'explosif',
    'schwefelsauer': 'acide sulfurique',
    'salzsauer': 'acide chlorhydrique',
    'fluorwasserstoffhaltig': 'contenant de l\'acide fluorhydrique',
    'kohlendioxidhaltig': 'contenant du dioxyde de carbone',
    'nitrosehaltig': 'contenant des oxydes d\'azote',
    'salzsäurehaltig': 'contenant de l\'acide chlorhydrique',
    'schwefeldioxidhaltig': 'contenant du dioxyde de soufre',
    'schwefelsäurehaltig': 'contenant de l\'acide sulfurique',
    'schwefeltrioxidhaltig': 'contenant du trioxyde de soufre',
    
    # Common word parts at end
    'lösung': 'solution',
    'lösungsmittel': 'solvant',
    'gemisch': 'mélange',
    'verbindung': 'composé',
    'pulver': 'poudre',
    'paste': 'pâte',
    'emulsion': 'émulsion',
    'suspension': 'suspension',
    'dispersion': 'dispersion',
}

def translate_chemical_name(german_name):
    """Translate a German chemical name to French."""
    result = german_name.lower()
    
    # Try exact match first
    if result in TERM_TRANSLATIONS:
        return TERM_TRANSLATIONS[result].title()
    
    # Apply translations from longest to shortest (more specific first)
    sorted_terms = sorted(TERM_TRANSLATIONS.keys(), key=len, reverse=True)
    
    for de_term in sorted_terms:
        if de_term in result:
            result = result.replace(de_term, TERM_TRANSLATIONS[de_term])
    
    # Capitalize appropriately (title case for chemical names)
    # But keep lowercase for prefixes like di-, tri-, etc.
    words = result.split()
    capitalized = []
    for i, word in enumerate(words):
        if i == 0:
            capitalized.append(word.capitalize())
        elif word in ['de', 'd\'', 'et', 'ou', 'à', 'en']:
            capitalized.append(word)
        elif word.startswith(('di', 'tri', 'tétra', 'penta', 'hexa', 'mono', 'poly', 'iso', 'n-', 'o-', 'm-', 'p-')):
            capitalized.append(word)
        else:
            capitalized.append(word)
    
    return ' '.join(capitalized)


def main():
    # Load chemical data
    with open('data/chemicals_burkle_full.json', 'r', encoding='utf-8') as f:
        chemicals = json.load(f)
    
    # Get unique names and translate
    names = sorted(set(c['name'] for c in chemicals))
    
    translations = {}
    for name in names:
        translated = translate_chemical_name(name)
        # Only add if translation is different from original
        if translated.lower() != name.lower():
            translations[name.lower()] = translated
    
    print(f"Translated {len(translations)} of {len(names)} chemical names")
    
    # Output as JavaScript object
    js_output = "// German → French chemical name translations\n"
    js_output += "// Auto-generated - " + str(len(translations)) + " translations\n"
    js_output += "const chemicalTranslations = {\n"
    
    for de, fr in sorted(translations.items()):
        # Escape quotes
        de_escaped = de.replace("'", "\\'")
        fr_escaped = fr.replace("'", "\\'")
        js_output += f"    '{de_escaped}': '{fr_escaped}',\n"
    
    js_output += "};\n"
    
    # Save to file
    with open('js/chemical_translations_fr.js', 'w', encoding='utf-8') as f:
        f.write(js_output)
    
    print(f"Saved translations to js/chemical_translations_fr.js")
    
    # Also print some samples
    print("\nSample translations:")
    samples = list(translations.items())[:20]
    for de, fr in samples:
        print(f"  {de} → {fr}")


if __name__ == '__main__':
    main()
