#!/usr/bin/env python3
"""
Comprehensive German → Portuguese chemical name translator
Uses proper Portuguese chemical nomenclature (IUPAC-PT)
"""

import json
import re

# Comprehensive manual translations for common chemicals
MANUAL_TRANSLATIONS = {
    # Exhaust gases
    'abgase, alkalisch': 'Gases de escape, alcalinos',
    'abgase, fluorwasserstoffhaltig': 'Gases de escape contendo HF',
    'abgase, kohlendioxidhaltig': 'Gases de escape contendo CO₂',
    'abgase, nitrosehaltig': 'Gases de escape contendo NOx',
    'abgase, salzsäurehaltig': 'Gases de escape contendo HCl',
    'abgase, schwefeldioxidhaltig': 'Gases de escape contendo SO₂',
    'abgase, schwefelsäurehaltig': 'Gases de escape contendo H₂SO₄',
    'abgase, schwefeltrioxidhaltig': 'Gases de escape contendo SO₃',
    
    # Esters (säure...ester patterns)
    'acrylsäurebutylester': 'Acrilato de butila',
    'acrylsäureethylester': 'Acrilato de etila',
    'acrylsäuremethylester': 'Acrilato de metila',
    'ameisensäureethylester': 'Formiato de etila',
    'ameisensäuremethylester': 'Formiato de metila',
    'essigsäureethylester': 'Acetato de etila',
    'essigsäuremethylester': 'Acetato de metila',
    'essigsäurebutylester': 'Acetato de butila',
    'essigsäureamylester': 'Acetato de amila',
    'essigsäurepropylester': 'Acetato de propila',
    'essigsäureisopropylester': 'Acetato de isopropila',
    'essigsäureisobutylester': 'Acetato de isobutila',
    'milchsäureethylester': 'Lactato de etila',
    'adipinsäuredioctylester': 'Adipato de dioctila',
    'phthalsäuredibutylester': 'Ftalato de dibutila',
    'phthalsäuredioctylester': 'Ftalato de dioctila',
    'phthalsäurediethylester': 'Ftalato de dietila',
    'phthalsäuredimethylester': 'Ftalato de dimetila',
    'ölsäuremethylester': 'Oleato de metila',
    'ölsäuremethoxyethylester': 'Oleato de metoxietila',
    'stearinsäuremethylester': 'Estearato de metila',
    'palmitinsäuremethylester': 'Palmitato de metila',
    'buttersäureethylester': 'Butirato de etila',
    'propionsäureethylester': 'Propionato de etila',
    
    # Amides
    'ameisensäureamid': 'Formamida',
    'essigsäureamid': 'Acetamida',
    'acrylsäureamid': 'Acrilamida',
    
    # More complex organics
    'acetamino-4-ethoxybenzol, 1-': 'Fenacetina',
    'acetoxybenzoesäure, 2-': 'Ácido acetilsalicílico',
    'acetylsalicylsäure': 'Ácido acetilsalicílico',
    'aminobenzol': 'Anilina',
    'aminoessigsäure': 'Glicina',
    'aminoethanol, 2-': 'Etanolamina',
    'aminoethanol': 'Etanolamina',
    'monoethanolamin': 'Monoetanolamina',
    'diethanolamin': 'Dietanolamina',
    'triethanolamin': 'Trietanolamina',
    'ethylendiamin': 'Etilenodiamina',
    'propylendiamin': 'Propilenodiamina',
    'diethylamin': 'Dietilamina',
    'triethylamin': 'Trietilamina',
    'dimethylamin': 'Dimetilamina',
    'trimethylamin': 'Trimetilamina',
    'methylamin': 'Metilamina',
    'ethylamin': 'Etilamina',
    'propylamin': 'Propilamina',
    'butylamin': 'Butilamina',
    'hexylamin': 'Hexilamina',
    'cyclohexylamin': 'Ciclo-hexilamina',
    'benzylamin': 'Benzilamina',
    'dibutylamin': 'Dibutilamina',
    'morpholin': 'Morfolina',
    'piperidin': 'Piperidina',
    'pyrrolidin': 'Pirrolidina',
    
    # Chlorinated compounds
    'vinylchlorid': 'Cloreto de vinila',
    'vinylidenchlorid': 'Cloreto de vinilideno',
    'methylchlorid': 'Cloreto de metila',
    'ethylchlorid': 'Cloreto de etila',
    'propylchlorid': 'Cloreto de propila',
    'butylchlorid': 'Cloreto de butila',
    'acetylchlorid': 'Cloreto de acetila',
    'benzoylchlorid': 'Cloreto de benzoíla',
    'thionylchlorid': 'Cloreto de tionila',
    'sulfurylchlorid': 'Cloreto de sulfurila',
    'phosphorylchlorid': 'Cloreto de fosforila',
    'phosphortrichlorid': 'Tricloreto de fósforo',
    'phosphorpentachlorid': 'Pentacloreto de fósforo',
    'antimontrichlorid': 'Tricloreto de antimônio',
    'arsenochlorid': 'Cloreto de arsênio',
    'siliciumtetrachlorid': 'Tetracloreto de silício',
    'titantetrachlorid': 'Tetracloreto de titânio',
    
    # Fluorinated
    'schwefelhexafluorid': 'Hexafluoreto de enxofre',
    'bortrifluorid': 'Trifluoreto de boro',
    'siliciumtetrafluorid': 'Tetrafluoreto de silício',
    
    # Cyanides and related
    'blausäure': 'Ácido cianídrico',
    'cyanwasserstoff': 'Ácido cianídrico',
    'acetoncyanhydrin': 'Cianidrina de acetona',
    'acrylnitril': 'Acrilonitrila',
    'acetonitril': 'Acetonitrila',
    'benzonitril': 'Benzonitrila',
    'adiponitril': 'Adiponitrila',
    
    # Phenols and aromatics
    'phenol': 'Fenol',
    'kresol': 'Cresol',
    'o-kresol': 'o-Cresol',
    'm-kresol': 'm-Cresol',
    'p-kresol': 'p-Cresol',
    'xylenol': 'Xilenol',
    'resorcin': 'Resorcinol',
    'hydrochinon': 'Hidroquinona',
    'brenzkatechin': 'Catecol',
    'pyrogallol': 'Pirogalol',
    'nitrophenol': 'Nitrofenol',
    'chlorphenol': 'Clorofenol',
    'pentachlorphenol': 'Pentaclorofenol',
    'bisphenol a': 'Bisfenol A',
    
    # Ketones
    'methylethylketon': 'Metiletilcetona',
    'methylisobutylketon': 'Metilisobutilcetona',
    'diethylketon': 'Dietilcetona',
    'diisobutylketon': 'Diisobutilcetona',
    'mesityloxid': 'Óxido de mesitila',
    'isophoron': 'Isoforona',
    'acetophenon': 'Acetofenona',
    'benzophenon': 'Benzofenona',
    
    # Ethers
    'methyltertbutylether': 'MTBE',
    'mtbe': 'MTBE',
    'diisopropylether': 'Éter diisopropílico',
    'dibutylether': 'Éter dibutílico',
    'anisol': 'Anisol',
    'phenetol': 'Fenetol',
    
    # Glycol ethers
    'ethylenglykolmonoethylether': 'Cellosolve',
    'ethylenglykolmonomethylether': 'Metilcellosolve',
    'ethylenglykolmonobutylether': 'Butilcellosolve',
    'diethylenglykolmonoethylether': 'Carbitol',
    'diethylenglykolmonomethylether': 'Metilcarbitol',
    'propylenglykolmonomethylether': 'PGME',
    
    # Oils and fats
    'öle und fette, pflanzlich': 'Óleos e gorduras vegetais',
    'öle und fette, tierisch': 'Óleos e gorduras animais',
    'öle und fette, mineralisch': 'Óleos e gorduras minerais',
    'öle, ätherisch': 'Óleos essenciais',
    'fette': 'Gorduras',
    'wachse': 'Ceras',
    'bienenwachs': 'Cera de abelha',
    'carnaubawachs': 'Cera de carnaúba',
    
    # Battery and industrial
    'akkusäure': 'Ácido de bateria',
    'batteriesäure': 'Ácido de bateria',
    'fotoentwickler': 'Revelador fotográfico',
    'fixierbad': 'Fixador fotográfico',
    'galvanisierbad': 'Banho de galvanização',
    'beizbad': 'Banho de decapagem',
    
    # More salts with complex names
    'kaliumaluminiumsulfat': 'Sulfato de potássio e alumínio',
    'aluminiumkaliumsulfat': 'Sulfato de potássio e alumínio',
    'kaliumnatriumtartrat': 'Tartarato de sódio e potássio',
    'natriumkaliumtartrat': 'Tartarato de sódio e potássio',
    'kaliumbitartrat': 'Bitartarato de potássio',
    'natriumbitartrat': 'Bitartarato de sódio',
    'kaliumhydrogentartrat': 'Hidrogenotartarato de potássio',
    'natriumlaurylsulfat': 'Laurilsulfato de sódio',
    'natriumdodecylsulfat': 'Dodecilsulfato de sódio',
    'natriumhydrogensulfit': 'Bissulfito de sódio',
    'kaliumhydrogensulfit': 'Bissulfito de potássio',
    'natriummetabisulfit': 'Metabissulfito de sódio',
    'kaliummetabisulfit': 'Metabissulfito de potássio',
    'natriumperborat': 'Perborato de sódio',
    'natriumtripolyphosphat': 'Tripolifosfato de sódio',
    'natriumhexametaphosphat': 'Hexametafosfato de sódio',
    'zeolithe': 'Zeólitas',
    
    # Misc industrial
    'photoresist': 'Fotorresiste',
    'entwickler': 'Revelador',
    'lebensmittel': 'Alimentos',
    'getränke': 'Bebidas',
    'kosmetika': 'Cosméticos',
    'pharmazeutika': 'Fármacos',
    'pflanzenschutzmittel': 'Defensivos agrícolas',
    'herbizide': 'Herbicidas',
    'insektizide': 'Inseticidas',
    'fungizide': 'Fungicidas',
    'desinfektionsmittel': 'Desinfetantes',
    'konservierungsmittel': 'Conservantes',
    'weichmacher': 'Plastificantes',
    'antioxidantien': 'Antioxidantes',
    'stabilisatoren': 'Estabilizantes',
    'emulgatoren': 'Emulsificantes',
    'tenside': 'Tensoativos',
    'flammschutzmittel': 'Retardantes de chama',
    'farbstoffe': 'Corantes',
    'pigmente': 'Pigmentos',
    'füllstoffe': 'Cargas',
    
    # Specific compounds
    'acetylentetrabromid': 'Tetrabrometo de acetileno',
    'acetylentetrachlorid': 'Tetracloreto de acetileno',
    'chlorameisensäure': 'Cloroformiato',
    'chlorameisensäuremethylester': 'Cloroformiato de metila',
    'chlorameisensäureethylester': 'Cloroformiato de etila',
    'diazomethan': 'Diazometano',
    'dimethylhydrazin': 'Dimetil-hidrazina',
    'nitrosamine': 'Nitrosaminas',
    'nitroglycerin': 'Nitroglicerina',
    'trinitrotoluol': 'Trinitrotolueno',
    'tnt': 'TNT',
    'hexogen': 'RDX',
    'oktogen': 'HMX',
    
    # More alcohols
    'furfurylalkohol': 'Álcool furfurílico',
    'tetrahydrofurfurylalkohol': 'Álcool tetra-hidrofurfurílico',
    'diacetonealkohol': 'Álcool diacetona',
    'diacetonalkohol': 'Álcool diacetona',
    
    # Aldehydes
    'propionaldehyd': 'Propionaldeído',
    'butyraldehyd': 'Butiraldeído',
    'isobutyraldehyd': 'Isobutiraldeído',
    'valeraldehyd': 'Valeraldeído',
    'crotonaldehyd': 'Crotonaldeído',
    'acrolein': 'Acroleína',
    'glyoxal': 'Glioxal',
    'furfural': 'Furfural',
    'furfurol': 'Furfural',
    'zimtaldehyd': 'Cinamaldeído',
    
    # Specific German terms
    'ätzkali': 'Potassa cáustica',
    'ätzkalk': 'Cal viva',
    'ätznatron': 'Soda cáustica',
    'branntkalk': 'Cal viva',
    'löschkalk': 'Cal apagada',
    'sumpfkalk': 'Cal apagada',
    'marmor': 'Mármore',
    'kalkstein': 'Calcário',
    'dolomit': 'Dolomita',
    'flussspat': 'Fluorita',
    'schwerspat': 'Barita',
    'magnesit': 'Magnesita',
    'bauxit': 'Bauxita',
    
    # Solutions
    'grignard-lösung': 'Solução de Grignard',
    'fehling-lösung': 'Solução de Fehling',
    'benedict-lösung': 'Solução de Benedict',
    'lugol-lösung': 'Solução de Lugol',
    'jodlösung': 'Solução de iodo',
    'iodlösung': 'Solução de iodo',
    # Common acids
    'essigsäure': 'Ácido acético',
    'salzsäure': 'Ácido clorídrico',
    'schwefelsäure': 'Ácido sulfúrico',
    'salpetersäure': 'Ácido nítrico',
    'phosphorsäure': 'Ácido fosfórico',
    'flusssäure': 'Ácido fluorídrico',
    'fluorwasserstoffsäure': 'Ácido fluorídrico',
    'ameisensäure': 'Ácido fórmico',
    'milchsäure': 'Ácido lático',
    'zitronensäure': 'Ácido cítrico',
    'oxalsäure': 'Ácido oxálico',
    'weinsäure': 'Ácido tartárico',
    'benzoesäure': 'Ácido benzoico',
    'stearinsäure': 'Ácido esteárico',
    'ölsäure': 'Ácido oleico',
    'palmitinsäure': 'Ácido palmítico',
    'kohlensäure': 'Ácido carbônico',
    'borsäure': 'Ácido bórico',
    'chromsäure': 'Ácido crômico',
    'perchlorsäure': 'Ácido perclórico',
    'blausäure': 'Ácido cianídrico',
    'cyanwasserstoffsäure': 'Ácido cianídrico',
    'kieselsäure': 'Ácido silícico',
    'harnsäure': 'Ácido úrico',
    'propionsäure': 'Ácido propiônico',
    'buttersäure': 'Ácido butírico',
    'bernsteinsäure': 'Ácido succínico',
    'maleinsäure': 'Ácido maleico',
    'fumarsäure': 'Ácido fumárico',
    'acrylsäure': 'Ácido acrílico',
    'methacrylsäure': 'Ácido metacrílico',
    'adipinsäure': 'Ácido adípico',
    'capronsäure': 'Ácido caproico',
    'laurinsäure': 'Ácido láurico',
    'myristinsäure': 'Ácido mirístico',
    'linolsäure': 'Ácido linoleico',
    'linolensäure': 'Ácido linolênico',
    'glykolsäure': 'Ácido glicólico',
    'glukonsäure': 'Ácido glucônico',
    'ascorbinsäure': 'Ácido ascórbico',
    'pikrinsäure': 'Ácido pícrico',
    'phthalsäure': 'Ácido ftálico',
    'terephthalsäure': 'Ácido tereftálico',
    'isophthalsäure': 'Ácido isoftálico',
    'sulfaminsäure': 'Ácido sulfâmico',
    'trifluoressigsäure': 'Ácido trifluoroacético',
    'trichloressigsäure': 'Ácido tricloroacético',
    'dichloressigsäure': 'Ácido dicloroacético',
    'monochloressigsäure': 'Ácido monocloroacético',
    'chloressigsäure': 'Ácido cloroacético',
    'peressigsäure': 'Ácido peracético',
    'thioglykolsäure': 'Ácido tioglicólico',
    'bromwasserstoffsäure': 'Ácido bromídrico',
    'iodwasserstoffsäure': 'Ácido iodídrico',
    'selensäure': 'Ácido selênico',
    'selenige säure': 'Ácido selenioso',
    'schweflige säure': 'Ácido sulfuroso',
    'salpetrige säure': 'Ácido nitroso',
    'unterchlorige säure': 'Ácido hipocloroso',
    'hypochlorige säure': 'Ácido hipocloroso',
    'chlorige säure': 'Ácido cloroso',
    'jodsäure': 'Ácido iódico',
    'periodsäure': 'Ácido periódico',
    'arsensäure': 'Ácido arsênico',
    'arsenige säure': 'Ácido arsenioso',
    'wolframsäure': 'Ácido túngstico',
    'molybdänsäure': 'Ácido molíbdico',
    'kieselflusssäure': 'Ácido fluossilícico',
    'hexafluorokieselsäure': 'Ácido hexafluorossilícico',
    
    # Bases and hydroxides
    'natronlauge': 'Hidróxido de sódio (solução)',
    'kalilauge': 'Hidróxido de potássio (solução)',
    'ammoniak': 'Amônia',
    'ammoniakwasser': 'Hidróxido de amônio',
    'ammoniumhydroxid': 'Hidróxido de amônio',
    'natriumhydroxid': 'Hidróxido de sódio',
    'kaliumhydroxid': 'Hidróxido de potássio',
    'calciumhydroxid': 'Hidróxido de cálcio',
    'bariumhydroxid': 'Hidróxido de bário',
    'magnesiumhydroxid': 'Hidróxido de magnésio',
    'aluminiumhydroxid': 'Hidróxido de alumínio',
    'lithiumhydroxid': 'Hidróxido de lítio',
    'kalkwasser': 'Água de cal',
    'kalkmilch': 'Leite de cal',
    
    # Common salts - chlorides
    'natriumchlorid': 'Cloreto de sódio',
    'kaliumchlorid': 'Cloreto de potássio',
    'calciumchlorid': 'Cloreto de cálcio',
    'magnesiumchlorid': 'Cloreto de magnésio',
    'bariumchlorid': 'Cloreto de bário',
    'aluminiumchlorid': 'Cloreto de alumínio',
    'eisenchlorid': 'Cloreto de ferro',
    'eisen(iii)chlorid': 'Cloreto de ferro(III)',
    'eisen(ii)chlorid': 'Cloreto de ferro(II)',
    'kupferchlorid': 'Cloreto de cobre',
    'kupfer(ii)chlorid': 'Cloreto de cobre(II)',
    'zinkchlorid': 'Cloreto de zinco',
    'zinnchlorid': 'Cloreto de estanho',
    'zinn(ii)chlorid': 'Cloreto de estanho(II)',
    'zinn(iv)chlorid': 'Cloreto de estanho(IV)',
    'ammoniumchlorid': 'Cloreto de amônio',
    'lithiumchlorid': 'Cloreto de lítio',
    'nickelchlorid': 'Cloreto de níquel',
    'kobaltchlorid': 'Cloreto de cobalto',
    'manganchlorid': 'Cloreto de manganês',
    'chromchlorid': 'Cloreto de cromo',
    'quecksilberchlorid': 'Cloreto de mercúrio',
    'quecksilber(ii)chlorid': 'Cloreto de mercúrio(II)',
    'silberchlorid': 'Cloreto de prata',
    'bleichlorid': 'Cloreto de chumbo',
    'antimonchlorid': 'Cloreto de antimônio',
    'wismutchlorid': 'Cloreto de bismuto',
    'cadmiumchlorid': 'Cloreto de cádmio',
    'strontiumchlorid': 'Cloreto de estrôncio',
    
    # Sulfates
    'natriumsulfat': 'Sulfato de sódio',
    'kaliumsulfat': 'Sulfato de potássio',
    'calciumsulfat': 'Sulfato de cálcio',
    'magnesiumsulfat': 'Sulfato de magnésio',
    'bariumsulfat': 'Sulfato de bário',
    'aluminiumsulfat': 'Sulfato de alumínio',
    'eisensulfat': 'Sulfato de ferro',
    'eisen(ii)sulfat': 'Sulfato de ferro(II)',
    'eisen(iii)sulfat': 'Sulfato de ferro(III)',
    'kupfersulfat': 'Sulfato de cobre',
    'zinksulfat': 'Sulfato de zinco',
    'nickelsulfat': 'Sulfato de níquel',
    'ammoniumsulfat': 'Sulfato de amônio',
    'kobaltsulfat': 'Sulfato de cobalto',
    'mangansulfat': 'Sulfato de manganês',
    'chromsulfat': 'Sulfato de cromo',
    'cadmiumsulfat': 'Sulfato de cádmio',
    
    # Nitrates
    'natriumnitrat': 'Nitrato de sódio',
    'kaliumnitrat': 'Nitrato de potássio',
    'calciumnitrat': 'Nitrato de cálcio',
    'magnesiumnitrat': 'Nitrato de magnésio',
    'bariumnitrat': 'Nitrato de bário',
    'aluminiumnitrat': 'Nitrato de alumínio',
    'eisennitrat': 'Nitrato de ferro',
    'kupfernitrat': 'Nitrato de cobre',
    'zinknitrat': 'Nitrato de zinco',
    'bleinitrat': 'Nitrato de chumbo',
    'silbernitrat': 'Nitrato de prata',
    'ammoniumnitrat': 'Nitrato de amônio',
    'nickelnitrat': 'Nitrato de níquel',
    'kobaltnitrat': 'Nitrato de cobalto',
    'quecksilbernitrat': 'Nitrato de mercúrio',
    
    # Carbonates
    'natriumcarbonat': 'Carbonato de sódio',
    'kaliumcarbonat': 'Carbonato de potássio',
    'calciumcarbonat': 'Carbonato de cálcio',
    'magnesiumcarbonat': 'Carbonato de magnésio',
    'bariumcarbonat': 'Carbonato de bário',
    'lithiumcarbonat': 'Carbonato de lítio',
    'ammoniumcarbonat': 'Carbonato de amônio',
    'natriumhydrogencarbonat': 'Bicarbonato de sódio',
    'kaliumhydrogencarbonat': 'Bicarbonato de potássio',
    'soda': 'Carbonato de sódio',
    
    # Phosphates
    'natriumphosphat': 'Fosfato de sódio',
    'kaliumphosphat': 'Fosfato de potássio',
    'calciumphosphat': 'Fosfato de cálcio',
    'ammoniumphosphat': 'Fosfato de amônio',
    'natriumdihydrogenphosphat': 'Fosfato de sódio monobásico',
    'dinatriumhydrogenphosphat': 'Fosfato de sódio dibásico',
    'trinatriumphosphat': 'Fosfato trissódico',
    
    # Acetates
    'natriumacetat': 'Acetato de sódio',
    'kaliumacetat': 'Acetato de potássio',
    'calciumacetat': 'Acetato de cálcio',
    'magnesiumacetat': 'Acetato de magnésio',
    'ammoniumacetat': 'Acetato de amônio',
    'bleiacetat': 'Acetato de chumbo',
    'kupferacetat': 'Acetato de cobre',
    'zinkacetat': 'Acetato de zinco',
    'eisenacetat': 'Acetato de ferro',
    'aluminiumacetat': 'Acetato de alumínio',
    
    # Other salts
    'natriumhypochlorit': 'Hipoclorito de sódio',
    'calciumhypochlorit': 'Hipoclorito de cálcio',
    'natriumchlorit': 'Clorito de sódio',
    'natriumchlorat': 'Clorato de sódio',
    'kaliumchlorat': 'Clorato de potássio',
    'natriumperchlorat': 'Perclorato de sódio',
    'kaliumperchlorat': 'Perclorato de potássio',
    'natriumbromat': 'Bromato de sódio',
    'kaliumbromat': 'Bromato de potássio',
    'natriumjodat': 'Iodato de sódio',
    'kaliumjodat': 'Iodato de potássio',
    'natriumsulfit': 'Sulfito de sódio',
    'natriumthiosulfat': 'Tiossulfato de sódio',
    'natriumsulfid': 'Sulfeto de sódio',
    'kaliumsulfid': 'Sulfeto de potássio',
    'natriumcyanid': 'Cianeto de sódio',
    'kaliumcyanid': 'Cianeto de potássio',
    'natriumfluorid': 'Fluoreto de sódio',
    'kaliumfluorid': 'Fluoreto de potássio',
    'natriumiodid': 'Iodeto de sódio',
    'kaliumiodid': 'Iodeto de potássio',
    'natriumbromid': 'Brometo de sódio',
    'kaliumbromid': 'Brometo de potássio',
    'natriumsilicat': 'Silicato de sódio',
    'kaliumsilicat': 'Silicato de potássio',
    'natriumborat': 'Borato de sódio',
    'borax': 'Bórax',
    'kaliumpermanganat': 'Permanganato de potássio',
    'kaliumdichromat': 'Dicromato de potássio',
    'natriumdichromat': 'Dicromato de sódio',
    'natriumchromat': 'Cromato de sódio',
    'kaliumchromat': 'Cromato de potássio',
    'ammoniumsulfid': 'Sulfeto de amônio',
    
    # Oxides
    'natriumoxid': 'Óxido de sódio',
    'kaliumoxid': 'Óxido de potássio',
    'calciumoxid': 'Óxido de cálcio',
    'magnesiumoxid': 'Óxido de magnésio',
    'bariumoxid': 'Óxido de bário',
    'aluminiumoxid': 'Óxido de alumínio',
    'eisenoxid': 'Óxido de ferro',
    'kupferoxid': 'Óxido de cobre',
    'zinkoxid': 'Óxido de zinco',
    'titanoxid': 'Óxido de titânio',
    'titandioxid': 'Dióxido de titânio',
    'siliciumdioxid': 'Dióxido de silício',
    'kohlendioxid': 'Dióxido de carbono',
    'schwefeldioxid': 'Dióxido de enxofre',
    'schwefeltrioxid': 'Trióxido de enxofre',
    'stickstoffdioxid': 'Dióxido de nitrogênio',
    'stickstoffmonoxid': 'Monóxido de nitrogênio',
    'distickstoffoxid': 'Óxido nitroso',
    'distickstoffmonoxid': 'Óxido nitroso',
    'kohlenmonoxid': 'Monóxido de carbono',
    'bleioxid': 'Óxido de chumbo',
    'quecksilberoxid': 'Óxido de mercúrio',
    'nickeloxid': 'Óxido de níquel',
    'chromoxid': 'Óxido de cromo',
    'manganoxid': 'Óxido de manganês',
    'antimonoxid': 'Óxido de antimônio',
    'arsenoxid': 'Óxido de arsênio',
    'wasserstoffperoxid': 'Peróxido de hidrogênio',
    'natriumperoxid': 'Peróxido de sódio',
    'bariumperoxid': 'Peróxido de bário',
    
    # Common solvents
    'aceton': 'Acetona',
    'methanol': 'Metanol',
    'ethanol': 'Etanol',
    'propanol': 'Propanol',
    'isopropanol': 'Isopropanol',
    '2-propanol': 'Isopropanol',
    'butanol': 'Butanol',
    'isobutanol': 'Isobutanol',
    'pentanol': 'Pentanol',
    'hexanol': 'Hexanol',
    'heptanol': 'Heptanol',
    'octanol': 'Octanol',
    'benzylalkohol': 'Álcool benzílico',
    'ethylenglykol': 'Etilenoglicol',
    'ethylenglycol': 'Etilenoglicol',
    'propylenglykol': 'Propilenoglicol',
    'propylenglycol': 'Propilenoglicol',
    'glycerin': 'Glicerina',
    'glyzerin': 'Glicerina',
    'glycerol': 'Glicerol',
    'diethylenglykol': 'Dietilenoglicol',
    'triethylenglykol': 'Trietilenoglicol',
    'benzol': 'Benzeno',
    'toluol': 'Tolueno',
    'xylol': 'Xileno',
    'styrol': 'Estireno',
    'chloroform': 'Clorofórmio',
    'tetrachlorkohlenstoff': 'Tetracloreto de carbono',
    'dichlormethan': 'Diclorometano',
    'methylenchlorid': 'Diclorometano',
    'trichlorethylen': 'Tricloroetileno',
    'tetrachlorethylen': 'Tetracloroetileno',
    'perchlorethylen': 'Percloroetileno',
    'chlorbenzol': 'Clorobenzeno',
    'dichlorbenzol': 'Diclorobenzeno',
    'diethylether': 'Éter dietílico',
    'ether': 'Éter',
    'petrolether': 'Éter de petróleo',
    'tetrahydrofuran': 'Tetra-hidrofurano',
    'thf': 'THF',
    'dioxan': 'Dioxano',
    '1,4-dioxan': '1,4-Dioxano',
    'dimethylformamid': 'Dimetilformamida',
    'dmf': 'DMF',
    'dimethylsulfoxid': 'Dimetilsulfóxido',
    'dmso': 'DMSO',
    'dimethylacetamid': 'Dimetilacetamida',
    'acetonitril': 'Acetonitrila',
    'pyridin': 'Piridina',
    'cyclohexan': 'Ciclo-hexano',
    'cyclohexanol': 'Ciclo-hexanol',
    'cyclohexanon': 'Ciclo-hexanona',
    'hexan': 'Hexano',
    'heptan': 'Heptano',
    'octan': 'Octano',
    'pentan': 'Pentano',
    'dekalin': 'Decalina',
    'naphthalin': 'Naftaleno',
    'methylethylketon': 'Metiletilcetona',
    'mek': 'MEK',
    'methylisobutylketon': 'Metil isobutil cetona',
    'mibk': 'MIBK',
    'ethylacetat': 'Acetato de etila',
    'butylacetat': 'Acetato de butila',
    'methylacetat': 'Acetato de metila',
    'amylacetat': 'Acetato de amila',
    'isopropylacetat': 'Acetato de isopropila',
    'ethylenglykolmonoethylether': 'Cellosolve',
    
    # Fuels and oils
    'benzin': 'Gasolina',
    'diesel': 'Diesel',
    'dieselkraftstoff': 'Combustível diesel',
    'heizöl': 'Óleo combustível',
    'petroleum': 'Petróleo',
    'kerosin': 'Querosene',
    'schmieröl': 'Óleo lubrificante',
    'motoröl': 'Óleo de motor',
    'hydrauliköl': 'Óleo hidráulico',
    'mineralöl': 'Óleo mineral',
    'silikonöl': 'Óleo de silicone',
    'olivenöl': 'Azeite de oliva',
    'leinöl': 'Óleo de linhaça',
    'rizinusöl': 'Óleo de rícino',
    'sojaöl': 'Óleo de soja',
    'palmöl': 'Óleo de palma',
    'kokosöl': 'Óleo de coco',
    'rapsöl': 'Óleo de canola',
    'sonnenblumenöl': 'Óleo de girassol',
    'erdnussöl': 'Óleo de amendoim',
    'pflanzenöl': 'Óleo vegetal',
    'terpentinöl': 'Óleo de terebintina',
    'terpentin': 'Terebintina',
    'paraffin': 'Parafina',
    'paraffinöl': 'Óleo de parafina',
    'weissöl': 'Óleo branco',
    
    # Common chemicals
    'wasser': 'Água',
    'destilliertes wasser': 'Água destilada',
    'meerwasser': 'Água do mar',
    'salzwasser': 'Água salgada',
    'trinkwasser': 'Água potável',
    'abwasser': 'Água residual',
    'chlorwasser': 'Água clorada',
    'bromwasser': 'Água de bromo',
    'iodwasser': 'Água de iodo',
    'königswasser': 'Água régia',
    'formaldehyd': 'Formaldeído',
    'formalin': 'Formalina',
    'acetaldehyd': 'Acetaldeído',
    'glutaraldehyd': 'Glutaraldeído',
    'benzaldehyd': 'Benzaldeído',
    'phenol': 'Fenol',
    'kresol': 'Cresol',
    'hydrochinon': 'Hidroquinona',
    'resorcin': 'Resorcinol',
    'anilin': 'Anilina',
    'nitrobenzol': 'Nitrobenzeno',
    'chlor': 'Cloro',
    'brom': 'Bromo',
    'iod': 'Iodo',
    'jod': 'Iodo',
    'fluor': 'Flúor',
    'schwefel': 'Enxofre',
    'phosphor': 'Fósforo',
    'ozon': 'Ozônio',
    'wasserstoff': 'Hidrogênio',
    'sauerstoff': 'Oxigênio',
    'stickstoff': 'Nitrogênio',
    'argon': 'Argônio',
    'helium': 'Hélio',
    'neon': 'Neônio',
    'harnstoff': 'Ureia',
    'thioharnstoff': 'Tioureia',
    'hydrazin': 'Hidrazina',
    'hydroxylamin': 'Hidroxilamina',
    'schwefelwasserstoff': 'Sulfeto de hidrogênio',
    'chlorwasserstoff': 'Cloreto de hidrogênio',
    'fluorwasserstoff': 'Fluoreto de hidrogênio',
    'bromwasserstoff': 'Brometo de hidrogênio',
    'iodwasserstoff': 'Iodeto de hidrogênio',
    'phosgen': 'Fosgênio',
    'acetylen': 'Acetileno',
    'ethin': 'Acetileno',
    'ethylen': 'Etileno',
    'ethen': 'Etileno',
    'propylen': 'Propileno',
    'propen': 'Propileno',
    'butan': 'Butano',
    'isobutan': 'Isobutano',
    'propan': 'Propano',
    'methan': 'Metano',
    'ethan': 'Etano',
    'erdgas': 'Gás natural',
    'flüssiggas': 'GLP',
    'lpg': 'GLP',
    
    # Food and beverage
    'milch': 'Leite',
    'bier': 'Cerveja',
    'wein': 'Vinho',
    'essig': 'Vinagre',
    'zucker': 'Açúcar',
    'saccharose': 'Sacarose',
    'glukose': 'Glicose',
    'dextrose': 'Dextrose',
    'fruktose': 'Frutose',
    'laktose': 'Lactose',
    'maltose': 'Maltose',
    'stärke': 'Amido',
    'gelatine': 'Gelatina',
    'kasein': 'Caseína',
    'koffein': 'Cafeína',
    'zitronensaft': 'Suco de limão',
    'fruchtsaft': 'Suco de frutas',
    'melasse': 'Melaço',
    'honig': 'Mel',
    
    # Cleaning and household
    'seife': 'Sabão',
    'seifenlauge': 'Água com sabão',
    'waschmittel': 'Detergente',
    'reinigungsmittel': 'Produto de limpeza',
    'bleichmittel': 'Água sanitária',
    'bleichlauge': 'Solução alvejante',
    'chlorbleichlauge': 'Água sanitária clorada',
    
    # Industrial
    'kalk': 'Cal',
    'gebrannter kalk': 'Cal viva',
    'gelöschter kalk': 'Cal apagada',
    'chlorkalk': 'Cal clorada',
    'gips': 'Gesso',
    'zement': 'Cimento',
    'beton': 'Concreto',
    'asphalt': 'Asfalto',
    'bitumen': 'Betume',
    'teer': 'Alcatrão',
    'steinkohlenteer': 'Alcatrão de carvão',
    'kreosot': 'Creosoto',
    'kreide': 'Giz',
    'ton': 'Argila',
    'kaolin': 'Caulim',
    'kochsalz': 'Sal de cozinha',
    'kochsalzlösung': 'Solução salina',
    'sole': 'Salmoura',
    'salzlösung': 'Solução salina',
    
    # Polymers and plastics
    'latex': 'Látex',
    'kautschuk': 'Borracha natural',
    'naturkautschuk': 'Borracha natural',
    'gummi': 'Borracha',
    'silikon': 'Silicone',
    'harz': 'Resina',
    'epoxidharz': 'Resina epóxi',
    'polyesterharz': 'Resina de poliéster',
    'kunstharz': 'Resina sintética',
    'phenolharz': 'Resina fenólica',
    'lack': 'Verniz',
    'farbe': 'Tinta',
    'lösungsmittel': 'Solvente',
    'verdünner': 'Diluente',
    'klebstoff': 'Adesivo',
    'leim': 'Cola',
    'cellulose': 'Celulose',
    
    # Metals
    'aluminium': 'Alumínio',
    'eisen': 'Ferro',
    'kupfer': 'Cobre',
    'zink': 'Zinco',
    'blei': 'Chumbo',
    'zinn': 'Estanho',
    'nickel': 'Níquel',
    'chrom': 'Cromo',
    'mangan': 'Manganês',
    'kobalt': 'Cobalto',
    'titan': 'Titânio',
    'vanadium': 'Vanádio',
    'molybdän': 'Molibdênio',
    'wolfram': 'Tungstênio',
    'silber': 'Prata',
    'gold': 'Ouro',
    'platin': 'Platina',
    'palladium': 'Paládio',
    'quecksilber': 'Mercúrio',
    'cadmium': 'Cádmio',
    'antimon': 'Antimônio',
    'wismut': 'Bismuto',
    'arsen': 'Arsênio',
    'selen': 'Selênio',
    'tellur': 'Telúrio',
    'natrium': 'Sódio',
    'kalium': 'Potássio',
    'calcium': 'Cálcio',
    'magnesium': 'Magnésio',
    'barium': 'Bário',
    'lithium': 'Lítio',
    'strontium': 'Estrôncio',
    'beryllium': 'Berílio',
    
    # Amino acids
    'glycin': 'Glicina',
    'alanin': 'Alanina',
    'valin': 'Valina',
    'leucin': 'Leucina',
    'isoleucin': 'Isoleucina',
    'methionin': 'Metionina',
    'phenylalanin': 'Fenilalanina',
    'tyrosin': 'Tirosina',
    'tryptophan': 'Triptofano',
    'serin': 'Serina',
    'threonin': 'Treonina',
    'cystein': 'Cisteína',
    'prolin': 'Prolina',
    'asparagin': 'Asparagina',
    'glutamin': 'Glutamina',
    'lysin': 'Lisina',
    'arginin': 'Arginina',
    'histidin': 'Histidina',
    'asparaginsäure': 'Ácido aspártico',
    'glutaminsäure': 'Ácido glutâmico',
    
    # Other organics
    'essigsäureanhydrid': 'Anidrido acético',
    'acetanhydrid': 'Anidrido acético',
    'maleinsäureanhydrid': 'Anidrido maleico',
    'phthalsäureanhydrid': 'Anidrido ftálico',
    'acrylnitril': 'Acrilonitrila',
    'ethylenoxid': 'Óxido de etileno',
    'propylenoxid': 'Óxido de propileno',
    'butylenoxid': 'Óxido de butileno',
    'epichlorhydrin': 'Epicloridrina',
    'allylalkohol': 'Álcool alílico',
    'allylchlorid': 'Cloreto de alila',
    'vinylchlorid': 'Cloreto de vinila',
    'vinylacetat': 'Acetato de vinila',
    'methylmethacrylat': 'Metacrilato de metila',
    'mma': 'MMA',
    'caprolactam': 'Caprolactama',
    'adiponitril': 'Adiponitrila',
    'hexamethylendiamin': 'Hexametilenodiamina',
    'toluylendiisocyanat': 'Diisocianato de tolueno',
    'tdi': 'TDI',
    'diphenylmethandiisocyanat': 'Diisocianato de difenilmetano',
    'mdi': 'MDI',
    'bisphenol a': 'Bisfenol A',
    
    # Misc
    'alaune': 'Alúmen',
    'ätzkali': 'Potassa cáustica',
    'ätznatron': 'Soda cáustica',
    'aktivkohle': 'Carvão ativado',
    'kieselgur': 'Terra de diatomáceas',
    'perlit': 'Perlita',
    'vermiculit': 'Vermiculita',
    'talkum': 'Talco',
    'glimmer': 'Mica',
    'graphit': 'Grafite',
    'russ': 'Negro de fumo',
    'kohle': 'Carvão',
    'holzkohle': 'Carvão vegetal',
    'koks': 'Coque',
    'quarz': 'Quartzo',
    'feldspat': 'Feldspato',
    'glassand': 'Areia de vidro',
}

# Pattern-based translations (suffix replacements)
SUFFIX_PATTERNS = [
    # Acids
    (r'säure$', 'ácido'),
    (r'säuren$', 'ácidos'),
    
    # Salts - anions
    (r'chlorid$', 'cloreto'),
    (r'fluorid$', 'fluoreto'),
    (r'bromid$', 'brometo'),
    (r'iodid$', 'iodeto'),
    (r'jodid$', 'iodeto'),
    (r'sulfat$', 'sulfato'),
    (r'sulfit$', 'sulfito'),
    (r'sulfid$', 'sulfeto'),
    (r'nitrat$', 'nitrato'),
    (r'nitrit$', 'nitrito'),
    (r'phosphat$', 'fosfato'),
    (r'carbonat$', 'carbonato'),
    (r'hydrogencarbonat$', 'bicarbonato'),
    (r'bicarbonat$', 'bicarbonato'),
    (r'acetat$', 'acetato'),
    (r'formiat$', 'formiato'),
    (r'oxalat$', 'oxalato'),
    (r'citrat$', 'citrato'),
    (r'tartrat$', 'tartarato'),
    (r'lactat$', 'lactato'),
    (r'benzoat$', 'benzoato'),
    (r'stearat$', 'estearato'),
    (r'oleat$', 'oleato'),
    (r'palmitat$', 'palmitato'),
    (r'silicat$', 'silicato'),
    (r'silikat$', 'silicato'),
    (r'borat$', 'borato'),
    (r'chromat$', 'cromato'),
    (r'dichromat$', 'dicromato'),
    (r'permanganat$', 'permanganato'),
    (r'molybdat$', 'molibdato'),
    (r'wolframat$', 'tungstato'),
    (r'vanadat$', 'vanadato'),
    (r'arsenat$', 'arsenato'),
    (r'arsenit$', 'arsenito'),
    (r'cyanid$', 'cianeto'),
    (r'cyanat$', 'cianato'),
    (r'thiocyanat$', 'tiocianato'),
    (r'rhodanid$', 'tiocianato'),
    (r'hypochlorit$', 'hipoclorito'),
    (r'chlorit$', 'clorito'),
    (r'chlorat$', 'clorato'),
    (r'perchlorat$', 'perclorato'),
    (r'bromat$', 'bromato'),
    (r'jodat$', 'iodato'),
    (r'iodat$', 'iodato'),
    (r'periodat$', 'periodato'),
    (r'thiosulfat$', 'tiossulfato'),
    (r'persulfat$', 'persulfato'),
    (r'peroxid$', 'peróxido'),
    (r'hydroxid$', 'hidróxido'),
    (r'oxid$', 'óxido'),
    
    # Organic suffixes
    (r'alkohol$', 'álcool'),
    (r'ol$', 'ol'),
    (r'aldehyd$', 'aldeído'),
    (r'al$', 'al'),
    (r'keton$', 'cetona'),
    (r'on$', 'ona'),
    (r'amin$', 'amina'),
    (r'amid$', 'amida'),
    (r'ester$', 'éster'),
    (r'ether$', 'éter'),
    (r'anhydrid$', 'anidrido'),
    (r'nitril$', 'nitrila'),
    (r'glycol$', 'glicol'),
    (r'glykol$', 'glicol'),
]

# Prefix patterns for cation names
CATION_PREFIXES = {
    'natrium': 'sódio',
    'kalium': 'potássio',
    'calcium': 'cálcio',
    'magnesium': 'magnésio',
    'barium': 'bário',
    'strontium': 'estrôncio',
    'lithium': 'lítio',
    'aluminium': 'alumínio',
    'eisen': 'ferro',
    'kupfer': 'cobre',
    'zink': 'zinco',
    'nickel': 'níquel',
    'kobalt': 'cobalto',
    'mangan': 'manganês',
    'chrom': 'cromo',
    'blei': 'chumbo',
    'zinn': 'estanho',
    'silber': 'prata',
    'quecksilber': 'mercúrio',
    'cadmium': 'cádmio',
    'antimon': 'antimônio',
    'wismut': 'bismuto',
    'titan': 'titânio',
    'vanadium': 'vanádio',
    'wolfram': 'tungstênio',
    'molybdän': 'molibdênio',
    'ammonium': 'amônio',
}

def translate_chemical(name):
    """Translate a German chemical name to Portuguese"""
    lower = name.lower().strip()
    
    # Check manual translations first
    if lower in MANUAL_TRANSLATIONS:
        return MANUAL_TRANSLATIONS[lower]
    
    # Try pattern-based translation
    result = lower
    translated = False
    
    # Check for cation + anion pattern (e.g., "natriumchlorid")
    for cation_de, cation_pt in sorted(CATION_PREFIXES.items(), key=lambda x: -len(x[0])):
        if result.startswith(cation_de):
            remainder = result[len(cation_de):]
            for pattern, replacement in SUFFIX_PATTERNS:
                match = re.search(pattern, remainder)
                if match:
                    anion_pt = replacement
                    # Format: "Cloreto de sódio"
                    result = f"{anion_pt.capitalize()} de {cation_pt}"
                    translated = True
                    break
            if translated:
                break
    
    # If not a salt pattern, try simple suffix replacement
    if not translated:
        for pattern, replacement in SUFFIX_PATTERNS:
            if re.search(pattern, result):
                result = re.sub(pattern, replacement, result)
                translated = True
                break
    
    # Capitalize properly
    if translated:
        # Handle "de" and other prepositions
        words = result.split()
        capitalized = []
        skip_caps = {'de', 'do', 'da', 'dos', 'das', 'e', 'em', 'com', 'para', 'por'}
        for i, word in enumerate(words):
            if i == 0 or word not in skip_caps:
                capitalized.append(word.capitalize())
            else:
                capitalized.append(word)
        return ' '.join(capitalized)
    
    # Return original with capitalization if no translation found
    return name.capitalize() if name else name

def main():
    # Load chemicals
    with open('data/chemicals_burkle_full.json', 'r', encoding='utf-8') as f:
        chemicals = json.load(f)
    
    # Build translations
    translations = {}
    for chem in chemicals:
        german_name = chem['name']
        lower = german_name.lower()
        if lower not in translations:
            pt_name = translate_chemical(german_name)
            translations[lower] = pt_name
    
    # Sort by key
    sorted_translations = dict(sorted(translations.items()))
    
    # Count translated vs untranslated
    translated_count = sum(1 for k, v in sorted_translations.items() if k != v.lower())
    
    # Generate JS file
    js_content = "// German → Portuguese chemical name translations\n"
    js_content += f"// Comprehensive translation - {len(sorted_translations)} chemicals\n"
    js_content += f"// Translated: {translated_count}, Kept original: {len(sorted_translations) - translated_count}\n"
    js_content += "const chemicalTranslations = {\n"
    
    for key, value in sorted_translations.items():
        # Escape quotes
        escaped_key = key.replace("'", "\\'").replace("\\", "\\\\")
        escaped_value = value.replace("'", "\\'").replace("\\", "\\\\")
        js_content += f"    '{escaped_key}': '{escaped_value}',\n"
    
    js_content += "};\n"
    
    # Write output
    with open('js/chemical_translations_pt.js', 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print(f"Generated {len(sorted_translations)} translations")
    print(f"  - Translated: {translated_count}")
    print(f"  - Kept original: {len(sorted_translations) - translated_count}")
    print("Output: js/chemical_translations_pt.js")

if __name__ == '__main__':
    main()
