#!/usr/bin/env python3
"""Translate remaining German chemical names to Spanish"""

import json

# Complete translations for remaining chemicals
TRANSLATIONS = {
    'Amylzimtaldehyd': 'Aldehído amilcinámico',
    'Anisol': 'Anisol',
    'Butantriol': 'Butanotriol',
    'Butylacrylat': 'Acrilato de butilo',
    'Butylamin': 'Butilamina',
    'Butylenglycol': 'Butilenglicol',
    'Butylglycol': 'Butilglicol',
    'Butylphenol': 'Butilfenol',
    'Butylphenol, p-tertiär': 'Butilfenol, p-terciario',
    'Butyraldehyd': 'Butiraldehído',
    'Carbazol': 'Carbazol',
    'Carbolineum': 'Carbolineo',
    'Clophen A60': 'Clophen A60',
    'Crotonaldehyd': 'Crotonaldehído',
    'Cumol': 'Cumeno',
    'Curry': 'Curry',
    'Cyclanon': 'Ciclanona',
    'Cymol, p-': 'p-Cimeno',
    'DDT (Emulsion)': 'DDT (Emulsión)',
    'Decahydronaphtalin': 'Decahidronaftaleno',
    'Decan': 'Decano',
    'Densodrin W': 'Densodrin W',
    'Desmodur 44': 'Desmodur 44',
    'Dibenzylether': 'Éter dibencílico',
    'Dibenzylsebacat': 'Sebacato de dibencilo',
    'Dibromethan-1,2': '1,2-Dibromoetano',
    'Dibromtetrafluormethan': 'Dibromtetrafluorometano',
    'Dibutylamin': 'Dibutilamina',
    'Dibutylether': 'Éter dibutílico',
    'Dibutylphthalat': 'Ftalato de dibutilo',
    'Dibutylsebacat': 'Sebacato de dibutilo',
    'Dichlorbenzol, 1,2-': '1,2-Diclorobenceno',
    'Dichlorbenzol, 1,4-': '1,4-Diclorobenceno',
    'Dichlordifluormethan': 'Diclorodifluorometano',
    'Dichlorethylen': 'Dicloroetileno',
    'Dichlorfluormethan': 'Diclorofluorometano',
    'Dichlor-hexafluorcyclobutan': 'Dicloro-hexafluorociclobutano',
    'Dichlorisopropylether': 'Éter dicloroisopropílico',
    'Dichlorpropan': 'Dicloropropano',
    'Dichlortetrafluorethan': 'Diclorotetrafluoroetano',
    'Dicyclohexylamin (DCHA)': 'Diciclohexilamina (DCHA)',
    'Dicyclohexylphthalat': 'Ftalato de diciclohexilo',
    'Diethanolamin (DEA)': 'Dietanolamina (DEA)',
    'Diethylamin': 'Dietilamina',
    'Diethylbenzol': 'Dietilbenceno',
    'Diethylenglycol': 'Dietilenglicol',
    'Diethylenglycolether': 'Éter de dietilenglicol',
    'Diethylketon': 'Dietilcetona',
    'Diethylmalonat': 'Malonato de dietilo',
    'Diethylsebacat': 'Sebacato de dietilo',
    'Difluorchlorethan': 'Difluorocloroetano',
    'Difluorethan': 'Difluoroetano',
    'Difluormethan': 'Difluorometano',
    'Difluortetrachlorethan': 'Difluorotetracloroetano',
    'Diisobutylen (DIB)': 'Diisobutileno (DIB)',
    'Diisobutylketon': 'Diisobutilcetona',
    'Diisooctylphthalat (DOP)': 'Ftalato de diisooctilo (DOP)',
    'Diisopropylketon': 'Diisopropilcetona',
    'Dimethylamin': 'Dimetilamina',
    'Dimethylanilin': 'Dimetilanilina',
    'Dimethylether': 'Éter dimetílico',
    'Dimethylphthalat (DMP)': 'Ftalato de dimetilo (DMP)',
    'Dinonylphthalat (DNP)': 'Ftalato de dinonilo (DNP)',
    'Dioctyladipat': 'Adipato de dioctilo',
    'Dioctylsebacat': 'Sebacato de dioctilo',
    'Diphenylamin': 'Difenilamina',
    'Diphenylether': 'Éter difenílico',
    'Diphyl': 'Difilo',
    'Dipropylenglycol': 'Dipropilenglicol',
    'Dipropylketon': 'Dipropilcetona',
    'Emulgatoren': 'Emulsionantes',
    'Ephetin': 'Efetina',
    'Epichlorhydrin': 'Epiclorhidrina',
    'Erdgas': 'Gas natural',
    'Ethanthiol': 'Etanotiol',
    'Ethylacrylat': 'Acrilato de etilo',
    'Ethylbenzol': 'Etilbenceno',
    'Ethylbutyrat': 'Butirato de etilo',
    'Ethylen': 'Etileno',
    'Ethylendiamin': 'Etilendiamina',
    'Ethylenglycol': 'Etilenglicol',
    'Ethylether': 'Éter etílico',
    'Ethylformiat': 'Formiato de etilo',
    'Ethylglycol': 'Etilglicol',
    'Ethylhexanol-1': '1-Etilhexanol',
    'Ethyllactat': 'Lactato de etilo',
    'Ferricyankalium': 'Ferricianuro de potasio',
    'Ferrocyankalium': 'Ferrocianuro de potasio',
    'Fischtran': 'Aceite de pescado',
    'Flugmotorenkraftstoffe (JP)': 'Combustible de aviación (JP)',
    'Fluid 101, 100°C': 'Fluido 101, 100°C',
    'Flüssigseifen': 'Jabones líquidos',
    'Formamid': 'Formamida',
    'Fotoemulsionen': 'Emulsiones fotográficas',
    'Fotoentwickler': 'Revelador fotográfico',
    'Fotofixierbäder': 'Baños fijadores fotográficos',
    'Frostschutzmittel (KFZ)': 'Anticongelante (automóvil)',
    'Fruchtsäfte': 'Jugos de frutas',
    'Furan': 'Furano',
    'Gärungsmaische': 'Mosto de fermentación',
    'Gasoline': 'Gasolina',
    'Genantin': 'Genantina',
    'Gerbeextrakte, pflanzlich': 'Extractos de curtido, vegetales',
    'Gerbextrakte': 'Extractos de curtido',
    'Glysantin': 'Glisantina',
    'Grubengas': 'Grisú',
    'Hefe': 'Levadura',
    'Hexachlorbenzol (HCB)': 'Hexaclorobenceno (HCB)',
    'Hexachlorbutadien (HCBD)': 'Hexaclorobutadieno (HCBD)',
    'Hexachlorcyclohexan (HCH)': 'Hexaclorociclohexano (HCH)',
    'Hexamethylentetramin': 'Hexametilentetramina',
    'Hexen, 1-': '1-Hexeno',
    'Hydrazinhydrat': 'Hidrato de hidracina',
    'Hydrochinon': 'Hidroquinona',
    'Ingwer': 'Jengibre',
    'Isobutanol': 'Isobutanol',
    'Isobutylmethylketon': 'Isobutilmetilcetona',
    'Isooctan': 'Isooctano',
    'Isopropanol': 'Isopropanol',
    'Isopropylether': 'Éter isopropílico',
    'Isopropylmethylketon': 'Isopropilmetilcetona',
    'Kakao': 'Cacao',
    'Kakaobutter': 'Manteca de cacao',
    'Kardamom': 'Cardamomo',
    'Kautschukdispersion': 'Dispersión de caucho',
    'Kraftstoff, Normal': 'Combustible, normal',
    'Kraftstoff, Super': 'Combustible, súper',
    'Kreide': 'Tiza',
    'Kresol (-Gemische)': 'Cresol (mezclas)',
    'Kümmel': 'Comino',
    'Lachgas': 'Gas de la risa (óxido nitroso)',
    'Lactame': 'Lactamas',
    'Lactose': 'Lactosa',
    'Lanolin': 'Lanolina',
    'Ligroin': 'Ligroína',
    'Liköre': 'Licores',
    'Limonen, DL-': 'DL-Limoneno',
    'Lorbeer': 'Laurel',
    'Lysol': 'Lisol',
    'Melassewürze': 'Mosto de melaza',
    'Methoxybutanol': 'Metoxibutanol',
    'Methoxyethyloleat': 'Oleato de metoxietilo',
    'Methyethylether': 'Éter metil etílico',
    'Methylacrylat': 'Acrilato de metilo',
    'Methylamin, (Mono-)': 'Metilamina (mono-)',
    'Methylbenzol': 'Metilbenceno (tolueno)',
    'Methylbutanol': 'Metilbutanol',
    'Methylbutylketon': 'Metilbutilcetona',
    'Methylcyclohexan': 'Metilciclohexano',
    'Methylcyclopentan': 'Metilciclopentano',
    'Methylethylketon (MEK)': 'Metiletilcetona (MEK)',
    'Methylformiat': 'Formiato de metilo',
    'Methylglycol': 'Metilglicol',
    'Methylmethacrylat': 'Metacrilato de metilo',
    'Methyloleat': 'Oleato de metilo',
    'Methylpropylketon': 'Metilpropilcetona',
    'Methylsalicylat': 'Salicilato de metilo',
    'Mowilith D': 'Mowilith D',
    'Muskat': 'Nuez moscada',
    'Nagellackentferner': 'Quitaesmalte',
    'Nelken': 'Clavos de olor',
    'Netzmittel': 'Agentes humectantes',
    'Nicotin': 'Nicotina',
    'Nitroethan': 'Nitroetano',
    'Nitroglycol': 'Nitroglicol',
    'Nitropropan': 'Nitropropano',
    'Nitrose Gase': 'Gases nitrosos',
    'Nitrotoluole': 'Nitrotoluenos',
    'Nitroverdünnung': 'Diluyente nitro',
    'Nonanol': 'Nonanol',
    'Obstpulp': 'Pulpa de fruta',
    'Obstwein': 'Vino de frutas',
    'Octafluor-cyclobutan': 'Octafluorociclobutano',
    'Octan, n-': 'n-Octano',
    'Octylkresol': 'Octilcresol',
    'Oleumdämpfe': 'Vapores de óleum',
    'Oxymethylfurfurol, 5-': '5-Oximetilfurfural',
    'Paraffine': 'Parafinas',
    'Paraffinemulsion': 'Emulsión de parafina',
    'Paraffinwachs': 'Cera de parafina',
    'Paraformaldehyd': 'Paraformaldehído',
    'Parfüms': 'Perfumes',
    'Pectin': 'Pectina',
    'Penicillin': 'Penicilina',
    'Pentachlordiphenyl': 'Pentaclorodifenilo',
    'Pentanthiol, 1-': '1-Pentanotiol',
    'Perfluorpropan': 'Perfluoropropano',
    'Petrolether': 'Éter de petróleo',
    'Pfeffer': 'Pimienta',
    'Phenacetin': 'Fenacetina',
    'Phenylethanol': 'Feniletanol',
    'Phenylethylether': 'Éter feniletílico',
    'Phenylhydrazin': 'Fenilhidracina',
    'Phenylhydrazin-HCl': 'Fenilhidracina-HCl',
    'Phenylsulfonat': 'Fenilsulfonato',
    'Phosphin': 'Fosfina',
    'Piment': 'Pimienta de Jamaica',
    'Piperidin': 'Piperidina',
    'Polyesterharze': 'Resinas de poliéster',
    'Polyethylenglycol': 'Polietilenglicol',
    'Polyran M25 N': 'Polyran M25 N',
    'Polyran M400': 'Polyran M400',
    'Polysolvan O': 'Polysolvan O',
    'Pressluft': 'Aire comprimido',
    'Prontosil': 'Prontosil',
    'Propylamin, n-': 'n-Propilamina',
    'Propylenglycol': 'Propilenglicol',
    'Propylenglycolmethylether': 'Éter metílico de propilenglicol',
    'Pseudocumol': 'Pseudocumeno',
    'Pydraul C (312, 540)': 'Pydraul C (312, 540)',
    'Pydraul E (29, 30, 50, 65, 90, 11)': 'Pydraul E (29, 30, 50, 65, 90, 11)',
    'Pyrogallol': 'Pirogalol',
    'Pyrrol': 'Pirrol',
    'Ramasit': 'Ramasit',
    'Resorcin': 'Resorcinol',
    'Rindertalg': 'Sebo de res',
    'Rindertalg-Emulsion': 'Emulsión de sebo de res',
    'Röstgase': 'Gases de tostado',
    'Rumaroma': 'Aroma de ron',
    'Sagrotan': 'Sagrotan',
    'Salicylaldehyd': 'Salicilaldehído',
    'Sattdampfkondensat': 'Condensado de vapor saturado',
    'Schmierseife': 'Jabón blando',
    'Senf': 'Mostaza',
    'Skydrol 500 (B4)': 'Skydrol 500 (B4)',
    'Skydrol 7000': 'Skydrol 7000',
    'Spirituosen': 'Bebidas espirituosas',
    'Strychnin': 'Estricnina',
    'Tannin': 'Tanino',
    'Testbenzin': 'Bencina de prueba',
    'Testkraftstoff A (ISO-Fluid A)': 'Combustible de prueba A (ISO-Fluid A)',
    'Testkraftstoff B (ISO-Fluid B)': 'Combustible de prueba B (ISO-Fluid B)',
    'Testkraftstoff C (ISO-Fluid C)': 'Combustible de prueba C (ISO-Fluid C)',
    'Testkraftstoff D (ISO-Fluid D)': 'Combustible de prueba D (ISO-Fluid D)',
    'Tetrabromethan (TBE)': 'Tetrabromoetano (TBE)',
    'Tetrabromkohlenstoff': 'Tetrabromuro de carbono',
    'Tetrachlorethan': 'Tetracloroetano',
    'Tetraethylblei (TEL)': 'Tetraetilplomo (TEL)',
    'Tetraethylorthosilicat': 'Ortosilicato de tetraetilo',
    'Tetrafluormethan': 'Tetrafluorometano',
    'Tetrahydronaphthalin': 'Tetrahidronaftaleno',
    'Thiophen': 'Tiofeno',
    'Thymol': 'Timol',
    'Traganth': 'Tragacanto',
    'Triacetin': 'Triacetina',
    'Tributylcitrat': 'Citrato de tributilo',
    'Trichloracetaldehyd': 'Tricloroacetaldehído',
    'Trichlorbenzol': 'Triclorobenceno',
    'Trichlorethan': 'Tricloroetano',
    'Trichlorfluormethan': 'Triclorofluorometano',
    'Trichlorphenol': 'Triclorofenol',
    'Trichlortrifluorethan': 'Triclorotrifluoroetano',
    'Triethanolamin (TEA)': 'Trietanolamina (TEA)',
    'Triethylamin (TEA)': 'Trietilamina (TEA)',
    'Trifluortrichlorethan': 'Trifluorotricloroetano',
    'Triglycol': 'Triglicol',
    'Triisopropylbenzol': 'Triisopropilbenceno',
    'Trimethylolpropan': 'Trimetilolpropano',
    'Tripropylenglycol (TPG)': 'Tripropilenglicol (TPG)',
    'Vitamin C': 'Vitamina C',
    'Wachse': 'Ceras',
    'Walrat': 'Esperma de ballena',
    'Whiskey': 'Whisky',
    'White Spirit': 'Aguarrás mineral',
    'Xenon': 'Xenón',
    'Zimt': 'Canela',
    'Zimtaldehyd': 'Cinamaldehído',
    'Zitrussäfte': 'Jugos cítricos',
}

def main():
    with open('data/chemicals.json', 'r', encoding='utf-8') as f:
        chemicals = json.load(f)
    
    updated = 0
    for chem in chemicals:
        name = chem.get('name', '')
        if name in TRANSLATIONS:
            chem['name_es'] = TRANSLATIONS[name]
            updated += 1
    
    with open('data/chemicals.json', 'w', encoding='utf-8') as f:
        json.dump(chemicals, f, ensure_ascii=False, indent=2)
    
    print(f'Updated {updated} chemicals')
    
    # Check remaining
    not_translated = [c for c in chemicals if c['name'] == c.get('name_es', c['name'])]
    print(f'Remaining untranslated: {len(not_translated)}')
    if not_translated:
        print('Still missing:')
        for c in not_translated[:20]:
            print(f'  {c["name"]}')

if __name__ == '__main__':
    main()
